begin;

-- Fail-fast: bu 27 satırın resmi_madde_metni'nin hâlâ boş olduğunu doğrula
do $$
declare dolu_sayisi int;
begin
  select count(*) into dolu_sayisi from public.madde_kutuphanesi
  where madde_id in ('MAD-0893','MAD-0894','MAD-0895','MAD-0896','MAD-0897','MAD-0898','MAD-0899','MAD-0900','MAD-0902','MAD-0903','MAD-0904','MAD-0905','MAD-0906','MAD-0907','MAD-0909','MAD-0910','MAD-0911','MAD-0912','MAD-0913','MAD-0914','MAD-0915','MAD-0916','MAD-0917','MAD-0918','MAD-0919','MAD-0920','MAD-0921') and resmi_madde_metni is not null;
  if dolu_sayisi <> 0 then
    raise exception 'Beklenmeyen durum: % satırda resmi_madde_metni zaten dolu (fail-fast)', dolu_sayisi;
  end if;
end $$;

update public.madde_kutuphanesi set resmi_madde_metni = 'Asansörü çağırmak için sinyal(ler) oluşturan bir çağırma aracı, aşağıdakilerden en az biri yoluyla gerçekleştirilmelidir: a) elle çağırma aygıtı, ör. anahtarlı şalter, bir itfaiyeci asansörünün itfaiyeci asansörü anahtarı (EN 81-72: 2020) veya b) otomatik araçlar, ör. BMS, yangın algılama sistemi.', kontrol_basligi = 'Çağırma aracının gerçekleştirilme yöntemi', denetci_yonlendirmesi = 'Asansörü çağıran sinyalin elle bir aygıtla (anahtarlı şalter, itfaiyeci asansörü anahtarı vb.) mı yoksa otomatik bir kaynaktan (BMS, yangın algılama sistemi) mı geldiğini belirleyip belgede/işaretlerde teyit edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04', standart_madde_no = '5.1.3. | ZA: 1.6.2 4.4 4.10' where madde_id = 'MAD-0893';
update public.madde_kutuphanesi set resmi_madde_metni = 'Elle çağırma aygıtı; iki konumda kararlı çalışmalıdır.', kontrol_basligi = 'Elle çağırma aygıtının konum kararlılığı', denetci_yonlendirmesi = 'Elle çağırma aygıtını (anahtarlı şalter) her iki konumda da test edin; ara konumda takılı kalmadığını, iki kararlı konum arasında net geçiş yaptığını doğrulayın.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0894';
update public.madde_kutuphanesi set resmi_madde_metni = 'Elle çağırma aygıtı; anahtarın konumu ile ilgili herhangi bir hatayı önlemek için hangi konumda olduğu konusunda net görsel gösterge ile donatılmalıdır.', kontrol_basligi = 'Elle çağırma aygıtının konum göstergesi', denetci_yonlendirmesi = 'Elle çağırma aygıtının hangi konumda olduğunu (normal/yangın) net bir görsel göstergeyle belirttiğini kontrol edin; anahtar konumunda belirsizlik/hata riski olmadığını doğrulayın.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0895';
update public.madde_kutuphanesi set resmi_madde_metni = 'Elle çağırma aygıtı; amacına uygun olarak işaretlenmelidir. Herkes tarafından erişilebilir olduğunda, işaretin ebadı, EN ISO 7010:P020, “Yangın anında asansörü kullanmayınız” ibaresine metni dâhil olmaksızın uygun ve en az 50 mm olmalıdır.', kontrol_basligi = 'Elle çağırma aygıtının işaretlenmesi', denetci_yonlendirmesi = 'Elle çağırma aygıtının üzerinde/yanında amacını belirten bir işaret olduğunu, herkesin erişebildiği konumdaysa bu işaretin en az 50 mm boyutunda olduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0896';
update public.madde_kutuphanesi set resmi_madde_metni = 'Elle çağırma aygıtı; binanın yönetim merkezinde veya belirlenmiş durakta yer almalıdır.', kontrol_basligi = 'Elle çağırma aygıtının yeri', denetci_yonlendirmesi = 'Elle çağırma aygıtının binanın yönetim merkezinde veya belirlenmiş durakta konumlandırıldığını doğrulayın.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0897';
update public.madde_kutuphanesi set resmi_madde_metni = 'Elle çağırma aygıtı; hatalı kullanımlara karşı, örneğin, cam bir panel arkasına veya güvenli bir alana yerleştirilerek, korunmalıdır. Bu aygıtlar herkes tarafından erişilebilir olduğunda sıfırlanması için özel bir alet gerekir.', kontrol_basligi = 'Elle çağırma aygıtının hatalı kullanıma karşı korunması', denetci_yonlendirmesi = 'Elle çağırma aygıtının hatalı/yetkisiz kullanıma karşı korunduğunu (örn. cam panel arkası veya güvenli alan) ve herkesin erişebildiği konumdaysa sıfırlama için özel alet gerektiğini kontrol edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0898';
update public.madde_kutuphanesi set resmi_madde_metni = 'Bir arıza nedeniyle asansörün durdurulması hâlinde, yangın algılama sisteminden asansör kumanda sistemine gelen bir sinyal, asansörü harekete geçirmemelidir.', kontrol_basligi = 'Arızalı durdurmada asansörün yeniden harekete geçmemesi', denetci_yonlendirmesi = 'Bir arıza nedeniyle asansör durduğunda, yangın algılama sisteminden gelen sinyalin asansörü yeniden harekete geçirmediğini test edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0899';
update public.madde_kutuphanesi set resmi_madde_metni = 'EN ISO 7010:2020, P020''deki “Yangın anında asansörü kullanmayınız” ifadesine uygun olan yasak işareti, tüm duraklardan kolayca görülebilecek şekilde asansörün yanına yerleştirilmelidir. Bu işaretin büyüklüğü en az 50 mm olmalıdır. “Yangın anında asansörü kullanmayınız” yazısı işarete eklenebilir.', kontrol_basligi = 'Yasak işareti', denetci_yonlendirmesi = 'Asansörün yanına, tüm duraklardan görülebilecek şekilde en az 50 mm boyutunda ''Yangın anında asansörü kullanmayınız'' yasak işaretinin (EN ISO 7010 P020) yerleştirildiğini kontrol edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04', standart_madde_no = '5.1.6. | ZA: 4.4 4.10' where madde_id = 'MAD-0900';
update public.madde_kutuphanesi set resmi_madde_metni = 'Çağırma araçlarından gelen giriş sinyalleri aşağıda belirtilenlerin hiçbirini geçersiz kılmamalıdır: a) elektrik güvenlik aygıtları; b) bakım kumandası (EN 81-20, 5.12.1.5); c) acil durum elektrik kumandası (EN 81-20, 5.12.1.6); d) asansörün sismik moddaki davranışı (EN 81-77, 5.10.4); e) uzaktan alarm sistemi.', kontrol_basligi = 'Çağırma sinyalinin diğer güvenlik fonksiyonlarını geçersiz kılmaması', denetci_yonlendirmesi = 'Yangın çağırma sinyali aktifken elektrik güvenlik devrelerinin, bakım kumandasının, acil durum kumandasının, sismik modun ve uzaktan alarm sisteminin işlevini koruduğunu test edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04', standart_madde_no = '5.3.1. | ZA: 4.4 4.10' where madde_id = 'MAD-0902';
update public.madde_kutuphanesi set resmi_madde_metni = 'Otomatik yangın algılama ve alarm sisteminden veya elle çağırma tertibatından yangını gösteren bir sinyal alındığında, tüm durak kumandaları ve kabindeki kumandalar işlevsiz hâle gelmeli ve tüm mevcut çağrılar iptal edilmelidir.', kontrol_basligi = 'Yangın sinyalinde durak ve kabin kumandalarının devre dışı kalması', denetci_yonlendirmesi = 'Yangın sinyali alındığında tüm durak ve kabin içi çağrı kumandalarının işlevsiz hale geldiğini ve mevcut çağrıların iptal edildiğini test edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0903';
update public.madde_kutuphanesi set resmi_madde_metni = 'Otomatik yangın algılama ve alarm sisteminden veya elle çağırma tertibatından yangını gösteren bir sinyal alındığında, kapı açık ve acil durum alarm düğmeleri çalışır durumda olmalıdır.', kontrol_basligi = 'Yangın sinyalinde kapı açma ve alarm butonlarının çalışır kalması', denetci_yonlendirmesi = 'Yangın sinyali sırasında kapı açma butonunun ve acil durum alarm butonunun çalışır durumda kaldığını doğrulayın.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0904';
update public.madde_kutuphanesi set resmi_madde_metni = 'Otomatik yangın algılama ve alarm sisteminden veya elle çağırma tertibatından yangını gösteren bir sinyal alındığında, asansör; bakım kumandası, acil durum elektrik kumandası veya herhangi bir bakım kontrolü altına alındığında ve bu işlem süresince kabinde ve ilgili makine mahallerinde işitsel bir sinyal duyulmalıdır.', kontrol_basligi = 'Bakım/acil durum kumandasında işitsel sinyal', denetci_yonlendirmesi = 'Asansör bakım kumandası, acil durum elektrik kumandası veya bakım kontrolü altındayken kabin ve makine mahallinde işitsel sinyalin duyulduğunu test edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0905';
update public.madde_kutuphanesi set resmi_madde_metni = 'İşitsel sinyal 55 dB(A) olarak ayarlanan işitsel uyarının ağırlıklandırmalı ses basıncı seviyesi 35 dB(A) ile 65 dB(A) arasında ayarlanabilir olmalıdır. Asansör bakım kumandasından, acil durum elektrik kumandasından veya herhangi bir bakım kontrolünden çıkarıldığında işitsel sinyal iptal edilmelidir.', kontrol_basligi = 'İşitsel sinyalin ses seviyesi ayarı', denetci_yonlendirmesi = 'İşitsel sinyalin ses seviyesinin 35-65 dB(A) arasında ayarlanabilir olduğunu ve bakım/acil durum kumandasından çıkınca sinyalin kesildiğini kontrol edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0906';
update public.madde_kutuphanesi set resmi_madde_metni = 'Durakta durmuş bir asansörün kapıları kapanmalı ve durmaksızın belirtilen sahanlığa gitmelidir. Kapılar kapanana kadar kabin içerisinde bir işitsel sinyal duyulmalıdır.', kontrol_basligi = 'Durakta duran asansörün kapanıp belirlenmiş sahanlığa gitmesi', denetci_yonlendirmesi = 'Durakta duran asansörün kapılarının kapanıp durmaksızın belirlenmiş sahanlığa gittiğini, kapanma sırasında kabin içinde işitsel sinyal duyulduğunu test edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0907';
update public.madde_kutuphanesi set resmi_madde_metni = 'Elle çalıştırılan veya otomatik olmayan ve elektrikle çalıştırılan kapıları bulunan bir asansör, kapıları açık şekilde bir durakta duruyorsa, o durakta hareketsiz olarak kalmalıdır. Kapılar kapalıysa asansör, durmaksızın belirlenmiş sahanlığa gitmelidir.', kontrol_basligi = 'Kapıları açık bekleyen elle/otomatik olmayan kapılı asansörün davranışı', denetci_yonlendirmesi = 'Elle/otomatik olmayan kapılı asansörün, kapıları açıkken durakta hareketsiz kaldığını; kapılar kapalıyken durmaksızın belirlenmiş sahanlığa gittiğini test edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0909';
update public.madde_kutuphanesi set resmi_madde_metni = 'Belirlenmiş duraktan diğer yöne gitmekte olan bir asansör normal şekilde durmalı, mümkün olan en yakın durakta kapılarını açmadan yönünü değiştirmeli ve belirlenmiş sahanlığa geri dönmelidir.', kontrol_basligi = 'Ters yöne giden asansörün belirlenmiş sahanlığa dönüşü', denetci_yonlendirmesi = 'Belirlenmiş sahanlığın tersi yöne giden asansörün normal durup, mümkün olan en yakın durakta kapı açmadan yön değiştirip belirlenmiş sahanlığa döndüğünü test edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0910';
update public.madde_kutuphanesi set resmi_madde_metni = 'Belirlenmiş sahanlığa doğru gitmekte olan bir asansör, belirlenmiş sahanlığa doğru yoluna hiç durmaksızın devam etmelidir. Eğer asansör bir katta durmaya başlamışsa, normal şekilde durması ve kapılarını açmadan belirlenmiş sahanlığa doğru yoluna devam etmesi kabul edilebilir.', kontrol_basligi = 'Belirlenmiş sahanlığa giden asansörün durmadan devam etmesi', denetci_yonlendirmesi = 'Belirlenmiş sahanlığa doğru giden asansörün yolda durmadan (veya durmuşsa kapı açmadan) sahanlığa ulaştığını test edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0911';
update public.madde_kutuphanesi set resmi_madde_metni = 'Hidrolik tahrikli asansörlerde elektrikli kayma önleme sisteminin otomatik en aşağı kata sevk etme işlemi devre dışı bırakılmalıdır.', kontrol_basligi = 'Hidrolik asansörlerde kayma önleme sisteminin devre dışı bırakılması', denetci_yonlendirmesi = 'Hidrolik tahrikli asansörlerde otomatik en-aşağı-kat sevk (kayma önleme) işlevinin yangın modunda devre dışı kaldığını test edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0912';
update public.madde_kutuphanesi set resmi_madde_metni = 'Bağlantılı asansörler grubundaki bir asansörün arızası, diğer asansörlerin belirlenmiş sahanlığa dönüşünü etkilememelidir.', kontrol_basligi = 'Bağlı asansör grubunda arızanın diğerlerini etkilememesi', denetci_yonlendirmesi = 'Bağlantılı asansör grubunda bir asansörün arızasının diğer asansörlerin belirlenmiş sahanlığa dönüşünü engellemediğini test edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0913';
update public.madde_kutuphanesi set resmi_madde_metni = 'Asansör kabini belirlenmiş durağa vardığında, elektrikle çalışan kapıları olan asansörler, kapılarını açmalı ve sesli (ör. sözlü mesaj) ve/veya görsel uyarılar (ör. “yangın alarmı - asansör devre dışı - şimdi asansörü terk ediniz” gibi yazılı bildirimler) yapmalıdır.', kontrol_basligi = 'Belirlenmiş durakta kapı açılması ve tahliye uyarısı', denetci_yonlendirmesi = 'Asansör belirlenmiş durağa vardığında kapıların açıldığını ve sesli/görsel tahliye uyarısının (örn. ''asansörü şimdi terk ediniz'') verildiğini test edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0914';
update public.madde_kutuphanesi set resmi_madde_metni = 'Asansör kabini belirlenmiş durağa vardığında, kapının fiilî bekleme süresi en fazla 20 saniyeyi aştığında, kabin ve durak kapıları kapatılmalı ve asansör hizmet dışı bırakılmalıdır.', kontrol_basligi = 'Bekleme süresi aşımında kapıların kapanıp hizmet dışı bırakılması', denetci_yonlendirmesi = 'Belirlenmiş durakta kapı bekleme süresi 20 saniyeyi aştığında kapıların kapanıp asansörün hizmet dışı bırakıldığını test edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0915';
update public.madde_kutuphanesi set resmi_madde_metni = 'Asansör kabini belirlenmiş durağa vardığında, kapı açma ve acil durum alarm butonları çalışır durumda olmalıdır.', kontrol_basligi = 'Belirlenmiş durakta kapı açma ve alarm butonlarının çalışırlığı', denetci_yonlendirmesi = 'Belirlenmiş durakta kapı açma ve acil durum alarm butonlarının çalışır durumda kaldığını doğrulayın.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0916';
update public.madde_kutuphanesi set resmi_madde_metni = 'İtfaiye personelinin, kabinin katta olup olmadığını ve içeride insanların mahsur kalıp kalmadığını kontrol etmesini sağlamak için, belirlenmiş duraktan gelen kat çağrısı, karşılık gelen belirlenmiş durakta bulunan asansörün kapılarının en fazla 20 s açılmasını sağlamalıdır.', kontrol_basligi = 'İtfaiye personeli için kat çağrısıyla kapı açma süresi', denetci_yonlendirmesi = 'Belirlenmiş duraktan gelen kat çağrısının, o duraktaki asansörün kapılarını en fazla 20 saniye açık tuttuğunu (itfaiye personelinin kabini kontrol edebilmesi için) test edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0917';
update public.madde_kutuphanesi set resmi_madde_metni = 'Ulusal yönetmeliklere göre ve belirlenen durak(lar)da asansör kat kapılarının önünde güvenli bir alan sağlandığında asansör, kabin ve durak kapıları açık olarak bu alanda durur vaziyette bulunabilir. Asansör hizmet dışı bırakılmalıdır.', kontrol_basligi = 'Güvenli alanda kapılar açık bekleme istisnası', denetci_yonlendirmesi = 'Ulusal yönetmeliğe göre güvenli alan sağlanan duraklarda asansörün kapıları açık, hizmet dışı şekilde bu alanda bekleyebildiğini doğrulayın.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0918';
update public.madde_kutuphanesi set resmi_madde_metni = 'Asansör kabini belirlenmiş durağa vardığında, her durumda, kapılar eğer kilit açılma bölgesinde duruyorsa, 300 N’dan daha büyük olmayan bir kuvvet ile aşağıdaki konumlarda kabin ve durak kapısını elle açmak mümkün olmalıdır: a) durak kapısının kilidi acil durum kilit açma anahtarı ile veya kabin kapısı tarafından açıldıktan sonra duraktan, b) kabinin içinden.', kontrol_basligi = 'Kilit açılma bölgesinde kapıların elle açılabilmesi', denetci_yonlendirmesi = 'Kilit açılma bölgesinde durakta, kapıların hem duraktan (acil kilit açma anahtarıyla) hem kabin içinden 300 N''u aşmayan bir kuvvetle elle açılabildiğini test edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0919';
update public.madde_kutuphanesi set resmi_madde_metni = 'Asansör kabini belirlenmiş durağa varıldığında, elle açılan kapılara sahip asansörler hizmet dışı bırakılmalı, kapı(lar) açılmalı ve işitsel (ör. sözlü mesaj) ve/veya görsel uyarı (ör. “yangın alarmı- asansör devre dışı - şimdi asansörü terk ediniz” gibi yazılı bildirimler) yapılmalıdır.', kontrol_basligi = 'Elle açılan kapılı asansörlerde hizmet dışı bırakma ve tahliye uyarısı', denetci_yonlendirmesi = 'Elle açılan kapılı asansörlerin belirlenmiş durakta hizmet dışı bırakılıp kapıların açıldığını ve sesli/görsel tahliye uyarısının verildiğini test edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0920';
update public.madde_kutuphanesi set resmi_madde_metni = 'Otomatik yangın algılama sistemi sıfırlandığında bu sistemden gelen elektrik sinyali ile veya yalnızca yetkili kişilerce sıfırlanabilecek şekilde tasarımlanmış elle çağırma sisteminin sıfırlanması ile asansör otomatik olarak normal çalışacak hâle gelmelidir.', kontrol_basligi = 'Yangın sinyali sıfırlanınca otomatik normal çalışmaya dönüş', denetci_yonlendirmesi = 'Yangın algılama sistemi veya yetkili elle sıfırlama sonrası asansörün otomatik olarak normal çalışmaya döndüğünü test edin.', kaynak_form_kodu = 'ÜB.FR.42', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0921';

-- Gerçek checklist maddesi olmayan iki satır: bölüm başlığı (MAD-0901) ve yöntem
-- kodları dipnotu (MAD-0922). MAD-1010 emsaliyle aynı gerekçeyle pasifleştiriliyor;
-- tarihsel snapshot korunur, satır silinmez.
update public.madde_kutuphanesi set aktif = false where madde_id in ('MAD-0901','MAD-0922');

-- Cihazlar kütüphane değişikliğini kesin algılasın
update public.kutuphane_bolum_surumleri set surum = 4, updated_at = now() where bolum = '09 - TS EN 81-73 Yangın Davranışı' and surum < 4;

commit;

-- Salt okunur doğrulama
select madde_id, kontrol_basligi, standart_madde_no, aktif,
  (resmi_madde_metni is not null) as resmi_metin_var,
  (denetci_yonlendirmesi is not null) as rehber_var
from public.madde_kutuphanesi
where madde_id in ('MAD-0893','MAD-0894','MAD-0895','MAD-0896','MAD-0897','MAD-0898','MAD-0899','MAD-0900','MAD-0902','MAD-0903','MAD-0904','MAD-0905','MAD-0906','MAD-0907','MAD-0909','MAD-0910','MAD-0911','MAD-0912','MAD-0913','MAD-0914','MAD-0915','MAD-0916','MAD-0917','MAD-0918','MAD-0919','MAD-0920','MAD-0921', 'MAD-0901','MAD-0922')
order by sira_no;