begin;

do $$
declare dolu_sayisi int;
begin
  select count(*) into dolu_sayisi from public.madde_kutuphanesi
  where madde_id in ('MAD-0845','MAD-0846','MAD-0847','MAD-0848','MAD-0850','MAD-0851','MAD-0853','MAD-0854','MAD-0855','MAD-0856','MAD-0857','MAD-0858','MAD-0859','MAD-0860','MAD-0861','MAD-0862','MAD-0863','MAD-0864','MAD-0865','MAD-0866','MAD-0867','MAD-0868','MAD-0869','MAD-0870','MAD-0871','MAD-0872','MAD-0873','MAD-0874','MAD-0875','MAD-0876','MAD-0877','MAD-0878','MAD-0879','MAD-0880','MAD-0881','MAD-0882','MAD-0884','MAD-0885','MAD-0886') and resmi_madde_metni is not null;
  if dolu_sayisi <> 0 then
    raise exception 'Beklenmeyen durum: % satirda resmi_madde_metni zaten dolu (fail-fast)', dolu_sayisi;
  end if;
end $$;

update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu mahfazaları delikli (perfore) olmamalıdır. Duvarlar, zemin ve tavan, 100 cm2 dairesel veya kare kesitli bir alana düzgün dağıtılmış 2500 N’luk kuvvet, her bir yüz üzerinde herhangi bir noktaya yüzeye dik açıyla uygulandığında; a) kalıcı şekil bozukluğu, b) 15 mm’den daha büyük elâstik şekil bozukluğu meydana gelmeden karşı koyabilecek mekanik mukavemette çelik, tuğla, beton ve benzer malzemeden imal edilmiş olmalıdır.', kontrol_basligi = 'Kuyu mahfazası darbe dayanımı', denetci_yonlendirmesi = 'Kuyu mahfazası duvar/zemin/tavanının 100 cm² alana uygulanan 2500 N''luk kuvvete kalıcı deformasyon veya 15 mm''den büyük esnek deformasyon olmadan dayandığını (test raporu/hesap ile) doğrulayın.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0845';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu mahfazası yapımında kullanılan malzeme, yanmaz, örneğin EN 13501-1 Sınıf A1’e uygun, olmalıdır.', kontrol_basligi = 'Kuyu mahfazası yanmazlık sınıfı', denetci_yonlendirmesi = 'Kuyu mahfazası malzemesinin yanmaz sınıfta (EN 13501-1 Sınıf A1 veya dengi) olduğunu belgeden doğrulayın.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0846';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyusu kısmi mahfazalı olan Kategori 1 asansörler için EN 81-20, Madde 5.2.5.2.3 b)’ye uygun mahfaza yüksekliği en az 5,0 m olmalıdır.', kontrol_basligi = 'Kategori 1 kısmi mahfaza yüksekliği', denetci_yonlendirmesi = 'Kategori 1 kısmi mahfazalı kuyularda mahfaza yüksekliğinin en az 5,0 m olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0847';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kategori 2 asansörlerin kuyusu tam mahfazalı olmalıdır.', kontrol_basligi = 'Kategori 2 tam mahfaza şartı', denetci_yonlendirmesi = 'Kategori 2 asansörlerde kuyunun tam mahfazalı olduğunu gözle kontrol edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0848';
update public.madde_kutuphanesi set resmi_madde_metni = 'Erişim ve acil durum kapıları, erişim kapakları ve muayene kapıları Çizelge E.1’de listelenen nesnelerden herhangi biriyle açılması mümkün olmayacak şekilde yapılmalıdır. Kapılar, kapaklar ve kilitleri, kilitli konumdayken panele 2500 N’luk bir kuvvet, maruz kalan yüzün herhangi bir noktasına dik açıyla, 100 cm2lik dairesel veya kare kesitli bir alana eşit dağılacak şekilde uygulandığında: a) kalıcı deformasyon olmaksızın kuvvete dayanmalı; b) 15 mm’den daha büyük elastik deformasyona uğramamalı; c) böyle bir deney sırasında ve sonrasında güvenlik işlevi etkilenmemeli; d) deney sonrasında çalışabilir durumda olmalıdır.', kontrol_basligi = 'Erişim/acil durum kapı ve kapakların darbe dayanımı', denetci_yonlendirmesi = 'Erişim/acil durum kapıları, kapaklar ve muayene kapaklarının 2500 N''luk kuvvete kalıcı deformasyon olmadan dayandığını ve kilitli konumda güvenlik işlevinin bozulmadığını doğrulayın.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0850';
update public.madde_kutuphanesi set resmi_madde_metni = 'Havalandırma açıklıkları, insanların dışarıdan erişimine açıksa, her bir açıklık: a) 250 mm × 250 mm’den daha büyük olmamalı; b) herhangi bir en kesite sahip düz bir çubuğun, açıklığın içinden geçememesini sağlayacak bir koruma yöntemiyle donatılmalıdır.', kontrol_basligi = 'Havalandırma açıklığı boyut ve koruma şartı', denetci_yonlendirmesi = 'Dışarıdan erişilebilir havalandırma açıklıklarının 250×250 mm''yi aşmadığını ve çubuk sokulmasını önleyen bir koruma yöntemiyle donatıldığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04', standart_madde_no = '5.2.3. | ZA: 1.5.2 2.1' where madde_id = 'MAD-0851';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyunun dışında kalan makina alanlarının, makara dairelerinin ve makina kabinlerinin yapılışında kullanılan malzemeler: Duvarlar, zemin ve tavan, 100 cm2 dairesel veya kare kesitli bir alana düzgün dağıtılmış 2500 N’luk kuvvet, her bir yüz üzerinde herhangi bir noktaya yüzeye dik açıyla uygulandığında; a) kalıcı şekil bozukluğu, b) 15 mm’den daha büyük elâstik şekil bozukluğu meydana gelmeden karşı koyabilecek mekanik mukavemette çelik, tuğla, beton ve benzer malzemeden imal edilmiş olmalıdır.', kontrol_basligi = 'Makina/makara alanı duvar ve tavan darbe dayanımı', denetci_yonlendirmesi = 'Kuyu dışındaki makina/makara alanı duvar, zemin ve tavanının 2500 N''luk kuvvete kalıcı deformasyon olmadan dayandığını doğrulayın.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0853';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu mahfazaları cam malzemeden yapılmış ise lamine cam panele/panellere sahip olmalıdır. (Pencere kullanımı tavsiye edilmez.)', kontrol_basligi = 'Kuyu mahfazası cam panel şartı', denetci_yonlendirmesi = 'Cam malzemeden yapılmış kuyu mahfazalarının lamine cam panel olduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0854';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kategori 2 asansörlerde aşağıdaki kapılardan herhangi biri açılırsa izinsiz giriş alarm sistemi devreye girmelidir: a) makina ve/veya makara dairesi kapısı; b) muayene kapıları, acil durum kapıları ve muayene kapakları; c) makina/makara kabini kapıları.', kontrol_basligi = 'Kategori 2 izinsiz giriş alarm tetikleyicileri', denetci_yonlendirmesi = 'Kategori 2 asansörlerde makina/makara dairesi kapısı, muayene/acil durum kapıları veya makina kabini kapılarından biri açıldığında izinsiz giriş alarmının devreye girdiğini test edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0855';
update public.madde_kutuphanesi set resmi_madde_metni = 'İzinsiz giriş alarm sistemi, yukarıda bahsedilen kapı veya kapaklardan herhangi birinin açılmasından itibaren 30 s içinde sesli bir alarm devreye sokmalıdır.', kontrol_basligi = 'İzinsiz giriş alarmının devreye girme süresi', denetci_yonlendirmesi = 'İzinsiz giriş alarmının, ilgili kapı açıldıktan sonra en fazla 30 saniye içinde devreye girdiğini ölçün.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0856';
update public.madde_kutuphanesi set resmi_madde_metni = 'Sesli alarm; a) 70 dB(A) ile 85 dB(A) arasında ayarlanabilir bir ses seviyesine sahip olmalı ve izinsiz girişin yapıldığı noktada da, ana giriş katında da duyulabilir olmalıdır; b) 5 dakika ile 15 dakika arasında ayarlanabilir bir süre sonunda otomatik olarak durmalıdır.', kontrol_basligi = 'İzinsiz giriş alarmının ses seviyesi ve süresi', denetci_yonlendirmesi = 'Sesli alarmın 70-85 dB(A) arasında ayarlanabilir olduğunu, hem izinsiz giriş noktasında hem ana giriş katında duyulduğunu ve 5-15 dakika sonra otomatik durduğunu test edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0857';
update public.madde_kutuphanesi set resmi_madde_metni = 'Elektrik beslemesinin kesilmesi durumunda alarm sistemi en az 2 saat daha çalışır durumda kalmalıdır.', kontrol_basligi = 'İzinsiz giriş alarmının yedek güçle çalışma süresi', denetci_yonlendirmesi = 'Elektrik kesildiğinde alarm sisteminin en az 2 saat daha çalıştığını doğrulayın.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0858';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kategori 2 asansörlerde, asansör çukurunda bulunan makinalar (ör. makina, tank, kontrolör) metalik bir mahfazayla kapatılmalıdır. Bu mahfaza, çöplerin donanıma girmesini ve tehlikeli işlev bozukluklarına veya malzeme tutuşmasına veya duman çıkmasına sebep olmasını engellemek amacıyla teşkil edilir.', kontrol_basligi = 'Kategori 2 çukur donanımının metalik mahfazası', denetci_yonlendirmesi = 'Kategori 2 asansörlerde çukurdaki makina/tank/kontrolörün metalik bir mahfazayla kapatıldığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0859';
update public.madde_kutuphanesi set resmi_madde_metni = 'Durak ve kabin kapıları; yatay eksende kayan, güçle çalıştırılan otomatik tipte olmalıdır.', kontrol_basligi = 'Durak ve kabin kapılarının otomatik yatay kayar tipte olması', denetci_yonlendirmesi = 'Durak ve kabin kapılarının yatay eksende kayan, güçle çalıştırılan otomatik tipte olduğunu gözle doğrulayın.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0860';
update public.madde_kutuphanesi set resmi_madde_metni = 'Durak ve kabin kapısı için kullanılan malzemeler aşağıdakilere uygun olmalıdır: a) Dekoratif amaçlı son yüzey işlemleri hariç, kapı panellerinde, çerçevelerinde/pervazlarında kullanılan malzemeler yanmaz, örneğin EN 13501-1 Sınıf A1’e uygun, olmalıdır. b) Dekoratif son yüzey işlemleri için kullanılan malzemeler; 1) Kategori 1 asansörler için sınırlı ölçüde alevlenebilir, örneğin EN 13501-1 Sınıf C’ye uygun, 2) Kategori 2 asansörler için yanmaz, örneğin EN 13501-1 Sınıf A2’ye uygun olmalıdır.', kontrol_basligi = 'Durak ve kabin kapı malzemelerinin yanmazlık sınıfı', denetci_yonlendirmesi = 'Kapı panelleri/çerçevelerinin yanmaz malzemeden, dekoratif yüzeylerin kategoriye göre uygun yanmazlık sınıfından (Kategori 1: sınırlı alevlenebilir, Kategori 2: yanmaz) olduğunu belgeden kontrol edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0861';
update public.madde_kutuphanesi set resmi_madde_metni = 'Malzemelerinden bağımsız olarak durak ve kabin kapı takımları, çerçeveleri ve bağlantı parçalarıyla birlikte EN 81-20, Madde 5.3.5.3.4 a)’da belirtilen yumuşak sarkaç darbe deneyine, bileşenlerde arıza olmaksızın veya kapıların düzgün işlemesini bozacak kalıcı deformasyon yaşanmaksızın dayanmalıdır. Deneyden sonra kapı takımları çalışır durumda kalmalıdır. Deneyler için cisim düşme yükseklikleri şu şekilde alınmalıdır: a) Kategori 1 asansörler için: 700 mm; b) Kategori 2 asansörler için: 1 000 mm.', kontrol_basligi = 'Kapı takımlarının sarkaç darbe deneyine dayanımı', denetci_yonlendirmesi = 'Kapı takımlarının yumuşak sarkaç darbe deneyine (Kategori 1: 700 mm, Kategori 2: 1000 mm düşme yüksekliği) arızasız/deformasyonsuz dayandığını ve deney sonrası çalışır kaldığını test edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0862';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kategori 2 asansörlerde cam panel kullanılmamalıdır.', kontrol_basligi = 'Kategori 2 cam panel yasağı', denetci_yonlendirmesi = 'Kategori 2 asansörlerde kapılarda cam panel kullanılmadığını gözle kontrol edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0863';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kategori 2 asansörler için her bir durak kapısı veya kapıların ön kenarlarındaki ekler ile kabin kapısı/kapıları veya kapıların ön kenarlarındaki ekler arasındaki mesafe 35 mm’yi aşmamalıdır. Bu mesafe, ön kenardan itibaren en az 75 mm’lik bir uzunluk boyunca muhafaza edilmeli ve en fazla 45°lik bir açıyla kapı panelinin arkasına doğru dönmelidir.', kontrol_basligi = 'Durak-kabin kapı ön kenar aralığı', denetci_yonlendirmesi = 'Kategori 2''de durak ve kabin kapı ön kenarları arasındaki mesafenin 35 mm''yi aşmadığını, gerekli uzunluk ve açı şartlarını sağladığını ölçün.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0864';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kategori 2 asansörlerde, girişin kattaki asansör girişi tarafından kuyunun içine doğru 10 mm çapında bir çubuğun sokulması mümkün olmamalıdır.', kontrol_basligi = 'Kategori 2 kapı-kuyu arası çubuk sokma testi', denetci_yonlendirmesi = 'Kategori 2''de asansör girişinden kuyu içine 10 mm çapında çubuk sokulamadığını test edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0865';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kategori 2 asansörlerde kabinin ve durak kapılarının ön kenar profili, kapının entegre bir parçası olarak biçimlendirilmelidir.', kontrol_basligi = 'Kategori 2 kapı ön kenar profili', denetci_yonlendirmesi = 'Kategori 2''de kabin/durak kapısı ön kenar profilinin kapının entegre parçası olarak biçimlendirildiğini gözle kontrol edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0866';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabinin mevcut olmadığı bulunmadığı herhangi bir katta, EN 81-20, Madde 5.3.9.3.1’de belirtilen acil durum açma anahtarı ile veya Ek E’de belirtilen nesneler kullanılarak açılmasını, devre dışı bırakılmadıkça, durak kapılarının açılmasını engelleyen bir emniyet sistemi bulunmalıdır.', kontrol_basligi = 'Kabin yokken durak kapısı açılmasını önleyen emniyet sistemi', denetci_yonlendirmesi = 'Kabin bulunmayan katta, acil durum açma anahtarı veya izinli araç dışında durak kapısının açılmasını engelleyen emniyet sisteminin varlığını doğrulayın.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0867';
update public.madde_kutuphanesi set resmi_madde_metni = 'Bu sistemin elle devreye alınması ve devreden çıkarılmasını sağlayacak bir tertibat aşağıdaki yerlerden en az birinde mevcut bulunmalıdır: a) makina dairesi; b) kontrol kabini; c) acil durum ve muayene paneli. Tertibat, Ek C''de gösterilen piktogramlarla açık şekilde işaretlenmelidir. Bu piktogram ayrıca binanın ana giriş/çıkış katındaki asansör girişinin üzerine veya yanına yerleştirilmelidir.', kontrol_basligi = 'Emniyet sisteminin elle devreye alma/çıkarma tertibatı', denetci_yonlendirmesi = 'Emniyet sistemini elle devreye alma/çıkarma tertibatının (makina dairesi/kontrol kabini/acil durum panelinde) mevcut ve piktogramla işaretli olduğunu, ayrıca ana giriş katında işaretlendiğini kontrol edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0868';
update public.madde_kutuphanesi set resmi_madde_metni = 'Ana güç kaynağının arızalanması durumunda, sistem bir yedek güç kaynağıyla en az iki saat boyunca çalışır durumda kalmalıdır. Ana anahtar bağlantısının kesilmesi durumunda sistem derhal devre dışı kalmalıdır.', kontrol_basligi = 'Emniyet sisteminin yedek güçle çalışma süresi', denetci_yonlendirmesi = 'Ana güç kesildiğinde sistemin yedek güçle en az 2 saat çalıştığını, ana anahtar kesildiğinde derhal devre dışı kaldığını test edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0869';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin kapıları her durumda bir mekanik kilitleme tertibatı ile donatılmalıdır.', kontrol_basligi = 'Kabin kapılarının mekanik kilitleme tertibatı', denetci_yonlendirmesi = 'Kabin kapılarının her durumda mekanik bir kilitleme tertibatına sahip olduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0870';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin duvarlarının mekanik dayanımı; Madde 5.4.1.2 a veya b '' de durak kapıları için belirtilenlerden uygun olanına en azından eşit olmalıdır.', kontrol_basligi = 'Kabin duvarlarının mekanik dayanımı', denetci_yonlendirmesi = 'Kabin duvarlarının mekanik dayanımının, durak kapıları için tanımlanan (Kategori 1/2) dayanım şartına en az eşit olduğunu doğrulayın.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0871';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kategori 1 asansörler için kabin tavanları: a) insanların asılarak tutunabileceği herhangi bir noktadan uygulanacak 150 kg’lık bir kütleyi taşıyabilmeli; b) elle veya Ek E’de açıklanan bir nesne kullanılarak, 60 saniye süre içerisinde yetkisiz kişiler tarafından yerinin değiştirilmesini önleyecek şekilde sabitlenmelidir.', kontrol_basligi = 'Kategori 1 kabin tavanının yük taşıma ve sabitleme şartı', denetci_yonlendirmesi = 'Kategori 1 kabin tavanının 150 kg''lık asılı yükü taşıdığını ve yetkisiz kişilerce 60 saniyede yerinden oynatılamayacak şekilde sabitlendiğini test edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0872';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kategori 2 asansörlerde tavan, insanların hiçbir noktadan asılarak tutunamayacağı şekilde tasarlanmalıdır.', kontrol_basligi = 'Kategori 2 kabin tavanının tutunmayı önleyen tasarımı', denetci_yonlendirmesi = 'Kategori 2 kabin tavanının hiçbir noktadan asılıp tutunulamayacak şekilde tasarlandığını gözle kontrol edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0873';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin gövdesi için kullanılan malzemeler yanmaz olmalıdır.', kontrol_basligi = 'Kabin gövde malzemesinin yanmazlığı', denetci_yonlendirmesi = 'Kabin gövde malzemesinin yanmaz olduğunu belgeden doğrulayın.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0874';
update public.madde_kutuphanesi set resmi_madde_metni = 'Tüm kabin döşeme malzemeleri, kesildiklerinde tökezlenme/takılma tehlikesi oluşması önlenecek şekilde sabitlenmelidir.', kontrol_basligi = 'Kabin döşeme malzemesinin takılma tehlikesine karşı sabitlenmesi', denetci_yonlendirmesi = 'Kabin döşeme malzemesinin kesildiğinde takılma tehlikesi oluşturmayacak şekilde sabitlendiğini kontrol edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0875';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kategori 2 asansörlerindeki tüm tırabzanlar, en olumsuz noktada, herhangi bir yönde uygulanan 2 500 N''luk bir kuvveti taşıyabilmelidir.', kontrol_basligi = 'Kategori 2 tırabzanların kuvvet dayanımı', denetci_yonlendirmesi = 'Kategori 2 tırabzanların en olumsuz noktada 2500 N''luk kuvvete dayandığını doğrulayın.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0876';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kategori 2 asansörlerinde ayna bulunduğu durumlarda, aynalar: a) çıkıntı yapmayacak (gömme olacak) şekilde takılmış olmalı, b) camdan imal edilmiş ise lamine olmalıdır.', kontrol_basligi = 'Kategori 2 kabin aynasının montaj ve cam şartı', denetci_yonlendirmesi = 'Kategori 2 kabin aynasının gömme monte edildiğini ve cam ise lamine olduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0877';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kategori 1 asansörler için, kabin donatıları ve bağlantıları yerlerinden yalnızca özel aletler kullanılarak çıkarılabilecek yapıda olmalıdır.', kontrol_basligi = 'Kategori 1 kabin donatılarının özel aletle sökülebilmesi', denetci_yonlendirmesi = 'Kategori 1 kabin donatılarının yalnızca özel aletle sökülebildiğini test edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0878';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kategori 2 asansörler için, kabin donatıları ve bağlantıları yerlerine kullanıcılar tarafından görülemeyecek bağlantılar ile tespit edilmelidir.', kontrol_basligi = 'Kategori 2 kabin donatı bağlantılarının gizliliği', denetci_yonlendirmesi = 'Kategori 2 kabin donatı bağlantılarının kullanıcı tarafından görülemeyecek şekilde tespit edildiğini kontrol edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0879';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kategori 1 ve Kategori 2 asansörler için; kabinler, zemin seviyesinde ve kumanda tertibatlarında en az 100 lüks şiddetinde bir ışık yoğunluğu sağlayacak sabit bir aydınlatma tesisatı ile teçhiz edilmelidir.', kontrol_basligi = 'Kabin aydınlatma şiddeti', denetci_yonlendirmesi = 'Kabin zemin seviyesi ve kumanda tertibatında en az 100 lüks aydınlatma şiddeti olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0880';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kategori 2 asansörler için; herhangi bir el tutamağı, en tercih edilmeyen noktasına herhangi bir yönden uygulanan 2500 N’luk noktasal kuvvete mukavemet göstermelidir.', kontrol_basligi = 'Kategori 2 el tutamağının kuvvet dayanımı', denetci_yonlendirmesi = 'Kategori 2''de el tutamağının en olumsuz noktada herhangi yönden 2500 N''luk kuvvete dayandığını doğrulayın.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0881';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin katta kapıları açıkta durumda değilse, alarm düğmesinin çalıştırılması bir tertibatın 60 s boyunca veya kabin kapıları açılıncaya kadar ses çıkarmasına sebep olmalı ve bu sesin seviyesi 70 dB(A) ile 85 dB(A) arasında ayarlanabilecek şekilde kabin içerisinden, duyulabilmelidir.', kontrol_basligi = 'Alarm düğmesinin ses süresi ve seviyesi', denetci_yonlendirmesi = 'Kabin katta kapıları açık değilken alarm düğmesine basıldığında, kapılar açılana kadar veya en az 60 saniye 70-85 dB(A) arası duyulabilir bir sesin çıktığını test edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04', standart_madde_no = '5.7.' where madde_id = 'MAD-0882';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kamuya açık işaret ve işaretlemeler; Ek E’de belirtilen araçlarla yerlerinden çıkarılamayacak şekilde tespit edilmeli,', kontrol_basligi = 'Kamuya açık işaretlerin sökülmeye karşı sabitlenmesi', denetci_yonlendirmesi = 'Kamuya açık işaret ve işaretlemelerin belirtilen araçlarla yerinden çıkarılamadığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0884';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kamuya açık işaret ve işaretlemeler; Ek E’de listelenen araçlardan biri kullanılarak 60 saniye içerisinde okunamaz hâle getirilememeli,', kontrol_basligi = 'Kamuya açık işaretlerin okunaksızlaştırmaya karşı dayanımı', denetci_yonlendirmesi = 'Kamuya açık işaretlerin 60 saniye içinde okunamaz hale getirilemediğini test edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0885';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kumanda tablası yüz plâkası veya butonlar üzerindeki sembol ve işaretlemeler ile aktarılan herhangi bir bilgi 60 saniye içerisinde Ek E’de listelenen araçlarla tahrip edildiğinde okunur hâlde kalmalıdır.', kontrol_basligi = 'Kumanda paneli sembollerinin tahribata karşı okunabilirliği', denetci_yonlendirmesi = 'Kumanda paneli sembol/işaretlerinin 60 saniyelik tahribat denemesinden sonra okunur kaldığını test edin.', kaynak_form_kodu = 'ÜB.FR.41', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0886';

-- Gerçek checklist maddesi olmayan satırlar: alt bölüm başlıkları (5.2.2, 5.3, 5.9),
-- belirsiz/eylemsiz genel ifade ("TS EN 81-71 standardına göre ek düzenlemeler yapılmalıdır")
-- ve yöntem kodları dipnotu. MAD-1010 emsaliyle pasifleştirildi.
update public.madde_kutuphanesi set aktif = false where madde_id in ('MAD-0849','MAD-0852','MAD-0883','MAD-0887','MAD-0888');

update public.kutuphane_bolum_surumleri set surum = surum + 1, updated_at = now() where bolum = '08 - TS EN 81-71 Tahribata Dayanıklı';

commit;

select madde_id, kontrol_basligi, aktif, (resmi_madde_metni is not null) as resmi_var from public.madde_kutuphanesi where madde_id in ('MAD-0845','MAD-0846','MAD-0847','MAD-0848','MAD-0850','MAD-0851','MAD-0853','MAD-0854','MAD-0855','MAD-0856','MAD-0857','MAD-0858','MAD-0859','MAD-0860','MAD-0861','MAD-0862','MAD-0863','MAD-0864','MAD-0865','MAD-0866','MAD-0867','MAD-0868','MAD-0869','MAD-0870','MAD-0871','MAD-0872','MAD-0873','MAD-0874','MAD-0875','MAD-0876','MAD-0877','MAD-0878','MAD-0879','MAD-0880','MAD-0881','MAD-0882','MAD-0884','MAD-0885','MAD-0886', 'MAD-0849','MAD-0852','MAD-0883','MAD-0887','MAD-0888') order by sira_no;