begin;

do $$
declare dolu_sayisi int;
begin
  select count(*) into dolu_sayisi from public.madde_kutuphanesi
  where madde_id in ('MAD-0713','MAD-0714','MAD-0715','MAD-0716','MAD-0717','MAD-0718','MAD-0719','MAD-0720','MAD-0721','MAD-0722','MAD-0723','MAD-0724','MAD-0725','MAD-0726','MAD-0727','MAD-0728','MAD-0729','MAD-0730','MAD-0731','MAD-0732','MAD-0733','MAD-0734','MAD-0735','MAD-0737','MAD-0738','MAD-0739','MAD-0740','MAD-0741','MAD-0742','MAD-0743','MAD-0744','MAD-0745','MAD-0746','MAD-0748','MAD-0749','MAD-0750','MAD-0751','MAD-0752','MAD-0753','MAD-0754') and resmi_madde_metni is not null;
  if dolu_sayisi <> 0 then
    raise exception 'Beklenmeyen durum: % satirda resmi_madde_metni zaten dolu (fail-fast)', dolu_sayisi;
  end if;
end $$;

update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyuda yer alan itfaiyeci asansörünün, yangın söndürme çalışmaları için kullanılan her durak kapısının önünde güvenli alanı bulunmalıdır. Her durak kapısının önünde bulunan güvenli alanında, yangına dayanıklı kepenk veya yangın kapısı bulunmalıdır.', kontrol_basligi = 'İtfaiyeci asansörü durak kapısı önünde güvenli alan ve yangın kapısı', denetci_yonlendirmesi = 'Kuyuda yer alan itfaiyeci asansörünün her durak kapısı önünde güvenli alan ve yangına dayanıklı kepenk/yangın kapısı bulunduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0713';
update public.madde_kutuphanesi set resmi_madde_metni = 'Acil durum asansörleri önünde, aynı zamanda kaçış merdivenine de geçiş sağlayacak şekilde, her katta 6 m2’den az, 10 m2’den çok ve herhangi bir boyutu 2 m’den az olmayacak yangın güvenlik holü olmalıdır.', kontrol_basligi = 'Yangın güvenlik holü boyutları', denetci_yonlendirmesi = 'Yangın güvenlik holünün her katta 6-10 m² arasında ve hiçbir boyutu 2 m altında olmadığını ölçün.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0714';
update public.madde_kutuphanesi set resmi_madde_metni = 'Aynı kuyu içinde 3’den fazla asansör kabini düzenlenemez. 4 asansör kabini düzenlendiği takdirde, ikişerli gruplar halinde araları yangına 60 dakika dayanıklı bir malzeme ile ayrılır.', kontrol_basligi = 'Aynı kuyuda azami kabin sayısı ve ayırma', denetci_yonlendirmesi = 'Aynı kuyuda 3''ten fazla kabin olmadığını; 4 kabin varsa ikişerli gruplar arasında 60 dakika yangına dayanıklı ayırma olduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0715';
update public.madde_kutuphanesi set resmi_madde_metni = 'Aynı kuyuda başka asansörler de varsa, ortak kuyunun tamamı, itfaiyeci asansörü kuyularının yangına dayanıklılık gerekliliklerini karşılamalıdır.Yangın sinyali sıfırlanana kadar, diğer çağırma araçlarından gelen sinyaller yok sayılmalıdır.(durak çağrıları)', kontrol_basligi = 'Ortak kuyunun yangına dayanıklılık gerekliliği', denetci_yonlendirmesi = 'Ortak kuyudaki diğer asansörlerin de itfaiyeci asansörü kuyusunun yangına dayanıklılık gerekliliklerini karşıladığını ve yangın sinyali sıfırlanana kadar diğer çağrıların yok sayıldığını doğrulayın.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0716';
update public.madde_kutuphanesi set resmi_madde_metni = 'Aynı kuyuda başka asansörler de varsa diğer asansörlerin çalışır durumda kalması gerekli değildir, ancak başka asansörün kusurlu çalışmasının, itfaiyeci asansörünün işlevini olumsuz etkilememesi sağlanmalıdır.', kontrol_basligi = 'Diğer asansörlerin arızasının itfaiyeci asansörünü etkilememesi', denetci_yonlendirmesi = 'Ortak kuyudaki diğer asansörün arızasının itfaiyeci asansörünün işlevini olumsuz etkilemediğini test edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0717';
update public.madde_kutuphanesi set resmi_madde_metni = 'İtfaiyeci asansörü, ikincil bir güç beslemesine sahip olmalıdır.', kontrol_basligi = 'İkincil güç beslemesi şartı', denetci_yonlendirmesi = 'İtfaiyeci asansörünün ikincil bir güç beslemesine sahip olduğunu doğrulayın.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0718';
update public.madde_kutuphanesi set resmi_madde_metni = 'İtfaiyeci asansörünün elektrik güç besleme kablosu/kabloları yangına karşı korunaklı olmalıdır. (en az 60 dakika dayanıklı olması)', kontrol_basligi = 'Güç besleme kablosunun yangına dayanıklılığı', denetci_yonlendirmesi = 'Güç besleme kablolarının en az 60 dakika yangına dayanıklı korumaya sahip olduğunu belgeden doğrulayın.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0719';
update public.madde_kutuphanesi set resmi_madde_metni = 'İkincil güç beslemesi ve otomatik anahtarlama düzeninin kaynağı, yangın korumalı bir alanda yer almalıdır.', kontrol_basligi = 'İkincil güç kaynağının yangın korumalı alanda olması', denetci_yonlendirmesi = 'İkincil güç beslemesi ve otomatik anahtarlama kaynağının yangın korumalı bir alanda yer aldığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0720';
update public.madde_kutuphanesi set resmi_madde_metni = 'İkincil güç beslemesi, itfaiyeci asansörünü beyan yükünde ve beyan hızında, yangına dayanıklılık süresine denk süre boyunca çalıştırılabilmelidir. Kabin ve kuyu aydınlatması için güç, ikincil güç beslemesi tarafından sağlanmalıdır. (enerji kesilmesi hâlinde, otomatik olarak devreye girecek özellikte ve 60 dakika çalışır durumda kalmasını sağlayacak bir acil durum jenaratörüne bağlı bulunması gerekir.)', kontrol_basligi = 'İkincil güç beslemesinin çalışma süresi ve kapsamı', denetci_yonlendirmesi = 'İkincil güç beslemesinin beyan yükü/hızında yangına dayanıklılık süresi boyunca çalıştığını, kabin/kuyu aydınlatmasını da beslediğini ve otomatik devreye giren jeneratöre bağlı olduğunu doğrulayın.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0721';
update public.madde_kutuphanesi set resmi_madde_metni = 'Acil durum asansörünün makina dairesi ayrı olmalı ve asansör kuyusu basınçlandırılmalıdır.', kontrol_basligi = 'Makina dairesinin ayrı olması ve kuyu basınçlandırması', denetci_yonlendirmesi = 'Acil durum asansörünün makina dairesinin ayrı olduğunu ve asansör kuyusunun basınçlandırıldığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0722';
update public.madde_kutuphanesi set resmi_madde_metni = 'Basınçlandırma sistemindeki ses basınç seviyesi, asansör aşama 2 deyken kabindeki mikrofonlardan 0,5 m mesafedeki konumlarda, itfaiye hizmeti erişim seviyesinde, acil durum ve test panosunda 80 dB(A)’dan daha az olmalıdır. (gürültünün seviyesinin yüksek olması durumda itfaiyeci acil iletişime geçemeyebilir.)', kontrol_basligi = 'Basınçlandırma sisteminin ses seviyesi', denetci_yonlendirmesi = 'Basınçlandırma sistemi sesinin, kabindeki mikrofonlardan 0,5 m mesafede ve acil durum/test panosunda 80 dB(A)''yı aşmadığını ölçün.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0723';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu basınçlandırması, kabin ve durak kapılarının açılma ve kapanmasını etkilememelidir.', kontrol_basligi = 'Basınçlandırmanın kapı hareketini etkilememesi', denetci_yonlendirmesi = 'Kuyu basınçlandırmasının kabin ve durak kapılarının açılıp kapanmasını etkilemediğini test edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0724';
update public.madde_kutuphanesi set resmi_madde_metni = 'İtfaiyeci asansörlerinin, bina tasarımı ile tanımlandığı ve Ulusal düzenlemelerin gerektirdiği şekilde tüm katlara hizmet vermesi tavsiye edilir. Ancak hizmet verilecek katların, yangında bina tasarımının bir parçası olarak tayin edildiği varsayılır.', kontrol_basligi = 'İtfaiyeci asansörünün hizmet verdiği katlar', denetci_yonlendirmesi = 'İtfaiyeci asansörünün, bina tasarımında ve ulusal düzenlemelerde belirlenen katlara hizmet verdiğini kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0725';
update public.madde_kutuphanesi set resmi_madde_metni = 'İtfaiyeci asansörlerinin, acil durum asansörünün kabin alanının en az 1.8 m² olmalıdır. (binaların yangından korunması hakkında yönetmelik-md-63/4)', kontrol_basligi = 'Acil durum asansörü kabin alanı', denetci_yonlendirmesi = 'Acil durum asansörü kabin alanının en az 1,8 m² olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0726';
update public.madde_kutuphanesi set resmi_madde_metni = 'İtfaiyeci asansörünün kullanım amaçları arasında, tahliye ve sedye veya yatak gibi ögeleri taşımanın da olduğu durumlarda, en küçük beyan yükü 1000 kg olmalı ve kabinin en küçük boyutları 1100 mm (en) x 2100 mm (derinlik) olmalıdır.', kontrol_basligi = 'Tahliye/sedye taşıma için beyan yükü ve kabin boyutu', denetci_yonlendirmesi = 'Tahliye/sedye taşıma amaçlı kullanımda beyan yükünün en az 1000 kg, kabin boyutunun en az 1100x2100 mm olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0727';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabinle giriş açıklığının genişliği en az 800 mm olmalıdır.', kontrol_basligi = 'Kabin giriş açıklığı genişliği', denetci_yonlendirmesi = 'Kabin giriş açıklığı genişliğinin en az 800 mm olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0728';
update public.madde_kutuphanesi set resmi_madde_metni = 'İtfaiyeci asansörü, asansör kapılarının kapanmasından sonra 60 s içinde itfaiye hizmeti erişim seviyesinden yangın söndürme çalışması yapılacak en üst durağa ulaşabilmelidir. Ancak, hareket mesafesi 200 m’den fazla olan asansörler için en üst durağa ulaşma süresi, her 3 m’lik ilave hareket yüksekliği için 1 s artırılabilir.', kontrol_basligi = 'İtfaiye hizmeti erişim seviyesinden en üst durağa ulaşma süresi', denetci_yonlendirmesi = 'İtfaiyeci asansörünün, kapı kapanmasından sonra 60 saniye içinde (200 m üzeri hareket mesafesinde her 3 m için +1 s) en üst durağa ulaştığını test edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0729';
update public.madde_kutuphanesi set resmi_madde_metni = 'İtfaiye hizmeti erişim seviyesi haricinde, duraklardaki elektrikli/elektronik aygıtlar 0 °C ila 65 °C ortam sıcaklığı aralığında düzgün çalışacak veya çalışmaz duruma getirilecek şekilde tasarlanmalıdır.', kontrol_basligi = 'İtfaiye hizmeti erişim seviyesi dışı elektronik aygıt sıcaklık aralığı', denetci_yonlendirmesi = 'İtfaiye hizmeti erişim seviyesi dışındaki durak elektronik aygıtlarının 0-65°C aralığında çalıştığını veya bu aralık dışında devre dışı kaldığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0730';
update public.madde_kutuphanesi set resmi_madde_metni = 'itfaiyeci asansörünün duraklardaki elektrikli/elektronik aygıtlar dışındaki tüm elektrikli/elektronik bileşenleri, 0 °C ila +40 °C ortam sıcaklığı aralığında düzgün çalışacak şekilde tasarlanmalıdır;', kontrol_basligi = 'İtfaiyeci asansörü elektronik bileşenlerinin sıcaklık aralığı', denetci_yonlendirmesi = 'İtfaiyeci asansörünün (durak aygıtları hariç) elektronik bileşenlerinin 0-40°C aralığında çalıştığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0731';
update public.madde_kutuphanesi set resmi_madde_metni = 'Ortam sıcaklığı algılayıcıları, itfaiyeci asansörünü durdurmamalı veya yol almasını engellememelidir.', kontrol_basligi = 'Ortam sıcaklığı algılayıcılarının asansörü durdurmaması', denetci_yonlendirmesi = 'Ortam sıcaklığı algılayıcılarının itfaiyeci asansörünü durdurmadığını veya yol almasını engellemediğini test edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0732';
update public.madde_kutuphanesi set resmi_madde_metni = 'Çift girişli kabin için, yangın söndürme çalışmalarının herhangi bir anında birden fazla kabin kapısı açık olmamalıdır.', kontrol_basligi = 'Çift girişli kabinde tek kapı açık kalma şartı', denetci_yonlendirmesi = 'Çift girişli kabinde yangın söndürme çalışması sırasında aynı anda yalnız bir kabin kapısının açık olduğunu test edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0733';
update public.madde_kutuphanesi set resmi_madde_metni = 'Ardışık ana durak kapı eşikleri arasındaki mesafe 7 m’yi aştığında, eşikler arasındaki mesafe 7 m’den fazla olmayacak şekilde acil çıkış kapıları sağlanmalıdır.', kontrol_basligi = 'Ardışık durak kapı eşikleri arası mesafe ve acil çıkış kapısı', denetci_yonlendirmesi = 'Ardışık ana durak kapı eşikleri arası mesafe 7 m''yi aştığında ara acil çıkış kapılarının sağlandığını ölçün.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0734';
update public.madde_kutuphanesi set resmi_madde_metni = 'İtfaiyeci asansörü kuyusu ve makinenin bulunduğu alanlarda yangın söndürme sistemi (yağmurlama sistemi) bulunmamalıdır.**', kontrol_basligi = 'İtfaiyeci asansörü kuyusunda yağmurlama sistemi yasağı', denetci_yonlendirmesi = 'İtfaiyeci asansörü kuyusu ve makina alanında yağmurlama (sprinkler) sisteminin bulunmadığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0735';
update public.madde_kutuphanesi set resmi_madde_metni = 'Durak kapısının bulunduğu duvardan 1,0 metre mesafe içeride itfaiyeci asansörlerinin, asansör kuyusu içerisinde ve kabin üzerinde, en yüksek kat seviyesinin altında ve kabin duvarlarının dış taraflarında yer alan elektrikli donanımı, üst kattan su damlaması ve sıçramalarına karşı EN 60529’a göre en az IPX3 koruma derecesiyle sınıflandırılmış bir mahfaza ile korunmalıdır.**', kontrol_basligi = 'Durak kapısına 1 m mesafedeki donanımın su koruması (IPX3)', denetci_yonlendirmesi = 'Durak kapısına 1 m mesafe içindeki, en yüksek kat altındaki elektrikli donanımın en az IPX3 korumalı olduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0737';
update public.madde_kutuphanesi set resmi_madde_metni = 'Bir durak kapısının bulunduğu bir duvardan 1,0 m’den fazla uzakta ve en yüksek durak seviyesinin altındaki itfaiyeci asansörü dâhilindeki elektrikli donanım, üst bir duraktan su damlamasına karşı EN 60529:1991’e göre en az IPX1 derecesinde sınıflandırılmış bir mahfaza ile korunmalıdır.', kontrol_basligi = 'Durak kapısından 1 m''den uzak donanımın su koruması (IPX1)', denetci_yonlendirmesi = 'Durak kapısından 1 m''den uzak, en yüksek durak altındaki elektrikli donanımın en az IPX1 korumalı olduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0738';
update public.madde_kutuphanesi set resmi_madde_metni = 'Asansör kuyu alt boşluğu zemininden 1,0 m’den daha aşağıda yer alan herhangi bir elektrikli donanım IP67 koruma derecesiyle korunmalıdır.', kontrol_basligi = 'Kuyu alt boşluğunda 1 m altındaki donanımın su koruması (IP67)', denetci_yonlendirmesi = 'Kuyu alt boşluğu zemininden 1 m aşağıdaki elektrikli donanımın IP67 korumalı olduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0739';
update public.madde_kutuphanesi set resmi_madde_metni = 'Priz çıkışı ve kuyunun aydınlatma sisteminin en aşağısındaki lamba, kuyu alt boşluğunda izin verilen en yüksek su seviyesinin en az 0,5 m yukarısında yer almalıdır.', kontrol_basligi = 'Priz ve aydınlatmanın su seviyesine göre konumu', denetci_yonlendirmesi = 'Priz çıkışı ve en alt aydınlatma lambasının, izin verilen en yüksek su seviyesinin en az 0,5 m yukarısında olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0740';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyunun dışında makinenin bulunduğu alanlardaki elektrikli donanım, sudan kaynaklı kusurlu çalışmaya karşı korunmalıdır.', kontrol_basligi = 'Kuyu dışı makina alanı donanımının su koruması', denetci_yonlendirmesi = 'Kuyu dışındaki makina alanı elektrikli donanımının sudan kaynaklı arızaya karşı korunduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0741';
update public.madde_kutuphanesi set resmi_madde_metni = 'Asansör kuyusuna su girişini önlemek için alınacak önlemler aşağıda verilmiştir. Ancak bu verilen önlemlerin alınamadığı durumlarda asansör kuyusundaki izin verilen su seviyesi sağlamak için ekstra önlemler alınmalıdır. a) atık su borularının sağlanması ve her durak girişinin önünde drenaj kanallarının bulunması ve/veya b) güvenli alana giren suyun asansör kuyusuna geçmeden merdivenlerden boşalması ve/veya duman bacasından çıkması ve/veya c) drenaj veya su akıtma boruları yoluyla bina dışına aktarılması amacıyla, her durak girişinin önündeki zeminin yükseltilmesi veya eğimlendirilmesi,', kontrol_basligi = 'Kuyuya su girişini önleyen tedbirler', denetci_yonlendirmesi = 'Kuyuya su girişini önleyecek drenaj kanalı, eğimli zemin veya benzeri tedbirlerin alındığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0742';
update public.madde_kutuphanesi set resmi_madde_metni = 'Asansör kuyusundaki su seviyesinin izin verilen maksimum seviyelerden birine ulaşmasını önlenmesi için; a) kuyuda drenaj sistemi ve/veya b) Suyun asansör kuyusundan çıkarılması için asansör kuyusunun dışında sabit olarak monte edilmiş drenaj pompalarının kullanılmalıdır.', kontrol_basligi = 'Kuyu su seviyesini sınırlayan drenaj sistemi', denetci_yonlendirmesi = 'Kuyudaki su seviyesini sınırlamak için drenaj sistemi veya sabit drenaj pompası bulunduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0743';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu alt boşluğundaki su seviyesi, tam basınçlı kabin tamponu seviyesinin üstüne çıkmamalıdır.', kontrol_basligi = 'Su seviyesinin tampon seviyesini aşmaması', denetci_yonlendirmesi = 'Kuyu alt boşluğundaki su seviyesinin tam basınçlı kabin tamponu seviyesini aşmadığını ölçün.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0744';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu alt boşluğundaki su seviyesi, donanıma ulaşmamalı ve bu yolla itfaiyeci asansörünün kusurlu çalışmasına neden olmamalıdır.', kontrol_basligi = 'Su seviyesinin donanıma ulaşmaması', denetci_yonlendirmesi = 'Kuyu alt boşluğundaki su seviyesinin donanıma ulaşmadığını ve kusurlu çalışmaya yol açmadığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0745';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin tavanı, suyun birikmesini engelleyecek ve tavandan kontrollü tahliyeye olanak sağlayacak şekilde tasarlanmalıdır. Kabin tavanındaki ve dış duvarlardaki elektrikli donanım, EN 60529:1991’e göre en az IPX3 ile sınıflandırılmalıdır.', kontrol_basligi = 'Kabin tavanının su tahliyesi ve donanım koruması', denetci_yonlendirmesi = 'Kabin tavanının su birikmesini önleyip kontrollü tahliyeye izin verdiğini, tavan/dış duvar donanımının en az IPX3 korumalı olduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0746';
update public.madde_kutuphanesi set resmi_madde_metni = 'En küçük net açıklık boyutları 0,5 m x 0,7 m olan kabin tavanına, 630 kg kapasiteli asansör hariç (bu durumda boyutlar en az 0,4 m x 0,5 m’dir), bir imdat geçiş kapısı yerleştirilmelidir.', kontrol_basligi = 'İmdat geçiş kapısı boyutları', denetci_yonlendirmesi = 'İmdat geçiş kapısının en küçük net açıklığının 0,5x0,7 m (630 kg kapasitede 0,4x0,5 m) olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0748';
update public.madde_kutuphanesi set resmi_madde_metni = 'İmdat geçiş kapısı yoluyla kabinin içine erişim, herhangi bir sabit aparat veya aydınlatma ile engellenmemelidir.', kontrol_basligi = 'İmdat geçiş kapısından erişimin engellenmemesi', denetci_yonlendirmesi = 'İmdat geçiş kapısından kabine erişimin sabit aparat veya aydınlatma ile engellenmediğini kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0749';
update public.madde_kutuphanesi set resmi_madde_metni = 'Asma tavan mevcutsa, bu tavan özel bir alet kullanılmadan kolaylıkla açılabilmeli veya yerinden çıkarılabilmelidir.', kontrol_basligi = 'Asma tavanın aletsiz açılabilmesi', denetci_yonlendirmesi = 'Asma tavanın özel alet olmadan kolayca açılıp çıkarılabildiğini test edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0750';
update public.madde_kutuphanesi set resmi_madde_metni = 'İmdat geçiş kapısına ait asma tavanın sırasıyla herhangi bir parçasının taşıma kuvveti 250 N’dan az olmalıdır.', kontrol_basligi = 'Asma tavan parçasının taşıma kuvveti', denetci_yonlendirmesi = 'Asma tavan parçalarının taşıma kuvvetinin 250 N''dan az olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0751';
update public.madde_kutuphanesi set resmi_madde_metni = 'İmdat geçiş kapısı kurtarma amacıyla açıldığında, serbest bırakma noktası/noktaları kabin içinden ve ayrıca kabin dışından açıkça tanımlanmalıdır.', kontrol_basligi = 'İmdat geçiş kapısı serbest bırakma noktalarının tanımlı olması', denetci_yonlendirmesi = 'İmdat geçiş kapısının serbest bırakma noktalarının kabin içinden ve dışından açıkça tanımlı olduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0752';
update public.madde_kutuphanesi set resmi_madde_metni = 'Asma tavan serbest bırakıldıktan sonra kontrolsüz düşmesi riskine karşı önlemler alınmalıdır. Asma tavanın açılması, itfaiyeciler kabin içindeyken mümkün olmalıdır.', kontrol_basligi = 'Asma tavanın kontrolsüz düşmeye karşı korunması', denetci_yonlendirmesi = 'Asma tavanın kontrolsüz düşmeye karşı önlemli olduğunu ve itfaiyeci kabin içindeyken açılabildiğini test edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0753';
update public.madde_kutuphanesi set resmi_madde_metni = 'İmdat geçiş kapısı açık durumdayken, sıfırlama işlemi olumlu bir eylem olarak kullanılmaksızın imdat geçiş kapısı tekrar kapatılırsa, elektrik anahtarını sıfırlamamalıdır. İmdat geçiş kapısı açık olduğunda, asansörün çalışmasını engellemelidir.', kontrol_basligi = 'İmdat geçiş kapısı açıkken elektrik anahtarının sıfırlanmaması', denetci_yonlendirmesi = 'İmdat geçiş kapısı açıkken elektrik anahtarının sıfırlanmadığını ve asansörün çalışmasının engellendiğini test edin.', kaynak_form_kodu = 'ÜB.FR.40', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0754';

update public.madde_kutuphanesi set aktif = false where madde_id in ('MAD-0736','MAD-0747');

commit;

select madde_id, kontrol_basligi, aktif, (resmi_madde_metni is not null) as resmi_var from public.madde_kutuphanesi where madde_id in ('MAD-0713','MAD-0714','MAD-0715','MAD-0716','MAD-0717','MAD-0718','MAD-0719','MAD-0720','MAD-0721','MAD-0722','MAD-0723','MAD-0724','MAD-0725','MAD-0726','MAD-0727','MAD-0728','MAD-0729','MAD-0730','MAD-0731','MAD-0732','MAD-0733','MAD-0734','MAD-0735','MAD-0737','MAD-0738','MAD-0739','MAD-0740','MAD-0741','MAD-0742','MAD-0743','MAD-0744','MAD-0745','MAD-0746','MAD-0748','MAD-0749','MAD-0750','MAD-0751','MAD-0752','MAD-0753','MAD-0754', 'MAD-0736','MAD-0747') order by sira_no;
