begin;

do $$
declare dolu_sayisi int;
begin
  select count(*) into dolu_sayisi from public.madde_kutuphanesi
  where madde_id in ('MAD-0233','MAD-0234','MAD-0235','MAD-0236','MAD-0237','MAD-0238','MAD-0239','MAD-0240','MAD-0241','MAD-0242','MAD-0243','MAD-0244','MAD-0245','MAD-0246','MAD-0247','MAD-0248','MAD-0249','MAD-0250','MAD-0251','MAD-0253','MAD-0254','MAD-0255','MAD-0256','MAD-0258','MAD-0259','MAD-0260','MAD-0261') and resmi_madde_metni is not null;
  if dolu_sayisi <> 0 then
    raise exception 'Beklenmeyen durum: % satirda resmi_madde_metni zaten dolu (fail-fast)', dolu_sayisi;
  end if;
end $$;

update public.madde_kutuphanesi set resmi_madde_metni = 'Sınır güvenlik kesicileri (doğrudan kabin tarafından veya kabine bağlı dolaylı olarak)', kontrol_basligi = 'Sınır güvenlik kesicileri', denetci_yonlendirmesi = 'Sınır güvenlik kesicilerinin doğrudan kabin tarafından veya kabine bağlı dolaylı olarak çalıştığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0233';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu havalandırması (en az 0,1 m2 olmak üzere kuyu alanının 0,025 katı kadar)', kontrol_basligi = 'Kuyu havalandırma açıklığı ölçüsü', denetci_yonlendirmesi = 'Kuyu havalandırma açıklığının en az 0,1 m² olmak üzere kuyu alanının 0,025 katı kadar olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0234';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin ray uzunluğu (en az 0,1 + 0,035.v2 m)', kontrol_basligi = 'Kabin ray uzunluğu', denetci_yonlendirmesi = 'Kabin ray uzunluğunun en az 0,1 + 0,035v² m olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0235';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin üstünün kuyu tavanı arasındaki mesafe (en az 1,0 + 0,035 v² m)', kontrol_basligi = 'Kabin üstü-kuyu tavanı mesafesi', denetci_yonlendirmesi = 'Kabin üstü ile kuyu tavanı arasındaki mesafenin en az 1,0 + 0,035v² m olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0236';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin üstündeki en yüksek teçhizat ile kuyu tavanı arasında en az 0,3 + 0,035 v² m - Patenler, makaralar, halat bağlantıları, kabin üstü siperi ve kapı başlık parçalarının kuyu tavanı arası en az 0,1 + 0,035 v² m', kontrol_basligi = 'Kabin üstü teçhizat ve kuyu tavanı arası mesafeler', denetci_yonlendirmesi = 'Kabin üstündeki en yüksek teçhizat ile kuyu tavanı arasının en az 0,3+0,035v² m, patenler/makaralar/halat bağlantıları/kabin üstü siperi/kapı başlık parçaları ile kuyu tavanı arasının en az 0,1+0,035v² m olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0237';
update public.madde_kutuphanesi set resmi_madde_metni = 'En az 0,5 x 0,6 x 0,8 m sığınma boşluğu (halat ve bağlantıları bu boşlukta yer alıyorsa halatların merkezi bloğun düşey yüzeylerin 0,15 m''den daha fazlasında olmamalı)', kontrol_basligi = 'Kuyu üstü sığınma boşluğu ölçüleri', denetci_yonlendirmesi = 'Kuyu üstünde en az 0,5x0,6x0,8 m sığınma boşluğu bulunduğunu ve bu boşlukta halat/bağlantı merkezinin düşey yüzeylerden 0,15 m''den fazla uzakta olmadığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0238';
update public.madde_kutuphanesi set resmi_madde_metni = 'Bu sığınma boşluğu sağlanmıyor ise (özellikle mevcut binalarda) riskin önlenmesi için farklı uygulanabilir yöntemler kullanılabilir. (bkz. TS EN 81-21)', kontrol_basligi = 'Sığınma boşluğu sağlanamayan durumlarda alternatif önlem', denetci_yonlendirmesi = 'Sığınma boşluğu sağlanamıyorsa (özellikle mevcut binalarda) TS EN 81-21''e göre alternatif risk önleme yönteminin uygulandığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0239';
update public.madde_kutuphanesi set resmi_madde_metni = 'Karşı ağırlık ray uzunluğu (en az 0,1 + 0,035 v2 m)', kontrol_basligi = 'Karşı ağırlık ray uzunluğu', denetci_yonlendirmesi = 'Karşı ağırlık ray uzunluğunun en az 0,1 + 0,035v² m olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0240';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu aydınlatması (kabin üstü 1m''de en az 50 lüks, tavandan en fazla 0,5 m)', kontrol_basligi = 'Kuyu üstü aydınlatma seviyesi', denetci_yonlendirmesi = 'Kuyu aydınlatmasının kabin üstünden 1 m''de en az 50 lüks olduğunu ve en yakın lambanın tavandan en fazla 0,5 m uzaklıkta olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0241';
update public.madde_kutuphanesi set resmi_madde_metni = 'İletkenlerin kesit alanı en az 0,75 mm², boru / kanal içinde olması, kablo uçları cihazların içine kadar sokulmalı veya uygun bir rakor içinde son bulmalı', kontrol_basligi = 'Kuyu içi elektrik tesisatı kesit ve montaj şartı', denetci_yonlendirmesi = 'İletkenlerin kesit alanının en az 0,75 mm² olduğunu, boru/kanal içinde tesis edildiğini ve kablo uçlarının cihaz içine sokulduğunu veya uygun rakorla sonlandırıldığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0242';
update public.madde_kutuphanesi set resmi_madde_metni = 'Durak kapı kilitleme tertibatı (kilit dilinin yuvasına 7 mm girmesi, topraklama sürekliliği)', kontrol_basligi = 'Durak kapısı kilitleme tertibatı derinliği ve topraklaması', denetci_yonlendirmesi = 'Durak kapısı kilit dilinin yuvasına en az 7 mm girdiğini ve topraklama sürekliliğinin sağlandığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0243';
update public.madde_kutuphanesi set resmi_madde_metni = 'Durak kapıları etek sacı (kilit açılma bölgesinin yarı uzunluğu+5 cm, kabin giriş genişliği her iki yandan+en az 2,5 cm, metal düzgün sert kaplama, 5cm2 300N''da kalıcı şekil değişikliği olmamalı, 1 cm''den fazla esnememeli, en az 60º açı ve 2 cm sert bir pah', kontrol_basligi = 'Durak kapıları etek sacı ölçü ve dayanımı', denetci_yonlendirmesi = 'Durak kapıları etek sacının ölçülerini (kilit açılma bölgesi yarı uzunluğu+5 cm, kabin giriş genişliği her iki yandan+en az 2,5 cm), sert metal kaplamasını, 5 cm²''ye 300 N''da kalıcı deformasyon olmadığını, 1 cm''den fazla esnemediğini ve en az 60° açı + 2 cm sert pah bulunduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0244';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kilit açılma bölgesi, durak seviyesinin en fazla 0,2 m altı ve 0,2 m üstü, tam otomatik asansörler kapılarında durak seviyesinin en fazla 0,35 m altı ve 0,35 m üstü', kontrol_basligi = 'Kilit açılma bölgesi ölçüleri', denetci_yonlendirmesi = 'Kilit açılma bölgesinin durak seviyesinin en fazla 0,2 m altı/üstü (tam otomatik kapılarda 0,35 m altı/üstü) olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0245';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin ile karşı ağırlık veya dengeleme ağırlığı arasındaki açıklık (en az 50 mm)', kontrol_basligi = 'Kabin-karşı ağırlık arası açıklık', denetci_yonlendirmesi = 'Kabin ile karşı ağırlık veya dengeleme ağırlığı arasındaki açıklığın en az 50 mm olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0246';
update public.madde_kutuphanesi set resmi_madde_metni = 'Karşı ağırlık ve dengeleme ağırlığı (blokların yerinden çıkmasının engellenmesi)', kontrol_basligi = 'Karşı ağırlık/dengeleme ağırlığı bloklarının sabitliği', denetci_yonlendirmesi = 'Karşı ağırlık ve dengeleme ağırlığı bloklarının yerinden çıkmasının engellendiğini kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0247';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin girişine bakan kuyu duvarının, kapının genişliği boyunca kesintisiz bir yüzey', kontrol_basligi = 'Kabin girişi karşısındaki kuyu duvarı yüzeyi', denetci_yonlendirmesi = 'Kabin girişine bakan kuyu duvarının, kapı genişliği boyunca kesintisiz bir yüzey oluşturduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0248';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu iç yüzeyi ile kabin eşiği, kabin kapısı çerçevesi veya sürmeli kapılarda kapanan kenar arasındaki yatay açıklık 0,15 m''yi aşmamalıdır. Bu açıklık; -0,5m''yi aşmayan bir yükseklik boyunca 0,2 m olabilir, -Düşey hareketli sürmeli kapıya sahip yük asansöründe hareket boyunca 0,2 m olabilir - Mekanik olarak kilitlenen ve kilit açılma bölgesinde açılan kabin kapılarında sınır yoktur.', kontrol_basligi = 'Kuyu iç yüzeyi ile kabin eşiği arası yatay açıklık', denetci_yonlendirmesi = 'Kuyu iç yüzeyi ile kabin eşiği/kapı çerçevesi arasındaki yatay açıklığın 0,15 m''yi aşmadığını (istisnai durumlarda 0,2 m sınırına uyduğunu) ölçün.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0249';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu duvarlarının dayanımı (5 cm²''ye 300 N)', kontrol_basligi = 'Kuyu duvarlarının mekanik dayanımı', denetci_yonlendirmesi = 'Kuyu duvarlarının 5 cm²''lik alana 300 N kuvvete dayandığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0250';
update public.madde_kutuphanesi set resmi_madde_metni = 'Asansöre ait olmayan teçhizat', kontrol_basligi = 'Kuyuda asansöre ait olmayan teçhizat bulunmaması', denetci_yonlendirmesi = 'Kuyuda asansörün çalışması veya güvenliğiyle ilgisi olmayan boru, kablo, kanal veya başka bir tesisat bulunmadığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0251';
update public.madde_kutuphanesi set resmi_madde_metni = 'Geçiş yollarında sabit tesis edilmiş yeterli aydınlatma', kontrol_basligi = 'Makine/makara dairesi geçiş yollarının aydınlatması', denetci_yonlendirmesi = 'Makine ve makara dairesine geçiş yollarında sabit tesis edilmiş yeterli aydınlatma bulunduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0253';
update public.madde_kutuphanesi set resmi_madde_metni = 'Özel mekândan geçmeden, her zaman rahat ve güvenilir geçiş', kontrol_basligi = 'Makine/makara dairesine geçişin özel mekândan bağımsız olması', denetci_yonlendirmesi = 'Makine ve makara dairelerine özel bir mekândan geçmeden her zaman rahat ve güvenilir geçiş sağlandığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0254';
update public.madde_kutuphanesi set resmi_madde_metni = 'Makine ve makara mekânlarına güvenilir erişim (sabit / portatif merdiven)', kontrol_basligi = 'Makine/makara mekânlarına merdivenle erişim', denetci_yonlendirmesi = 'Makine ve makara mekânlarına sabit veya portatif merdivenle güvenilir erişim sağlandığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0255';
update public.madde_kutuphanesi set resmi_madde_metni = 'Erişim şekli portatif dayama merdivense; - En fazla 4 m yükseklikte olmalı, - Girişe tespit edilmeli, kaymaya / devrilmeye elverişli olmamalı, - 1,5 m''den yüksek ise yatayla 65°- 75° açısı olmalı, - Basamaklar genişliği en az 0,35 m, derinliği en az 25 mm - Düşey duran merdivenlerde basamaklar ile duvar arası en az 0,15 m olmalı, - En az bir adet tutamak olmalı, -1,5m yatay mesafede merdiven boyundan daha fazla yükseklikten düşme riski engellenmeli', kontrol_basligi = 'Portatif dayama merdiveni şartları', denetci_yonlendirmesi = 'Portatif dayama merdiveninin en fazla 4 m yükseklikte, girişe sabitlenmiş, kaymaz/devrilmez, 1,5 m üstünde 65-75° açılı, basamak genişliği en az 0,35 m ve derinliği en az 25 mm, tutamaklı ve düşme riskine karşı önlemli olduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0256';
update public.madde_kutuphanesi set resmi_madde_metni = 'Makine dairesi giriş kapısı (açılma yönü, en az 0,6 m genişlik ve en az 1,8 m yükseklik)', kontrol_basligi = 'Makine dairesi giriş kapısı ölçüleri', denetci_yonlendirmesi = 'Makine dairesi giriş kapısının açılma yönünü, en az 0,6 m genişliğini ve en az 1,8 m yüksekliğini ölçün.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0258';
update public.madde_kutuphanesi set resmi_madde_metni = 'Makine dairesi giriş kapısı kilit tertibatı (içeriden anahtarsız, dışarıdan anahtarla)', kontrol_basligi = 'Makine dairesi giriş kapısı kilit tertibatı', denetci_yonlendirmesi = 'Makine dairesi giriş kapısının içeriden anahtarsız, dışarıdan anahtarla açıldığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0259';
update public.madde_kutuphanesi set resmi_madde_metni = 'Binanın diğer bölümlerinden gelen pis hava doğrudan makine dairesine girmemeli', kontrol_basligi = 'Makine dairesi havalandırmasında pis hava girişi olmaması', denetci_yonlendirmesi = 'Binanın diğer bölümlerinden gelen pis havanın doğrudan makine dairesine girmediğini kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0260';
update public.madde_kutuphanesi set resmi_madde_metni = 'Makine dairesi giriş kapısı dış yüzünde uyarı yazısı', kontrol_basligi = 'Makine dairesi giriş kapısı uyarı yazısı', denetci_yonlendirmesi = 'Makine dairesi giriş kapısının dış yüzünde uyarı yazısı bulunduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0261';

update public.madde_kutuphanesi set aktif = false where madde_id in ('MAD-0232','MAD-0252','MAD-0257','MAD-0262');

commit;
