begin;

do $$
declare dolu_sayisi int;
begin
  select count(*) into dolu_sayisi from public.madde_kutuphanesi
  where madde_id in ('MAD-0313','MAD-0315','MAD-0325','MAD-0357','MAD-0358','MAD-0360','MAD-0361','MAD-0364') and resmi_madde_metni is not null;
  if dolu_sayisi <> 0 then
    raise exception 'Beklenmeyen durum: % satirda resmi_madde_metni zaten dolu (fail-fast)', dolu_sayisi;
  end if;
end $$;

update public.madde_kutuphanesi set resmi_madde_metni = 'Asansör kullanma talimatı (özellikle telefon/interkom ve varsa yükleme rampası ile ilgili)', kontrol_basligi = 'Kabin kullanma talimatı', denetci_yonlendirmesi = 'Kabin içinde asansör kullanma talimatının (özellikle telefon/interkom ve varsa yükleme rampası bilgisiyle) bulunduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0313';
update public.madde_kutuphanesi set resmi_madde_metni = 'Makina gücü ile otomatik çalışan kapılarda, kapıyı tekrar "AÇ" butonu', kontrol_basligi = 'Otomatik kapıda yeniden açma butonu', denetci_yonlendirmesi = 'Makine gücüyle otomatik çalışan kapılarda kapıyı tekrar açan butonun bulunduğunu ve çalıştığını test edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0315';
update public.madde_kutuphanesi set resmi_madde_metni = 'Otomatik kurtarma varsa kabin içinde ilgili talimatının bulunması', kontrol_basligi = 'Otomatik kurtarma talimatı', denetci_yonlendirmesi = 'Otomatik kurtarma sistemi varsa kabin içinde ilgili kullanım talimatının bulunduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0325';
update public.madde_kutuphanesi set resmi_madde_metni = '- 0,3 m < kabinin dış kenarı ile duvar arası ≤ 0,85 m ise korkuluk yüksekliği en az 0,7 m - Kabinin dış kenarı ile duvar arası > 0,85 m ise korkuluk yüksekliği en az 1,1 m - 10 cm yüksekliğinde bir ayak koruma, bir el tutamağı ve yarı yükseklikte bir ara çubuk - Kabin üstünde en fazla 0,15 m kabin tavanının içerisine doğru konumlanması - El tutamağı dış kenarı ile kuyu içindeki herhangi bir parça arası mesafe en az 0,1 m', kontrol_basligi = 'Kabin üstü korkuluğunun yapısı ve yüksekliği', denetci_yonlendirmesi = 'Kabin üstü dış kenarı ile kuyu duvarı arası 0,3 m''yi aştığında korkuluk bulunduğunu; serbest mesafe 0,85 m''ye kadarsa yüksekliğin en az 0,7 m, 0,85 m''den büyükse en az 1,1 m olduğunu; ayak koruyucu, ara çubuk ve el tutamağının mevcut olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0357';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin üstündeki serbest alan (En az 0,12 m², en küçük kenar 0,25 m)', kontrol_basligi = 'Kabin üstü çalışma alanının net ölçüleri', denetci_yonlendirmesi = 'Kabin üstünde kişinin durabileceği net alanın en az 0,12 m² ve en küçük kenarının en az 0,25 m olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0358';
update public.madde_kutuphanesi set resmi_madde_metni = 'Alarm tertibatı (acil durum besleme kaynağından, sürekli iki yönlü haberleşme)', kontrol_basligi = 'Kabin üstü alarm ve iki yönlü haberleşme', denetci_yonlendirmesi = 'Kabin üstünde acil durum besleme kaynağından sürekli çalışan iki yönlü haberleşmeli alarm tertibatı bulunduğunu test edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0360';
update public.madde_kutuphanesi set resmi_madde_metni = 'Bakım kumandası (muayene anahtarı, sürekli basılarak çalışan kumanda butonu, hareket yönleri, stop, kabin hızı 0,63 m/s''den az olmalı, hareket sınırları aşılmamalı)', kontrol_basligi = 'Kabin üstü bakım kumandasının işlevleri', denetci_yonlendirmesi = 'Bakım kumandasında iki konumlu muayene anahtarı, sürekli basılı tutularak çalışan yön/çalıştır butonları, durdurma tertibatı bulunduğunu ve muayene hızının 0,63 m/s''yi aşmadığını, hareket sınırlarının aşılmadığını test edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0361';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin/ karşı ağırlık/palanga halat bağlantıları (radansa klemens sayısı ise en az 3)', kontrol_basligi = 'Kabin, karşı ağırlık ve palanga halatı bağlantıları', denetci_yonlendirmesi = 'Kabin, karşı ağırlık ve palanga halatı uç bağlantılarını gevşeme/kayma/tel hasarı yönünden kontrol edin; radansalı klemensli bağlantıda en az 3 klemens bulunduğunu doğrulayın.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0364';

commit;
