begin;

do $$
declare dolu_sayisi int;
begin
  select count(*) into dolu_sayisi from public.madde_kutuphanesi
  where madde_id in ('MAD-0264','MAD-0265','MAD-0266','MAD-0267','MAD-0268','MAD-0269','MAD-0270','MAD-0271','MAD-0272','MAD-0273','MAD-0274','MAD-0275','MAD-0276','MAD-0277','MAD-0278','MAD-0279','MAD-0280','MAD-0281','MAD-0282','MAD-0283','MAD-0284','MAD-0285','MAD-0286','MAD-0287','MAD-0288','MAD-0289','MAD-0290','MAD-0291','MAD-0292','MAD-0293','MAD-0294','MAD-0295','MAD-0296','MAD-0297','MAD-0298','MAD-0299','MAD-0300','MAD-0301','MAD-0302','MAD-0303','MAD-0304','MAD-0305','MAD-0306','MAD-0307','MAD-0308') and resmi_madde_metni is not null;
  if dolu_sayisi <> 0 then
    raise exception 'Beklenmeyen durum: % satirda resmi_madde_metni zaten dolu (fail-fast)', dolu_sayisi;
  end if;
end $$;

update public.madde_kutuphanesi set resmi_madde_metni = 'Kabinin içinin net yüksekliği en az 2 m olmalıdır.', kontrol_basligi = 'Kabin içi net yüksekliği', denetci_yonlendirmesi = 'Kabinin içinin net yüksekliğinin en az 2 m olduğunu ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0264';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin alanı, (tamamlamalar hariç) zeminden 1 m yükseklikte duvardan duvara ölçülmelidir. Giriş kasası dikmeleri arasında kullanılabilir alan bulunan yerlerde, kapılar kapalı olduğunda; -Alanın herhangi bir kapı panelinden 100 mm'' ye eşit veya bundan küçük bir derinlikte olduğu yerlerde (çoklu panelli kapılarda hızlı ve yavaş kapılar da dâhil), bu alan zemin alanından hariç tutulmalıdır. -Alan 100 mm'' den daha fazla derinlikte olduğunda, toplam kullanılabilir alan zemin alanı içine dâhil edilmelidir.', kontrol_basligi = 'Kabin kullanılabilir alanının ölçülmesi', denetci_yonlendirmesi = 'Kabin kullanılabilir alanının, zeminden 1 m yükseklikte duvardan duvara ölçüldüğünü ve kapı paneli derinlik kuralına göre hesaplandığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0265';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin içinde monte edenin ismi, imal yılı, montaj seri numarası, beyan yükü ve insan sayısı belirtilmelidir. İmalatçının/monte eden yüklenicinin ismi:..... Montaj seri numarası:..... İmal yılı:.... Asansörün kilogram cinsinden anma yükü:..... Kişi sayısı:....', kontrol_basligi = 'Kabin kimlik ve kapasite bilgileri', denetci_yonlendirmesi = 'Kabin içinde monte edenin adı, imal yılı, montaj seri numarası, beyan yükü ve kişi sayısının etiketle belirtildiğini kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0266';
update public.madde_kutuphanesi set resmi_madde_metni = '"... kg... KİŞİ." şeklinde veya ağırlık ve kişiler için piktogramlar kullanılarak yapılmalıdır. Büyük harfler ve rakamlar ve piktogramlar için 10 mm; Küçük harfler için 7 mm.', kontrol_basligi = 'Kabin yük ve kişi sayısı işareti', denetci_yonlendirmesi = 'Kabin yük/kişi sayısı işaretinin doğru formatta ("...kg ...KİŞİ" veya piktogram) ve harf/rakam boyutlarının (büyük 10 mm, küçük 7 mm) uygun olduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0267';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin, normal erişimi için girişler, acil durum giriş kapakları ve havalandırma kanalları hariç, duvarlarla, zeminle ve tavanla tamamen kapatılmış olmalıdır.', kontrol_basligi = 'Kabin gövdesinin kapalı yapısı', denetci_yonlendirmesi = 'Kabinin, normal erişim/acil giriş kapakları ve havalandırma kanalları hariç, duvar/zemin/tavanla tamamen kapatıldığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0268';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin duvarının herhangi bir noktasına içten dışa doğru, 5 cm² alana dik olarak 300 newton kuvvet uygulandığında 1 mm''den büyük kalıcı biçim değişikliği ve 15 mm''den büyük elastik sapma oluşmamalıdır.', kontrol_basligi = 'Kabin duvarı dayanımı — 300 newton', denetci_yonlendirmesi = 'Kabin duvarına 5 cm² alana 300 N kuvvet uygulandığında 1 mm''den fazla kalıcı deformasyon veya 15 mm''den fazla elastik sapma oluşmadığını test edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0269';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin duvarının herhangi bir noktasına içten dışa doğru, 100 cm² alana dik olarak 1 000 newton kuvvet uygulandığında 1 mm''den büyük kalıcı biçim değişikliği ve 15 mm''den büyük elastik sapma oluşmamalıdır.', kontrol_basligi = 'Kabin duvarı dayanımı — 1000 newton', denetci_yonlendirmesi = 'Kabin duvarına 100 cm² alana 1000 N kuvvet uygulandığında 1 mm''den fazla kalıcı deformasyon veya 15 mm''den fazla elastik sapma oluşmadığını test edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0270';
update public.madde_kutuphanesi set resmi_madde_metni = 'Camdan yapılmış veya kısmen camdan yapılmış kabin duvarları lamine olmalıdır.', kontrol_basligi = 'Cam kabin duvarlarında lamine cam', denetci_yonlendirmesi = 'Camdan veya kısmen camdan yapılmış kabin duvarlarının lamine cam olduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0271';
update public.madde_kutuphanesi set resmi_madde_metni = 'Cam paneller, aşağıdaki bilgileri veren işaretlere sahip olmalıdır: a) tedarikçinin ismi ve ticari markası; b) cam tipi; c) kalınlık (ör. 8/8/0,76 mm).', kontrol_basligi = 'Cam panel kimlik işaretleri', denetci_yonlendirmesi = 'Cam panellerin tedarikçi adı, cam tipi ve kalınlık bilgilerini içeren işaretlere sahip olduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0272';
update public.madde_kutuphanesi set resmi_madde_metni = 'Camları, zeminden 1,10 m yükseklikten daha aşağıda yerleştirilmiş olan kabin duvarlarında 0,90 m ile 1,10 m arasında yükseklikte bir el tutamağı bulunmalıdır. Bu tutamak camdan bağımsız olarak sabitlenmelidir.', kontrol_basligi = 'Alçak cam panel önünde el tutamağı', denetci_yonlendirmesi = 'Zeminden 1,10 m altında cam bulunan kabin duvarlarında, camdan bağımsız sabitlenmiş, 0,90-1,10 m yükseklikte bir el tutamağı bulunduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0273';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin gövdesinin destek yapısı alev almayan malzemelerden yapılmalıdır. Kabin zemini, duvar ve tavan bitirmeleri için seçilen malzemeler, aşağıdaki sıralandığı gibi, EN 13501-1:2007+A1:2009''un gerekliliklerini karşılamalıdır: Zemin kaplaması: Cfl-s2; Duvar: C-s2, d1; Tavan: C-s2, d0. Son kat boyalar, duvarların üzerinde 0,30 mm'' ye kadar olan lamineler ve çalışma aygıtları gibi donanımlar, aydınlatma ve göstergeler yukarıdaki gerekliliklerden muaftır.', kontrol_basligi = 'Kabin malzemelerinin yangına tepki sınıfı', denetci_yonlendirmesi = 'Kabin destek yapısının alev almaz malzemeden olduğunu ve zemin/duvar/tavan kaplamalarının EN 13501-1 yangına tepki sınıflarını (Cfl-s2 / C-s2,d1 / C-s2,d0) karşıladığını belgeden doğrulayın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0274';
update public.madde_kutuphanesi set resmi_madde_metni = 'Ayna veya cam kaplama kırılma hâlinde EN 12600 Tip B ya da Tip C davranışı göstermelidir. Tip B, parçaların çok sayıda çatlak oluşsa da birbirinden ayrılmadığı lamine cam davranışıdır. Tip C, camın çok sayıda nispeten tehlikesiz küçük parçaya ayrıldığı temperli cam davranışıdır. Ürün işaretini veya uygunluk belgesini kontrol edin.', kontrol_basligi = 'Kabin aynası ve cam kaplamanın güvenli kırılma tipi', denetci_yonlendirmesi = 'Kabin aynası veya cam kaplamanın kırılma halinde EN 12600 Tip B veya Tip C davranışı gösterdiğini ürün işareti/uygunluk belgesinden doğrulayın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0275';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabinin üst ve alt kısımlarında havalandırma açıklıkları bulunmalıdır.', kontrol_basligi = 'Kabin üst ve alt havalandırma açıklıkları', denetci_yonlendirmesi = 'Kabinin üst ve alt kısımlarında havalandırma açıklıkları bulunduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0276';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabinin üst kısmında yer alan havalandırma açıklıklarının etkili alanı, kullanılabilir kabin alanının en az %1''i olmalıdır ve aynı durum kabinin alt kısmındaki açıklıklar için de geçerlidir. Kabin kapılarının etrafındaki boşluklar havalandırma deliklerinin alanının hesaplanmasında, gerekli etkili alanın %50''sine kadar karşıladığı kabul edilebilir.', kontrol_basligi = 'Kabin havalandırma açıklıklarının etkili alanı', denetci_yonlendirmesi = 'Kabin üst ve alt havalandırma açıklıklarının etkili alanının kullanılabilir kabin alanının en az %1''i olduğunu (kapı çevresi boşlukları %50''ye kadar sayılabilir) ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0277';
update public.madde_kutuphanesi set resmi_madde_metni = 'Havalandırma açıklıkları, iç kısımdan, kabin duvarları içinden 10 mm çapında düz rijit bir çubuk geçirmenin mümkün olmayacağı şekilde yapılmalı veya düzenlenmelidir.', kontrol_basligi = 'Havalandırma açıklıklarında erişim güvenliği', denetci_yonlendirmesi = 'Havalandırma açıklıklarından 10 mm çapında düz rijit bir çubuğun geçemediğini kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0278';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin, herhangi bir duvardan 100 mm''den az mesafede olmayacak şekilde zemin üzerinde 1 m yükseklikle ve kumanda aygıtları üzerinde en az 100 lüks bir ışık şiddeti sağlayan, kalıcı olarak monte edilmiş elektrik aydınlatması ile donatılmalıdır.(lüksmetre en kuvvetli ışığa doğru yöneltilir.)', kontrol_basligi = 'Kabin normal aydınlatma seviyesi', denetci_yonlendirmesi = 'Kabin aydınlatmasının, zeminden 1 m yükseklikte ve kumanda aygıtları üzerinde en az 100 lüks sağladığını ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0279';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabinin park hâlinde olduğu ve kapıların kapalı olduğu zaman haricinde kabin sürekli olarak aydınlatılmalıdır.', kontrol_basligi = 'Kabin aydınlatmasının sürekli çalışması', denetci_yonlendirmesi = 'Kabinin, park halinde kapılar kapalıyken hariç, sürekli aydınlatıldığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0280';
update public.madde_kutuphanesi set resmi_madde_metni = 'En az iki tane paralel bağlı lamba bulunmalıdır.', kontrol_basligi = 'Kabin aydınlatmasında lamba yedekliliği', denetci_yonlendirmesi = 'Kabin aydınlatmasında en az iki paralel bağlı lamba bulunduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0281';
update public.madde_kutuphanesi set resmi_madde_metni = 'Normal aydınlatma kesildiğinde otomatik devreye giren, yeniden şarj edilebilir acil besleme bulunmalıdır. Bu sistem en az 1 saat boyunca kabindeki her alarm başlatma aygıtında ve kabin merkezinde zeminden 1,00 m yüksekte en az 5 lüks sağlamalıdır.', kontrol_basligi = 'Kabin acil durum aydınlatması', denetci_yonlendirmesi = 'Normal aydınlatma kesildiğinde otomatik devreye giren acil aydınlatmanın en az 1 saat, alarm aygıtlarında ve kabin merkezinde 1 m yükseklikte en az 5 lüks sağladığını test edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0282';
update public.madde_kutuphanesi set resmi_madde_metni = 'Bir kurtarma hizmetiyle iki taraflı ses iletişimine izin veren kalıcı teması sağlayan EN 81-28''e uygun bir uzaktan alarm sistemi kurulmalıdır.', kontrol_basligi = 'Kabin uzaktan alarm ve iki yönlü haberleşme', denetci_yonlendirmesi = 'Kurtarma hizmetiyle iki yönlü sesli iletişim sağlayan EN 81-28''e uygun uzaktan alarm sisteminin kurulu olduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0283';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin ile acil müdahalenin yürütüldüğü nokta arasında doğrudan sesli iletişim mümkün değilse veya seyir mesafesi 30 m''yi aşıyorsa, acil durum beslemesinden çalışan dahili telefon ya da eşdeğer iki yönlü haberleşme bulunmalıdır.', kontrol_basligi = 'Kabin ile acil müdahale noktası arasında dahili haberleşme', denetci_yonlendirmesi = 'Doğrudan sesli iletişim mümkün değilse veya seyir mesafesi 30 m''yi aşıyorsa, acil durum beslemeli dahili telefon/eşdeğer haberleşme bulunduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0284';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kumanda tertibatlarının fonksiyonu açıkça tanımlanmalıdır.', kontrol_basligi = 'Kabin kumandalarının işlev işaretleri', denetci_yonlendirmesi = 'Kabin kumanda tertibatlarının işlevinin açıkça tanımlandığını (etiket/simge ile) kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0285';
update public.madde_kutuphanesi set resmi_madde_metni = 'Görünür uyarılar veya sinyaller, kabin içerisindeki bir kişinin asansörün hangi durakta durduğunu fark etmesine olanak sağlamalıdır.', kontrol_basligi = 'Kabin konum göstergesi', denetci_yonlendirmesi = 'Kabin içinden hangi durakta olunduğunu gösteren görünür uyarı/sinyal bulunduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0286';
update public.madde_kutuphanesi set resmi_madde_metni = 'Sarı renk, alarm başlatma aygıtı dışında başka bir kumanda aygıtı için kullanılmamalıdır.', kontrol_basligi = 'Alarm kumandasında sarı renk kullanımı', denetci_yonlendirmesi = 'Sarı rengin alarm başlatma aygıtı dışında başka bir kumanda için kullanılmadığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0287';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin kapıları otomatik güç ile çalışıyorsa kabinin içinde bir kumanda butonu, kabin durakta olduğunda kapılarını yeniden açmasına imkân vermelidir.', kontrol_basligi = 'Kabin içi kapı açma butonu', denetci_yonlendirmesi = 'Kabin kapıları otomatik güçle çalışıyorsa, kabin içindeki kapı açma butonunun durakta kapıyı yeniden açtığını test edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0288';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin eşiği ile durak kapısı eşiği arasındaki yatay açıklık 35 mm'' yi aşmamalıdır.', kontrol_basligi = 'Kabin ve durak eşikleri arasındaki yatay açıklık', denetci_yonlendirmesi = 'Kabin eşiği ile durak kapısı eşiği arasındaki yatay açıklığın 35 mm''yi aşmadığını ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0289';
update public.madde_kutuphanesi set resmi_madde_metni = 'Durak ve/veya kabin kapısı ile kapıya rijit bağlı mekanik parçaların ortalama kapanma hızındaki kinetik enerjisi 10 joule''ü aşmamalıdır.', kontrol_basligi = 'Güçle çalışan kapıların kapanma enerjisi', denetci_yonlendirmesi = 'Güçle çalışan kapıların ortalama kapanma hızındaki kinetik enerjisinin 10 joule''ü aşmadığını ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0290';
update public.madde_kutuphanesi set resmi_madde_metni = 'Bir sürgülü kapının ortalama kapanma hızı, hareket mesafesinin tümü üzerinden hesaplanır ancak aşağıda belirtilenler bu değerden düşülür: 1) merkezî kapanan kapılarda, her hareket yolu sonunda 25 mm; 2) yana kapanan kapılarda, her hareket yolu sonunda 50 mm.', kontrol_basligi = 'Sürgülü kapının ortalama kapanma hızının hesabı', denetci_yonlendirmesi = 'Sürgülü kapının ortalama kapanma hızı hesabında merkezî kapılarda 25 mm, yana kapanan kapılarda 50 mm''nin hareket mesafesinden düşüldüğünü kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0291';
update public.madde_kutuphanesi set resmi_madde_metni = 'Bir koruyucu aygıt, kapının/kapıların kapanma hareketi esnasında bir kişinin kapı girişinden geçmesi durumunda kapının/kapıların otomatik olarak yeniden açılmasını başlatmalıdır. Bu koruyucu aygıt, kapı kapanma aralığının son 20 mm''sinde devre dışı bırakılabilir.', kontrol_basligi = 'Kapı koruyucu aygıtının yeniden açma işlevi', denetci_yonlendirmesi = 'Kapı kapanırken bir kişi geçtiğinde koruyucu aygıtın kapıyı otomatik yeniden açtığını (son 20 mm hariç) test edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0292';
update public.madde_kutuphanesi set resmi_madde_metni = 'Koruyucu aygıt (örneğin ışık perdesi), kabin kapısı eşiği üzerinden en az 25 ila 1600 mm''lik bir açıklık mesafesini kapsamalıdır.', kontrol_basligi = 'Işık perdesinin koruma yüksekliği', denetci_yonlendirmesi = 'Koruyucu aygıtın (ör. ışık perdesi) kabin kapısı eşiğinden 25-1600 mm yükseklik aralığını kapsadığını ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0293';
update public.madde_kutuphanesi set resmi_madde_metni = 'Koruyucu aygıt, asgari 50 mm çapındaki engelleri tespit edebilmelidir.', kontrol_basligi = 'Kapı koruyucu aygıtının algılayacağı engel çapı', denetci_yonlendirmesi = 'Kapı koruyucu aygıtının en az 50 mm çapındaki engelleri algıladığını test edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0294';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kapı kapanırken, kalıcı engelleri ortadan kaldırmak için koruma aygıtı önceden belirlenmiş bir sürenin sonrasında devre dışı kalabilir.', kontrol_basligi = 'Kalıcı engelde koruyucu aygıtın geçici devre dışı kalması', denetci_yonlendirmesi = 'Kalıcı bir engel karşısında koruma aygıtının önceden belirlenmiş süre sonunda devre dışı kalabildiğini kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0295';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kapı koruyucu aygıtı devre dışı veya arızalıyken asansör çalışmaya devam ediyorsa kapıların kinetik enerjisi en fazla 4 joule olmalı ve kapı her kapanırken sesli uyarı verilmelidir.', kontrol_basligi = 'Koruyucu aygıt arızasında kapı enerjisi ve sesli uyarı', denetci_yonlendirmesi = 'Koruyucu aygıt devre dışı/arızalıyken kapı kinetik enerjisinin en fazla 4 joule olduğunu ve her kapanışta sesli uyarı verildiğini test edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0296';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kapının kapanmasını engellemek için gerekli kuvvet etkisi, kapının hareket seyrinin üçte birlik kısmı haricinde 150 newton''u aşmamalıdır.', kontrol_basligi = 'Kapının kapanmasını engelleme kuvveti', denetci_yonlendirmesi = 'Kapının kapanmasını engellemek için gereken kuvvetin (hareketin son üçte biri hariç) 150 N''u aşmadığını ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0297';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kapı kapanma hareketinin önlenmesi, kapının yeniden açılmasını başlatmalıdır. (tam açılması gerekli değil)', kontrol_basligi = 'Kapı kapanması engellendiğinde yeniden açılma', denetci_yonlendirmesi = 'Kapı kapanma hareketi engellendiğinde kapının yeniden açılmaya başladığını test edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0298';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin kapısı açık iken, asansörün çalışmaması ve harekete devam etmemesi gerekir.', kontrol_basligi = 'Kabin kapısı açıkken hareketin önlenmesi', denetci_yonlendirmesi = 'Kabin kapısı açıkken asansörün çalışmadığını ve harekete devam etmediğini test edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0299';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin kapısının kapalı kalmasını sağlayan bir elektrikli güvenlik tertibatı olmalıdır.', kontrol_basligi = 'Kabin kapısının kapalı konum denetimi', denetci_yonlendirmesi = 'Kabin kapısının kapalı kalmasını sağlayan elektrikli güvenlik tertibatı bulunduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0300';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin kapısının elektriksel olarak denetlenmesi ve kat seviyesi dışında açılmaması gerekiyor.', kontrol_basligi = 'Kabin kapısının kat seviyesi dışında açılmasının önlenmesi', denetci_yonlendirmesi = 'Kabin kapısının elektriksel olarak denetlendiğini ve kat seviyesi dışında açılmadığını test edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0301';
update public.madde_kutuphanesi set resmi_madde_metni = 'Asansörün çalışması, seviyeleme/bypass durumları haricinde, ilgili kabin kapısının kilitlenmesine otomatik olarak bağlı olmalıdır. Bu kilitleme, bir elektrik güvenlik aygıtı ile onaylanmalıdır.', kontrol_basligi = 'Kabin kapısı kilidi ile hareketin elektriksel bağı', denetci_yonlendirmesi = 'Asansörün çalışmasının (seviyeleme/bypass hariç) kabin kapısının kilitlenmesine elektrik güvenlik aygıtıyla otomatik bağlı olduğunu test edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0302';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kapılar kapalı iken, kapı panelleri arasındaki veya paneller ve dikmeler veya kapı üst pervazı veya eşikler arasındaki boşluk, 6 mm''yi aşmamalıdır. Aşınma nedeniyle bu değer, camdan yapılmış kapılar haricinde, 10 mm''ye ulaşabilir. Bu açıklıklar, varsa girintinin arkasından ölçülür.', kontrol_basligi = 'Kapı panelleri ve çevresindeki açıklıklar', denetci_yonlendirmesi = 'Kapılar kapalıyken panel arası veya panel-dikme/eşik arası boşluğun 6 mm''yi (aşınmada cam hariç 10 mm''yi) aşmadığını ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0303';
update public.madde_kutuphanesi set resmi_madde_metni = 'Yatay sürgülü kapıların ve katlanır kapılarının öndeki durak kapısı panelinin/panellerinin açılma yönünde 150 newton''luk bir manuel kuvvet uygulandığında, en uygunsuz noktada, açıklıklar 6 mm''yi aşabilir, ancak aşağıda verilen değerleri aşmamalıdır: a) yana açılan kapılar için 30 mm; b) merkezî (ortadan) açılan kapılar için toplamda 45 mm.', kontrol_basligi = 'Yatay sürgülü kapıda kuvvet altındaki açıklıklar', denetci_yonlendirmesi = 'Yatay sürgülü/katlanır kapılara 150 N manuel kuvvet uygulandığında açıklıkların yana açılan kapılarda 30 mm''yi, merkezî kapılarda toplam 45 mm''yi aşmadığını ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0304';
update public.madde_kutuphanesi set resmi_madde_metni = 'Asansörün ana besleme ayırma elemanı kapatıldığında kabin aydınlatması ve havalandırması kesilmemelidir. Sahadaki düzene göre bu eleman pako şalter, ana ayırıcı veya trifaze kaçak akım koruma elemanı olarak adlandırılmış olabilir; devreyi işlevine göre doğrulayın.', kontrol_basligi = 'Ana ayırıcı kapalıyken kabin aydınlatması ve havalandırması', denetci_yonlendirmesi = 'Ana besleme ayırıcı kapatıldığında kabin aydınlatması ve havalandırmasının kesilmediğini test edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0305';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin durma doğruluğunu bütün duraklarda, mümkünse her iki seyir yönünde ölçün. Durma seviyesi hedef kattan en fazla ±10 mm sapmalıdır.', kontrol_basligi = 'Kabinin durma doğruluğu', denetci_yonlendirmesi = 'Kabin durma doğruluğunu tüm duraklarda, mümkünse her iki yönde ölçün; hedef kattan sapmanın ±10 mm''yi aşmadığını doğrulayın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0306';
update public.madde_kutuphanesi set resmi_madde_metni = 'Yükleme veya boşaltma sırasında kabin seviyesi kat seviyesinden ±20 mm sınırına ulaştığında otomatik yeniden seviyeleme devreye girmelidir.', kontrol_basligi = 'Kabinin yeniden seviyeleme sınırı', denetci_yonlendirmesi = 'Yükleme/boşaltma sırasında kabin seviyesi kat seviyesinden ±20 mm sınırına ulaştığında otomatik yeniden seviyelemenin devreye girdiğini test edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0307';
update public.madde_kutuphanesi set resmi_madde_metni = 'Durak ve kabin eşiklerinin dayanımı (İnsan taşıma Fs=0,4.gn.Q, Yük Taşıma Fs=0,6.gn.Q) Her durak eşiği önünde verilen hafif ters eğim, kuyu içine su girmesini önlemeli,', kontrol_basligi = 'Kabin ve durak eşiklerinin dayanımı', denetci_yonlendirmesi = 'Durak ve kabin eşiklerinin dayanım hesabına (Fs=0,4·gn·Q insan / Fs=0,6·gn·Q yük) uygun olduğunu ve durak eşiği önünde su girişini önleyen hafif ters eğim bulunduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0308';

commit;
