begin;

do $$
declare dolu_sayisi int;
begin
  select count(*) into dolu_sayisi from public.madde_kutuphanesi
  where madde_id in ('MAD-0006','MAD-0008A','MAD-0008E','MAD-0009','MAD-0010','MAD-0011','MAD-0012','MAD-0013','MAD-0014','MAD-0015','MAD-0016','MAD-0017','MAD-0018','MAD-0019','MAD-0020','MAD-0021','MAD-0022','MAD-0023','MAD-0024','MAD-0025','MAD-0026','MAD-0027','MAD-0028','MAD-0029','MAD-0030','MAD-0031','MAD-0032','MAD-0033','MAD-0040','MAD-0042','MAD-0045','MAD-0046','MAD-0047','MAD-0048','MAD-0049','MAD-0050','MAD-0051','MAD-0052','MAD-0053','MAD-0054','MAD-0055','MAD-0056','MAD-0057','MAD-0058','MAD-0059','MAD-0060','MAD-0061','MAD-0062','MAD-0063','MAD-0064','MAD-0065','MAD-0066','MAD-0067','MAD-0068','MAD-0069','MAD-0070','MAD-0071','MAD-0074','MAD-0076','MAD-0077','MAD-0078','MAD-0079','MAD-0080','MAD-0081','MAD-0082','MAD-0083','MAD-0084','MAD-0085','MAD-0086','MAD-0087','MAD-0088','MAD-0098','MAD-0101','MAD-0102','MAD-0103','MAD-0105','MAD-0106','MAD-0108') and resmi_madde_metni is not null;
  if dolu_sayisi <> 0 then
    raise exception 'Beklenmeyen durum: % satirda resmi_madde_metni zaten dolu (fail-fast)', dolu_sayisi;
  end if;
end $$;

update public.madde_kutuphanesi set resmi_madde_metni = 'Tampon kaideleri sabit olmalı ve ray ekseninde olmalıdır.', denetci_yonlendirmesi = 'Tampon kaidesinin zemine sabitlendiğini, gevşeme veya deformasyon olmadığını ve kaide ekseninin kılavuz ray ekseniyle çakıştığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0006';
update public.madde_kutuphanesi set resmi_madde_metni = 'Aydınlatma anahtarı (durak seviyesinden asgari 1,0 m, kapı çerçevesinden azami 0,75 m).', denetci_yonlendirmesi = 'Kuyu dibi aydınlatma anahtarının erişim kapısı çerçevesine yatay ve durak/erişim seviyesine dikey mesafesini ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0009';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyuya erişime izin veren giriş yollarında en az 50 lüks aydınlatma sağlayan sabit bir aydınlatma sağlanmalıdır.', denetci_yonlendirmesi = 'Kuyu dibi erişim yolundaki sabit aydınlatmanın varlığını doğrulayın ve zemin seviyesinde lüksmetre ile ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0010';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu, kabinin kuyu içindeki seyri boyunca herhangi bir konumunda, tüm kapılar kapalı olduğunda bile, aşağıdaki aydınlatma yoğunluğunu sağlayan, kalıcı olarak kurulmuş elektrikli aydınlatma ile donatılmalıdır: bir kişinin kuyu alt boşluğu zemininin 1,0 m üzerinde ayakta durabileceği, çalışabileceği ve/veya çalışma alanları arasında hareket edebileceği her yerde en az 50 lüks.', denetci_yonlendirmesi = 'Tüm kapılar kapalıyken kuyu dibi zemininden 1000 mm yükseklikte, çalışma alanlarındaki aydınlığı lüksmetreyle ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0011';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin veya aksamın oluşturduğu gölgelerin haricinde, en az 20 lüks.', denetci_yonlendirmesi = 'Kabin veya donanımın gölgelediği alanlar dışında kuyudaki en düşük aydınlık değerini lüksmetreyle ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0012';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu derinliği 1,60 m''den az veya eşit ise durdurma anahtarları (kapı çerçevesi iç kenarından azami 0,75 m yatay mesafede) kuyu dibinden en fazla 2,0 m ve durak seviyesinden en az 0,4 m.', denetci_yonlendirmesi = 'Kuyu dibi derinliğini bir kez ölçün; 1600 mm veya altındaysa durdurma anahtarının yatay ve dikey konumunu bu sınırlara göre kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0013';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu derinliği 1,60 m''den fazla ise durdurma anahtarları (kapı çerçevesi iç kenarından azami 0,75 m yatay mesafede) birinci anahtar kuyu dibinden en fazla 1,20 m ve ikinci anahtar durak seviyesinden en az 1,0 m dikey mesafe içinde olmalıdır.', denetci_yonlendirmesi = 'Kuyu dibi derinliği 1600 mm''yi aşıyorsa iki durdurma anahtarının varlığını ve her birinin konum mesafelerini ayrı ayrı ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0014';
update public.madde_kutuphanesi set resmi_madde_metni = 'Durak kapıları haricinde bir kuyu alt boşluğu erişim kapısı olması durumunda, kuyu alt boşluğu zemininden 1,20 m yükseklikte tek bir durdurma anahtarı sağlanmalıdır. Aynı seviyede kuyu alt boşluğuna erişim sağlayan iki durak kapısı varsa, biri erişim donanımına sahip kuyu alt boşluğu erişim kapısı olarak belirlenmelidir.', denetci_yonlendirmesi = 'Ayrı bir kuyu dibi erişim kapısı varsa, bu kapıdan ulaşılan durdurma anahtarının yatay ve dikey konumunu ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0015';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu alt boşluğundaki durdurma anahtarı; iki konumlu dengeye sahip olmalı, kazara çalışmaya karşı korunmalı, üstünde veya yakınında, "DUR/STOP" kelimesi bulunmalıdır.', denetci_yonlendirmesi = 'Durdurma anahtarını çalıştırarak iki kararlı konumunu ve kazara çalışmaya karşı korumasını deneyin; üzerinde/yakınında DUR-STOP işaretinin bulunduğunu görsel olarak kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0016';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu alt boşluğu derinliğinin 2,50 m''yi aşması durumunda, bir erişim kapısı olmalıdır. Kuyuya erişim kapıları asgari 2,0 m yüksekliğe ve asgari 0,60 m genişliğe sahip olmalıdır. Yuvarlak veya kare kesitli 0,30 m x 0,30 m''lik bir alana eşit olarak dağıtılmış 1000 N''luk bir kuvvet, kuyu dışından herhangi bir noktada dik açılarla uygulandığında, 15 mm''den daha büyük elastik deformasyona uğramadan dayanım gösterecek bir mekanik dayanıma sahip olmalıdır.', denetci_yonlendirmesi = 'Kuyu dibi derinliği 2500 mm''yi aşıyorsa erişim kapısının varlığını, net yükseklik/genişlik ölçülerini ve mekanik dayanım deney sonucunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0017';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu alt boşluğu derinliğinin 2,50 m''yi aşmaması durumunda ya bir erişim kapısı ya da durak kapısından kolayca erişilebilir kuyu içerisinde bir merdiven sağlanmalıdır.', denetci_yonlendirmesi = 'Kuyu dibi derinliğini ölçüp 2500 mm sınırına göre erişim kapısı veya kuyu içi merdivenden hangisinin uygulandığını tespit edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0018';
update public.madde_kutuphanesi set resmi_madde_metni = 'Taşınabilir merdiven hareketli parçaların alanına dâhil oluyorsa elektrikli güvenlik tertibatı ile donatılmalı, kuyu dibinde depolanıyorsa sığınma alanına dahil edilmemelidir. (topraklaması olmalıdır.)', denetci_yonlendirmesi = 'Merdivenin muhafaza konumunun hareketli parçalarla çakışıp çakışmadığını inceleyin; çakışıyorsa elektrikli güvenlik tertibatını işlevsel olarak deneyin ve topraklamasını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0019';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu dibi merdiven kuyudan sökülemeyecek şekilde olmalı ve en az 1500 N dayanıma sahip olmalıdır.', denetci_yonlendirmesi = 'Merdivenin kalıcı olarak muhafaza edildiğini ve kuyudan çıkarılamadığını doğrulayın; dayanım belgesini/deney sonucunu kontrol edin, deney kuvvetini ölçü alanına yazmayın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0020';
update public.madde_kutuphanesi set resmi_madde_metni = 'Merdivenin portatif olması durumunda azami ağırlığı, durak kapısı eşiğinden kolay ve güvenli şekilde taşınmasını sağlamak üzere 15 kg''ı aşmamalıdır. (Hareketli ve katlanabilir merdivenler (tip 3 ve tip 4) için geçerlidir.)', denetci_yonlendirmesi = 'Hareketli veya katlanabilir merdivenin taşınma biçimini gözlemleyin ve kütlesinin 15 kg''ı aşmadığını tartarak veya belgeden doğrulayın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0021';
update public.madde_kutuphanesi set resmi_madde_metni = 'Alüminyum veya çelikten yapılmalıdır. (yanan malzeme örneğin ahşaptan yapılmamalı)', denetci_yonlendirmesi = 'Merdivenin malzemesinin alüminyum veya çelik olduğunu, ahşap kullanılmadığını görsel olarak kontrol edin; çelik ise korozyon korumasını inceleyin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0022';
update public.madde_kutuphanesi set resmi_madde_metni = 'Uzunluğu durak eşiği seviyesinden dikey olarak asgari 1,10 m yükseklikte olmalıdır.', denetci_yonlendirmesi = 'Merdiven kullanım konumundayken dikmelerin durak eşiği seviyesinden dikey yüksekliğini ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0023';
update public.madde_kutuphanesi set resmi_madde_metni = 'Merdiven dikmelerinin kesit alanı genişliği 35 mm''yi aşmamalı ve 100 mm''yi derinliği aşmamalıdır.', denetci_yonlendirmesi = 'Merdiven dikmesinin kesit genişliğini ve derinliğini kumpasla ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0024';
update public.madde_kutuphanesi set resmi_madde_metni = 'Merdiven basamaklarının en kesiti; asgari 25 mm ve azami 35 mm düz basamağa veya çapa sahip dairesel veya çokgen (kare veya 4 kenardan fazla) olmalıdır.', denetci_yonlendirmesi = 'Basamak kesitinin biçimini ve çapını/düz yüzey ölçüsünü ölçün, kaymazlığını elle kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0025';
update public.madde_kutuphanesi set resmi_madde_metni = 'Basamaklar genişliği en az 0,28 m ve basamak aralıkları 0,25-0,3 m arasında eşit olmalıdır.', denetci_yonlendirmesi = 'Basamak net genişliğini ve ardışık basamaklar arası düşey aralığı ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0026';
update public.madde_kutuphanesi set resmi_madde_metni = 'Düşey merdivenlerde, herhangi bir basamağın arkası ile kuyu alt boşluğu duvarı arasında asgari 200 mm net mesafe bulunmalıdır.', denetci_yonlendirmesi = 'Düşey merdivende en dar basamağın arkası ile kuyu duvarı arasındaki net mesafeyi ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0027';
update public.madde_kutuphanesi set resmi_madde_metni = 'Durak girişi kenarı ile muhafaza konumundaki merdiven arasındaki mesafe, 800 mm''den fazla olmamalıdır.', denetci_yonlendirmesi = 'Merdiven muhafaza konumundayken durak girişi kenarına olan mesafeyi ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0028';
update public.madde_kutuphanesi set resmi_madde_metni = 'Durak girişi kenarı ile çalışma konumundaki merdivenin basamak sırasının ortası arasındaki mesafe, kolayca ulaşılabilir olması için azami 600 mm olmalıdır.', denetci_yonlendirmesi = 'Merdiven çalışma konumundayken durak girişi kenarı ile basamak ekseni arasındaki yatay mesafeyi ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0029';
update public.madde_kutuphanesi set resmi_madde_metni = 'Merdivenin birinci basamak yüksekliği, durak eşiğinin seviyesine mümkün olduğu kadar yakın konumlandırılmalıdır.', denetci_yonlendirmesi = 'İlk basamağın kotu ile durak eşiği kotu arasındaki farkı ölçüp saha kaydı olarak not edin; standart kesin bir tolerans belirtmez.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0030';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyuya erişim sağlayan herhangi bir kapıya/kapağa bitişik erişim yolu, kalıcı olarak kurulmuş en az 50 lüks aydınlatma şiddetine sahip elektrik aydınlatması ile aydınlatılmalıdır.', denetci_yonlendirmesi = 'Merdiven erişim yolunun kalıcı elektrikli aydınlatmasının bulunduğunu doğrulayın ve gerekiyorsa lüks değerini ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0031';
update public.madde_kutuphanesi set resmi_madde_metni = 'Giriş kapısı yoksa taşınabilir merdivenden 1,8 m yükseklikte azami 0,8 m yatay mesafede durak kapısının kilidi açılabilmelidir. (veya kalıcı bir tertibat kapı kilidini açabilmeli)', denetci_yonlendirmesi = 'Ayrı erişim kapısı yoksa, merdivenden durak kapısı kilidine olan yatay ve dikey erişim mesafesini ölçün veya kalıcı kilit açma tertibatının işlevini deneyin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0032';
update public.madde_kutuphanesi set resmi_madde_metni = 'Sığınma alanının 0,30 m içerisinde muayene kumanda istasyonu bulunmalıdır.', denetci_yonlendirmesi = 'Kalıcı muayene kumanda istasyonunun sığınma alanına olan mesafesini ölçün ve istasyonun bu alandan çalıştırılabildiğini deneyin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0033';
update public.madde_kutuphanesi set resmi_madde_metni = 'Birden fazla kontrol kumanda istasyonu, "KONTROL"e geçmiş ise, kontrol kumanda istasyonunda aynı basma butonları aynı anda basılmadıkça, bunların herhangi birinden kabini hareket ettirmek mümkün olmamalıdır.', denetci_yonlendirmesi = 'İki veya daha fazla muayene istasyonunu aynı anda KONTROL konumuna alıp, yalnızca tüm istasyonlarda aynı anda basıldığında kabinin hareket ettiğini deneyerek doğrulayın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0040';
update public.madde_kutuphanesi set resmi_madde_metni = 'Mahsur kalma tehlikesi varsa ve bu mahsur kalma durumu için hiçbir vasıta sağlanmamışsa EN 81-28''e göre sığınma alanından kullanılabilecek alarm başlatma cihazları bulunmalıdır.', denetci_yonlendirmesi = 'Kuyu dibinde mahsur kalma riski olup olmadığını değerlendirin; risk varsa sığınma alanından erişilebilen alarm başlatma cihazını işlevsel olarak deneyin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0042';
update public.madde_kutuphanesi set resmi_madde_metni = 'Karşı ağırlık bölme duvarı (kuyu dibinden en az 2,0 m yükseklik, kuyu dibi ile bölmenin en alt bölümü arası en fazla 0,3 m, genişlik en az karşı ağırlık genişliği) olmalıdır.', denetci_yonlendirmesi = 'Karşı ağırlık ayırıcı bölmesinin alt kenarının kuyu dibi zeminine, üst kenarının ise yüksekliğine ve genişliğine göre ölçülerini alın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0045';
update public.madde_kutuphanesi set resmi_madde_metni = 'Karşı ağırlık rayı ile kuyu duvarı arası 0,3 m''den fazla ise bölme duvarı ile kapatılmalıdır.', denetci_yonlendirmesi = 'Karşı ağırlık rayı ile kuyu duvarı arasındaki açıklığı ölçün; 300 mm''yi aşıyorsa bu alanın da bölme ile kapatıldığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0046';
update public.madde_kutuphanesi set resmi_madde_metni = 'Herhangi bir noktada 5 cm² yuvarlak/kare alana 300 N''a karşı yeterli rijitliğe sahip olmalı.', denetci_yonlendirmesi = 'Ayırıcı bölmeye 300 N''luk kuvvet uygulanan deney sonucunu inceleyin; bölmenin karşı ağırlıkla çarpışmaya yol açacak sapma göstermediğini kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0047';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin üst boşluğu boyutlarını korumak için kabin en üst durak seviyesinde iken, karşı ağırlık ve karşı ağırlık tamponları arasında müsaade edilen azami açıklıkları belirten bir işaret, karşı ağırlığı gösteren bölmeye yakın veya üzerine konmalıdır.', denetci_yonlendirmesi = 'Karşı ağırlık bölmesi üzerinde veya yakınında azami açıklık işaretinin bulunduğunu ve okunaklı olduğunu görsel olarak kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0048';
update public.madde_kutuphanesi set resmi_madde_metni = 'Bu bölme duvarı delikli ise, EN ISO 13857 standardı 4.2.4.1''e uymalıdır. Sr: bölme ile hareketli parça arası mesafeyi, e: delikli kısmın açıklığını ifade etmektedir.', denetci_yonlendirmesi = 'Ayırıcı bölme delikliyse açıklık ölçüsünü ve bölme ile hareketli parça arası mesafeyi ölçüp TS EN ISO 13857 Çizelge 4 ile karşılaştırın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0049';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyunun altında erişilebilir boşluklar mevcutsa, kuyu alt boşluğu zemini maruz kalınacak en az 5000 N/m²''lik bir yüke göre tasarlanmalı ve karşı ağırlık veya dengeleme ağırlığı güvenlik tertibatıyla donatılmalıdır.', denetci_yonlendirmesi = 'Kuyu altında erişilebilir hacim varsa, zemin tasarım yükünü teknik dosyadan doğrulayın ve karşı ağırlık/dengeleme ağırlığında güvenlik tertibatı bulunduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0050';
update public.madde_kutuphanesi set resmi_madde_metni = 'Asansörler, kabinin ve karşı ağırlığın seyrinin en alt sınırında tamponlarla donatılmalıdır. Kabine veya karşı ağırlığa sabitlenmiş tampon/tamponlar bulunması durumunda, tamponun/tamponların kuyu alt boşluğu zemini üzerindeki etki alanı/alanları, yüksekliği 300 mm''den az olmayan engel/engeller (kaide, baba) ile belirgin hâle getirilmelidir. Karşı ağırlık bölme duvarı kuyu alt boşluğu tabanından 50 mm''den fazla uzatılmadığı durumlarda karşı ağırlığa sabitlenmiş tampon/tamponlar için bir engel gerekli değildir.', denetci_yonlendirmesi = 'Kabin ve karşı ağırlık tamponlarının varlığını, çarpma alanındaki kaide/baba yüksekliğinin en az 300 mm olduğunu ölçüp kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0051';
update public.madde_kutuphanesi set resmi_madde_metni = 'Doğrusal özelliklere sahip tampon stroku, 0,135 v² ve 65 mm''den az olmamalıdır.', denetci_yonlendirmesi = 'Doğrusal tamponun toplam kullanılabilir strokunu ölçüp beyan hızına göre gerekli asgari stroku mühendis hesabıyla karşılaştırın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0052';
update public.madde_kutuphanesi set resmi_madde_metni = 'Doğrusal özelliklere sahip enerji biriktiren tipte tamponlar, yalnızca asansörün anma hızı 1 m/s''yi geçmiyorsa kullanılmalıdır.', denetci_yonlendirmesi = 'Doğrusal enerji biriktiren tampon kullanılmışsa asansörün beyan hızının 1 m/s''yi aşmadığını denetim bilgilerinden doğrulayın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0053';
update public.madde_kutuphanesi set resmi_madde_metni = 'Enerji dağıtan tipteki tampon stroku, 0,0674 v² olmalıdır.', denetci_yonlendirmesi = 'Enerji dağıtan tamponun toplam kullanılabilir strokunu ölçüp beyan hızına göre gerekli asgari değerle karşılaştırın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0054';
update public.madde_kutuphanesi set resmi_madde_metni = '2,50 m/s''nin üzerindeki anma hızları için enerji dağıtan tipteki tampon stroku, 0,42 m''den küçük olmamalıdır.', denetci_yonlendirmesi = 'Beyan hızı 2,50 m/s''yi aşıyorsa tampon strokunun en az 420 mm olduğunu ölçerek kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0055';
update public.madde_kutuphanesi set resmi_madde_metni = 'Enerjiyi dağıtan tipte tamponlar, asansörün anma hızı ne olursa olsun kullanılabilir. Emniyet kontağı olmalıdır. (topraklaması olmalıdır.)', denetci_yonlendirmesi = 'Enerji dağıtan tamponun normal konumuna dönüşünü denetleyen elektrikli güvenlik tertibatını deneyin ve topraklamasını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0056';
update public.madde_kutuphanesi set resmi_madde_metni = 'Doğrusal olmayan özelliklere sahip tamponlar stroku tampon yüksekliğinin %90''ı olarak hesaplanır.', denetci_yonlendirmesi = 'İlk montaj yüksekliğini ve deneyde ulaşılan en düşük yüksekliği ölçün; tam sıkışmanın ilk yüksekliğin %90''ına karşılık geldiğini kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0057';
update public.madde_kutuphanesi set resmi_madde_metni = 'Doğrusal olmayan özelliklere sahip enerji biriktiren tipte tamponlar, yalnızca asansörün anma hızı 1 m/s''yi geçmiyorsa kullanılmalıdır.', denetci_yonlendirmesi = 'Doğrusal olmayan enerji biriktiren tampon kullanılmışsa beyan hızının 1 m/s''yi aşmadığını denetim bilgilerinden doğrulayın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0058';
update public.madde_kutuphanesi set resmi_madde_metni = 'Doğrusal olmayan özelliklere sahip enerji biriktiren tipteki tamponlar ve enerjiyi yayan tipteki tamponlar güvenlik aksamı olarak kabul edilir ve EN 81-50 gerekliliklere göre doğrulanmalıdır.', denetci_yonlendirmesi = 'Tamponun tip inceleme belgesini ve ürün tanımını EN 81-50 kapsamındaki doğrulamayla karşılaştırın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0059';
update public.madde_kutuphanesi set resmi_madde_metni = 'Doğrusal özelliklere sahip olanlar dışındaki tamponlarda (poliüretan ve hidrolik), aşağıdakileri gösteren bir bilgi plakası bulunmalıdır: a) tamponun imalatçısının adı; b) tip inceleme belgesi numarası; c) tamponun tipi; d) hidrolik tamponlarda akışkanın gösterimi ve türü. e) CE işareti.', denetci_yonlendirmesi = 'Tampon bilgi plakasındaki imalatçı, belge numarası, tip ve (hidrolikte) akışkan bilgilerini teknik dosyayla karşılaştırın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0060';
update public.madde_kutuphanesi set resmi_madde_metni = '1,75 m/s''yi aşan anma hızları için germesiz dengeleme araçları, dönüşün yakınında kılavuzlanmalıdır.', denetci_yonlendirmesi = 'Beyan hızı 1,75 m/s''yi aşıyorsa germesiz dengeleme aracının dönüş noktası yakınında kılavuzlandığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0061';
update public.madde_kutuphanesi set resmi_madde_metni = '3,0 m/s''yi aşmayan anma hızları için, zincirler, halatlar veya kayışlar gibi araçlar kullanılabilir.', denetci_yonlendirmesi = 'Beyan hızı 3,0 m/s''yi aşmıyorsa kullanılan dengeleme aracının tipini (zincir/halat/kayış) tespit edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0062';
update public.madde_kutuphanesi set resmi_madde_metni = '3,0 m/s''yi aşan anma hızları için dengeleme halatları sağlanmalıdır.', denetci_yonlendirmesi = 'Beyan hızı 3,0 m/s''yi aşıyorsa dengeleme aracının halat tipinde olduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0063';
update public.madde_kutuphanesi set resmi_madde_metni = 'Anma hızı 3,5 m/s''yi aşan asansörler için, ilave olarak bir geri tepmeyi önleme aygıtı bulunmalıdır; geri tepmeyi önleme aygıtının çalışması, asansör makinesinin bir elektrik güvenlik aygıtı tarafından durdurulmasını başlatmalıdır.', denetci_yonlendirmesi = 'Beyan hızı 3,5 m/s''yi aşıyorsa geri tepmeyi önleme aygıtının varlığını ve tetiklendiğinde makineyi durduran elektrik güvenlik tertibatını deneyin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0064';
update public.madde_kutuphanesi set resmi_madde_metni = 'Gergi makaralarının bölüm çapı ile dengeleme halatlarının anma çapı arasındaki oran en az 30 olmalıdır.', denetci_yonlendirmesi = 'Gergi makarası bölüm çapını ve dengeleme halatı anma çapını ölçüp oranın en az 30 olduğunu hesaplayın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0065';
update public.madde_kutuphanesi set resmi_madde_metni = 'Asansör kuyusunda birden fazla asansör varsa, farklı asansörlere ait hareketli parçalar arasında ayırıcı bölme bulunmalıdır.', denetci_yonlendirmesi = 'Ortak kuyudaki komşu asansörlerin hareketli parçaları arasında ayırıcı bölmenin bulunduğunu görsel olarak kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0066';
update public.madde_kutuphanesi set resmi_madde_metni = 'Ayırıcı bölme delikli malzemeden yapılmışsa, EN 13857 4.2.4.1 dikkate alınmalıdır.', denetci_yonlendirmesi = 'Delikli ayırıcı bölmede açıklık biçimini ve ölçüsünü belirleyip hareketli parçaya olan mesafeyle birlikte TS EN ISO 13857 Çizelge 4''e göre değerlendirin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0067';
update public.madde_kutuphanesi set resmi_madde_metni = 'Ayırıcı bölme, yuvarlak veya kare kesitte 5 cm²''lik bir alana eşit olarak dağıtılmış 300 N''luk bir kuvvet, herhangi bir noktasına dik açıda uygulandığında, sapma göstererek hareketli kısımlarla çarpışmamasını sağlayacak yeterli rijitliğe sahip olmalıdır.', denetci_yonlendirmesi = 'Asansörler arası ayırıcı bölmeye uygulanan 300 N''luk kuvvet deneyinin sonucunu inceleyip hareketli parçaya temas olmadığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0068';
update public.madde_kutuphanesi set resmi_madde_metni = 'Ayırıcı bölme, kuyu alt boşluğu zemininden 0,30 m mesafe içinden en alt durak zemininin 2,5 m üstünde bir yüksekliğe kadar uzanmalıdır. Genişlik, bir kuyu alt boşluğundan diğerine erişimi engellemek için yeterli olmalıdır.', denetci_yonlendirmesi = 'Ayırıcı bölmenin alt başlangıç kotunu ve üst uzandığı yüksekliği ölçün; genişliğinin kuyu dibinden diğerine geçişi engellediğini kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0069';
update public.madde_kutuphanesi set resmi_madde_metni = 'Herhangi bir korkuluğun iç kenarı ile bitişik bir asansörün hareketli kısmı (kabin, karşı ağırlık veya dengeleme ağırlığı) arasındaki yatay mesafe 0,50 m''den az ise ayırıcı bölme kuyunun tüm yüksekliği boyunca uzanmalıdır. Bu ayırıcı bölme, en az hareketli kısmın genişliğinde olmalı ve kuyu yüksekliği boyunca her bir tarafta ilave 0,10 m uzatılmalıdır.', denetci_yonlendirmesi = 'Korkuluk iç kenarı ile bitişik asansörün hareketli kısmı arasındaki yatay mesafeyi ölçün; 500 mm altındaysa bölmenin tam kuyu yüksekliği boyunca ve her yanda 100 mm fazlasıyla uzandığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0070';
update public.madde_kutuphanesi set resmi_madde_metni = 'Hız regülatörü gergi ağırlığı makarasının koruması (Şahıs yaralanması, halatın makaralardan çıkması, halat ve makara arasına cisimlerin girmesi).', denetci_yonlendirmesi = 'Gergi makarası korumasının kişi yaralanmasını, halatın makaradan çıkmasını ve araya cisim girmesini önlediğini görsel olarak kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0071';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin hız regülatörü halatının kopması veya aşırı uzaması durumunda bir elektrik güvenlik tertibatı asansörün motorunu durdurmalıdır. (topraklaması olmalıdır.)', denetci_yonlendirmesi = 'Hız regülatörü halatı gevşediğinde veya koptuğunda devreye giren elektrikli güvenlik tertibatını deneyin ve gergi tertibatının topraklamasını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0074';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu alt boşluğu sığınma alanı (girişten okunabilir işaret, kişi sayısı ve duruş tipi). Birden fazla sığınma boşluğu bulunması durumunda, bunlar aynı tipte olmalı ve birbirine karışmamalıdır.', denetci_yonlendirmesi = 'Kuyu dibi girişinden okunabilen sığınma alanı işaretindeki kişi sayısı ve duruş tipini sahadaki fiili sığınma alanlarıyla karşılaştırın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0076';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin göre en alt konumdayken, kuyu alt boşluğu zemininde Çizelge 4''ten seçilen bir sığınma boşluğunun barındırılabileceği en az bir adet açık alan sağlanmalıdır. Tip 1 – Dik duruş vaziyetteki duruş (0,40 x 0,50 x 200) m; Tip 2 – Çömelmiş vaziyetteki duruş (0,50 x 0,70 x 100) m; Tip 3 – Yan yatmış duruş (0,70 x 1,0 x 50) m.', denetci_yonlendirmesi = 'Kabin en alt konumdayken kuyu dibi zemininde seçilen sığınma alanı tipini belirleyip net genişlik, derinlik ve yüksekliğini ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0077';
update public.madde_kutuphanesi set resmi_madde_metni = 'Bu sığınma boşluğu sağlanmıyor ise riskin önlenmesi için farklı uygulanabilir yöntemler (bkz. TS EN 12100 ve TS EN ISO 14798).', denetci_yonlendirmesi = 'Standart sığınma alanı sağlanmıyorsa teknik dosyadaki risk değerlendirmesini ve eşdeğer koruyucu tedbirlerin sahada aynen uygulandığını doğrulayın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0078';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu tabanı ile kabinin en alt kısımları arasında en az 0,5 m düşey mesafe olmalıdır.', denetci_yonlendirmesi = 'Kabin en alt konumdayken kuyu dibi zemini ile kabinin en alt parçası arasındaki serbest düşey mesafeyi ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0079';
update public.madde_kutuphanesi set resmi_madde_metni = 'Düşey mesafe bitişik duvara 15 cm yatay mesafede kabinin dikey sürgülü kapı parçaları veya eteğinin parçaları asgari 10 cm''ye kadar azaltma olabilir. Düşey mesafe bitişik duvara 15 cm yatay mesafeden fazla ise kabinin dikey sürgülü kapı parçaları veya eteğinin parçaları asgari 50 cm olmalıdır.', denetci_yonlendirmesi = 'Kabin eteği veya düşey sürgülü kapının bitişik duvara yatay mesafesini ölçün; 150 mm altındaysa düşey açıklığın en az 100 mm olduğunu, üzerindeyse genel 500 mm şartının uygulandığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0080';
update public.madde_kutuphanesi set resmi_madde_metni = 'Düşey mesafe kabin çerçevesi parçaları, güvenlik tertibatları, kılavuz pabuçları, oturma tertibatları için kılavuz raylardan azami yatay mesafe içinde, Şekil 6 ve 7''ye uygun olmalıdır.', denetci_yonlendirmesi = 'Kabin çerçevesi/güvenlik tertibatı/kılavuz pabucu parçalarının kılavuz raya yatay uzaklığını ve kuyu dibine düşey mesafesini ölçüp Şekil 6-7''deki sınır eğrisiyle karşılaştırın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0081';
update public.madde_kutuphanesi set resmi_madde_metni = 'Her kabin eşiğine, karşısındaki net durak kapısının en az tam genişliğinde uzanan bir koruma eteği sacı monte edilmelidir. Bu düşey bölüm, yatay düzlemle en az 60°''lik açı yapan bir pah ile aşağıya doğru uzatılmalıdır. Bu pahın yatay düzlemden olan çıkıntısı 20 mm''den az olmamalıdır.', denetci_yonlendirmesi = 'Koruma eteğinin durak kapısı açıklığını tam genişlikte kapladığını ve alt pahın açısı ile yatay izdüşümünü ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0082';
update public.madde_kutuphanesi set resmi_madde_metni = 'Koruma eteğinin yüzü üzerindeki herhangi bir çıkıntı, örneğin bağlantı kısımları gibi, 5 mm''yi aşmamalıdır. 2 mm''yi aşan çıkıntılar, yatayla en az 75°''lik bir açı yapacak şekilde pahlanmalıdır.', denetci_yonlendirmesi = 'Koruma eteği yüzeyindeki bağlantı çıkıntılarının boyutunu ölçün; 2 mm''yi aşanların pahlı olup olmadığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0083';
update public.madde_kutuphanesi set resmi_madde_metni = 'Düşey kısmın yüksekliği en az 0,75 m olmalıdır.', denetci_yonlendirmesi = 'Koruma eteğinin düşey bölümünün net yüksekliğini ölçün.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0084';
update public.madde_kutuphanesi set resmi_madde_metni = 'Yuvarlak veya kare kesitli 5 cm²''lik bir alana eşit olarak dağılan 300 N''luk bir kuvvet, koruma eteğinin durak tarafından, düşey kesitin alt kenarı boyunca herhangi bir noktada dik açılarda uygulandığında, aşağıdakiler olmaksızın koruma eteği bu kuvvete dayanmalıdır: a) 1 mm''den daha büyük kalıcı deformasyon; b) 35 mm''den daha büyük elastik deformasyon.', denetci_yonlendirmesi = 'Koruma eteğine uygulanan 300 N''luk kuvvet deneyinde ölçülen kalıcı ve elastik deformasyon değerlerini kaydedip sınırlarla karşılaştırın.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0085';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kabin altına sabitlenmiş kasnaklar veya dişliler varsa, korumaya sahip olmalı (Halatın makaralardan çıkması, halat ve makara arasına cisimlerin girmesi).', denetci_yonlendirmesi = 'Kabin altı kasnak/dişli varsa korumasının halat çıkmasını ve araya cisim girmesini önlediğini görsel olarak kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0086';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu duvarları ve zemin yüzeyleri toz oluşturmayan (örneğin, beton, tuğla veya briket gibi), kaygan olmayan, su sızdırmayan dayanıklı malzemeden yapılmalı ve zemin yaklaşık aynı seviyede olmalıdır.', denetci_yonlendirmesi = 'Kuyu dibi zemininin kaymazlığını, su sızdırmazlığını ve toz oluşturmayan dayanıklı malzemeden yapıldığını, zeminin aynı seviyede olduğunu görsel olarak kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0087';
update public.madde_kutuphanesi set resmi_madde_metni = 'Güvenlik kontakları, asgari koruma derecesi IP4X (EN 60529:1992) ve bu amaç için uygun mekanik dayanıklı olmalıdır.', denetci_yonlendirmesi = 'Kuyu dibindeki güvenlik kontaklarının mahfazasının en az IP4X koruma derecesinde olduğunu ve mekanik zorlanmaya dayanıklı yapıldığını kontrol edin.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0088';
update public.madde_kutuphanesi set resmi_madde_metni = 'Karşı ağırlık seperatörü (kuyu tabanından en fazla 0,3 m''den başlayacak şekilde en az 2,5 m yükseklik, karşı ağırlığın genişliği + her iki yanına 0,1 m ilave genişlik).', denetci_yonlendirmesi = 'Karşı ağırlık ayırıcı bölmesinin başlangıç kotunu, yüksekliğini ve genişliğini ölçün.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0098';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu alt boşluğu güvenlik hacmi (0,5 m x 0,6 m x 1 m).', denetci_yonlendirmesi = 'Kabin tamponları tamamen sıkışmışken kuyu dibinde 0,50x0,60x1,00 m''lik bloğun yerleşebileceği net hacmi ölçüp kaydedin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0101';
update public.madde_kutuphanesi set resmi_madde_metni = 'Bu sığınma boşluğu sağlanmıyor ise (özellikle mevcut binalarda) riskin önlenmesi için farklı uygulanabilir yöntemler kullanılabilir. (bkz. TS EN 81-21)', denetci_yonlendirmesi = 'Standart güvenlik hacmi sağlanamıyorsa teknik dosyada TS EN 81-21''e göre seçilmiş alternatif tedbirlerin sahada uygulandığını doğrulayın.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0102';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu tabanı ile kabinin en alt kısımları arasında düşey mesafe en az 0,5 m. Bu mesafe aşağıdaki şartlarda 0,1 m''ye kadar düşebilir: kabin eteği ile duvarlar arası yatay mesafe en az 15 cm ise, kabinin en alt kısımları ile raylar arası yatay mesafe en az 15 cm ise.', denetci_yonlendirmesi = 'Kabin tamponları tamamen sıkışmışken kuyu dibi ile kabin en alt kısmı arası düşey mesafeyi ölçün; istisna şartlarındaki yatay mesafeleri de ayrıca kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0103';
update public.madde_kutuphanesi set resmi_madde_metni = 'Enerji depolayan doğrusal olmayan karakteristikli (poliüretan) tamponlar varsa; beyan hızı en fazla 1 m/s, strok mesafesi tamponun yüksekliğinin %90 oranı.', denetci_yonlendirmesi = 'Poliüretan tampon kullanılmışsa beyan hızının 1 m/s''yi aşmadığını doğrulayın ve tam sıkışmış strok mesafesini tampon yüksekliğinin %90''ı esasına göre ölçün.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0105';
update public.madde_kutuphanesi set resmi_madde_metni = 'Hidrolik tamponlar varsa; elektrikli güvenlik tertibatı, hidrolik seviyesi kontrolü.', denetci_yonlendirmesi = 'Hidrolik tampon varsa yağ seviyesini ve sızıntı durumunu kontrol edin, tamponun uzamış konumunu denetleyen elektrikli güvenlik tertibatını deneyin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0106';
update public.madde_kutuphanesi set resmi_madde_metni = 'Kuyu altında erişilebilir boşluk varsa, zemin dayanımı en az 5000 N/m² (Karşı ağırlık altındaki beton kaide zemine kadar olmalı veya güvenlik tertibatıyla donatılmalıdır.)', denetci_yonlendirmesi = 'Kuyu altında erişilebilir hacim varsa zemin tasarım yükünü teknik dosyadan doğrulayın; karşı ağırlık altındaki beton kaidenin zemine ulaştığını veya güvenlik tertibatı bulunduğunu kontrol edin.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0108';
update public.madde_kutuphanesi set resmi_madde_metni = 'TEMEL KUYU TASARIM ÖLÇÜLERİ (mm): Kuyu genişliği, Kuyu derinliği, Kabin tampon yüksekliği, Ray ile kapı arası, Kuyu dibi yüksekliği, Karşı ağırlık yeri (Arka/Sol/Sağ), Kabin raylar arası, Karşı ağırlık raylar arası, Kabin kılavuz ray tipi, Karşı ağırlık kılavuz ray tipi, Kat kapısı net genişliği, Kat kapısı net yüksekliği, Kat kapısının tipi (Otomatik/Manuel) ve açılma yönü (Sağ/Sol/Merkezi/Düşey), Kabin genişliği, Kabin derinliği, Kabin kılavuz ray konsolları arası mesafe, Kabin patenleri arası düşey mesafe, Karşı ağırlık kılavuz ray konsolları arası mesafe, Karşı ağırlık patenleri arası düşey mesafe.', denetci_yonlendirmesi = 'Kuyuya girdikten sonra erişilebilen sabit yüzeylerden kuyu genişliği ve derinliğini, kabin tampon yüksekliğini ve karşı ağırlığın kuyudaki yerini ölçüp kaydedin; bu alan otomatik uygunluk sonucu üretmez, yalnızca saha kaydıdır.', kaynak_form_kodu = 'ÜB.FR.38', kaynak_form_revizyonu = 'R.04' where madde_id = 'MAD-0008A';
update public.madde_kutuphanesi set resmi_madde_metni = 'TEMEL KUYU TASARIM ÖLÇÜLERİ (mm): Kuyu genişliği, Kuyu derinliği, Kabin tampon yüksekliği, Ray ile kapı arası, Kuyu dibi yüksekliği, Karşı ağırlık yeri (Arka/Sol/Sağ), Kabin raylar arası, Karşı ağırlık raylar arası, Kabin kılavuz ray tipi, Karşı ağırlık kılavuz ray tipi, Kat kapısı net genişliği, Kat kapısı net yüksekliği, Kat kapısının tipi (Otomatik/Manuel) ve açılma yönü (Sağ/Sol/Merkezi/Düşey), Kabin genişliği, Kabin derinliği.', denetci_yonlendirmesi = 'FR.39 temel kuyu tasarım tablosu için kuyu dibi yüksekliğini ve kabin tampon yüksekliğini sahada ölçerek kaydedin; bu alan otomatik uygunluk sonucu üretmez.', kaynak_form_kodu = 'ÜB.FR.39', kaynak_form_revizyonu = 'R.02' where madde_id = 'MAD-0008E';

update public.madde_kutuphanesi set aktif = false where madde_id in ('MAD-0007','MAD-0008');

commit;

select madde_id, kontrol_basligi, aktif, (resmi_madde_metni is not null) as resmi_var from public.madde_kutuphanesi where madde_id in ('MAD-0006','MAD-0008A','MAD-0008E','MAD-0009','MAD-0010','MAD-0011','MAD-0012','MAD-0013','MAD-0014','MAD-0015','MAD-0016','MAD-0017','MAD-0018','MAD-0019','MAD-0020','MAD-0021','MAD-0022','MAD-0023','MAD-0024','MAD-0025','MAD-0026','MAD-0027','MAD-0028','MAD-0029','MAD-0030','MAD-0031','MAD-0032','MAD-0033','MAD-0040','MAD-0042','MAD-0045','MAD-0046','MAD-0047','MAD-0048','MAD-0049','MAD-0050','MAD-0051','MAD-0052','MAD-0053','MAD-0054','MAD-0055','MAD-0056','MAD-0057','MAD-0058','MAD-0059','MAD-0060','MAD-0061','MAD-0062','MAD-0063','MAD-0064','MAD-0065','MAD-0066','MAD-0067','MAD-0068','MAD-0069','MAD-0070','MAD-0071','MAD-0074','MAD-0076','MAD-0077','MAD-0078','MAD-0079','MAD-0080','MAD-0081','MAD-0082','MAD-0083','MAD-0084','MAD-0085','MAD-0086','MAD-0087','MAD-0088','MAD-0098','MAD-0101','MAD-0102','MAD-0103','MAD-0105','MAD-0106','MAD-0108','MAD-0007','MAD-0008') order by sira_no;