-- AVES Saha R15D-rc3.9.10
-- Ek standartlar: TS EN 81-21 (mevcut binalarda kurulum), TS EN 81-22 (eğik düzlem
-- asansörler), TS EN 81-28 (yolcu/yük asansörleri uzaktan alarm) ve TS EN 81-77
-- (sismik durumlara tabi asansörler) checklist içerikleri kütüphaneye ekleniyor.
--
-- Kaynak: AVES Drive kontrol formları ÜB.FR.63/R.04 (81-21), ÜB.FR.57/R.03 (81-22),
-- ÜB.FR.62/R.03 (81-28), ÜB.FR.58/R.01 (81-77) — kodlar ve güncel revizyonlar
-- ÜB.LS.01 Ana Doküman Listesi ile çapraz doğrulanmıştır (81-21/81-22 dosya
-- adı/iç başlık uyuşmazlığı bu doğrulamayla çözüldü). Standart metinlerin kendisi
-- (TSE'den satın alınan tam metin) elde edilemediği için 81-22'deki dört madde
-- (kumanda tesisatı Ek-B/Ek-E darbe/kesilme testleri, kamuya açık işaretler) kesin
-- tanım yerine formun kendi iç deseninden çıkarılan mantıklı bir yorumla yazılmıştır
-- ve gerçek TS EN 81-22 metniyle doğrulanana kadar taslak niteliğindedir.
--
-- Bu dört standart mevcut "ek standart" mekanizmasına (seciliStandartGruplari /
-- ekStandartlar) eklenir; hiçbiri otomatik dahil edilmez, denetçi ilgili durumda
-- (mevcut bina / eğik düzlem / uzaktan alarm / sismik bölge) elle seçer. Mevcut
-- denetim kayıtlarına, madde kütüphanesindeki diğer satırlara veya RLS
-- politikalarına dokunulmaz — yalnız yeni satır eklenir.

begin;

do $$
declare
  v_count integer;
begin
  select count(*) into v_count from public.madde_kutuphanesi
  where madde_id between 'MAD-1011' and 'MAD-1074';
  if v_count <> 0 then
    raise exception 'MAD-1011..MAD-1074 aralığı zaten dolu (% satır bulundu), çakışma var', v_count;
  end if;
end
$$;

insert into public.madde_kutuphanesi
  (madde_id, sira_no, bolum, standart_grubu, kaynak_turu, standart_madde_no,
   kontrol_basligi, denetci_yonlendirmesi, yontem_kodu, dogrulama_yontemi,
   resmi_madde_metni, kaynak_form_kodu, kaynak_form_revizyonu, olcum_tanimlari, aktif)
values
  ('MAD-1011', 1011, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '5.2', 'Perfore duvar - kurcalamaya karşı koruma', 'İniş kapısı kilitleme düzenleri etrafında, 0,30 m''lik sert bir çubukla kurcalamayı önleyecek, perfore olmayan bir koruyucu ekran bulunduğunu kontrol edin.', 'A,D', 'Görsel + Ölçüm', 'İniş kapısı kilitleme düzenleri EN ISO 13857:2008 4.2.4.2''ye uygun olmalı; 0,30 m uzunluğundaki sert bir çubukla kurcalamayı önlemek için perfore olmayan koruyucu ekran sağlanmalıdır.', 'ÜB.FR.63', 'R.04', '[]'::jsonb, true),
  ('MAD-1012', 1012, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '5.3', 'Kabin-karşı ağırlık mesafesi', 'Kabin ile karşı ağırlık/dengeleme ağırlığı arası en az 25 mm mesafe olduğunu ölçün.', 'A,D', 'Görsel + Ölçüm', 'Kabin ve ilgili bileşenleri, karşı ağırlıktan veya dengeleme ağırlığından (varsa) ve ilgili bileşenlerinden en az 25 mm mesafede olacaktır.', 'ÜB.FR.63', 'R.04', '[{"id": "kabin_karsi_agirlik_mesafesi", "ad": "Kabin-karşı ağırlık mesafesi", "birim": "mm"}]'::jsonb, true),
  ('MAD-1013', 1013, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '5.4.1-5.4.3', 'Ayrı boşlukta karşı ağırlık', 'Karşı ağırlık ayrı boşlukta ise: muayene kapılarının varlığını, teçhizat-kapı arası ≤0,7 m mesafeyi, aydınlatma şiddetinin ≥50 lüks olduğunu ve kılavuzlama düzeninin uygun olduğunu kontrol edin.', 'A,D', 'Görsel + Ölçüm', 'Karşı ağırlık veya dengeleme ağırlığı kabinden ayrı bir boşlukta tesis edilebilir; bu durumda ayrı kuyunun her iki ucunda muayene kapıları, teçhizatla muayene kapıları arasında en fazla 0,7 m mesafe, en az 50 lüks aydınlatma ve uygun kılavuzlama sağlanmalıdır.', 'ÜB.FR.63', 'R.04', '[{"id": "ayrik_bosluk_aydinlatma_siddeti", "ad": "Aydınlatma şiddeti", "birim": "lux"}]'::jsonb, true),
  ('MAD-1014', 1014, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '5.5.1-5.5.2', 'Kabin çatısı-kuyu tavanı boşluğu (hareketli durdurucu/ön tetiklemeli sistem)', 'Üst boşluk azaltılmışsa hareketli durdurucu veya ön tetiklemeli durdurma sisteminin (tampon uyumu, ≥300N tetikleme kuvveti, elektriksel izleme) mevcut ve işlevsel olduğunu kontrol edin.', 'A,B,C,D', 'Görsel + Test + Ölçüm + Çizim/Hesap', 'Üst boşluk azaltıldıysa, kabin çatısı ile kuyu tavanı arası gerekli boşluğu sağlamak için hareketli durdurucular veya ön tetiklemeli bir durdurma sistemi bulunmalı; tetikleme kuvveti en az 300 N olmalı ve sistem elektriksel olarak izlenmelidir.', 'ÜB.FR.63', 'R.04', '[]'::jsonb, true),
  ('MAD-1015', 1015, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '5.5.3', 'Güvenlik sistemi (kabin çatısı)', 'Kabin çatısı erişim anahtarının güvenlik sistemini devreye aldığını ve resetlemenin yalnız yetkili erişimle mümkün olduğunu test edin.', 'A,C', 'Görsel + Test', 'Kabin çatısına erişim sağlayan kapı/kapak açıldığında normal çalışmayı etkisiz hale getiren, iki konumlu bir güvenlik sistemi çalışmalı ve yalnız elektriksel bir başlangıç konumuna getirme düzeniyle resetlenebilmelidir.', 'ÜB.FR.63', 'R.04', '[]'::jsonb, true),
  ('MAD-1016', 1016, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '5.5.4', 'Sesli/görsel bilgilendirme (kabin çatısı)', 'Durdurucu/tetikleme durumunun duraktan görülebildiğini veya duyulabildiğini test edin.', 'A,C', 'Görsel + Test', 'Durdurucu/tetikleme cihazının aktif/aktif olmayan konumu duraktan görülebilir ve/veya duyulabilir olmalıdır.', 'ÜB.FR.63', 'R.04', '[]'::jsonb, true),
  ('MAD-1017', 1017, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '5.5.5', 'Grup asansörlerde bölme', 'Komşu asansöre 2,0 m''den yakın küçültülmüş üst boşluk varsa bölmenin kuyu boyunca uzandığını ölçün.', 'A,D', 'Görsel + Ölçüm', 'Komşu asansörün küçültülmüş üst boşluğuna yatay mesafesi 2,0 m''den az olan yerlerde, erişimi engelleyen bir bölme kuyu yüksekliği ve derinliği boyunca uzanmalıdır.', 'ÜB.FR.63', 'R.04', '[]'::jsonb, true),
  ('MAD-1018', 1018, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '5.6', 'Uzatılabilir kabin çatısı korkuluğu', 'Korkuluğun kalıcı monte edildiğini, tam uzatılmadığında kabin hareketinin elektrik güvenlik cihazıyla engellendiğini test edin.', 'A,C,D', 'Görsel + Test + Ölçüm', 'Kabin tavanında korkuluk gerekiyorsa, kolayca ve güvenli şekilde uzatılabilen bir korkuluk kalıcı olarak monte edilmeli; 1000 N kuvvete şekil değiştirmeden dayanmalı ve korkuluk tam açılmadan/çekilmeden kabin hareket etmemelidir.', 'ÜB.FR.63', 'R.04', '[]'::jsonb, true),
  ('MAD-1019', 1019, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '5.7.1-5.7.4', 'Kuyu dibi azaltılmış boşluk (hareketli durdurucu/ön tetikleme)', 'Alt boşluk azaltılmışsa hareketli durdurucu/ön tetiklemeli sistem, güvenlik sistemi ve elektriksel izlemenin çalıştığını kontrol edin.', 'A,B,C,D', 'Görsel + Test + Ölçüm + Çizim/Hesap', 'Alt boşluk azaltıldıysa, kuyu dibi sığınma alanlarını sağlayan hareketli durdurucular veya ön tetiklemeli durdurma sistemi, güvenlik sistemi ve elektriksel izleme ile birlikte çalışmalıdır.', 'ÜB.FR.63', 'R.04', '[]'::jsonb, true),
  ('MAD-1020', 1020, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '5.7.5', 'Kuyu bölmesi (çoklu asansör)', 'Kuyu dibinden 4,0 m yüksekliğe kadar bölme bulunduğunu ölçün.', 'A,D', 'Görsel + Ölçüm', 'Kuyu birden fazla asansör içeriyorsa, en az kuyu dibi seviyesinden 4,0 m yüksekliğe kadar uzanan bir bölme sağlanmalıdır.', 'ÜB.FR.63', 'R.04', '[{"id": "kuyu_bolmesi_yuksekligi", "ad": "Bölme yüksekliği", "birim": "m"}]'::jsonb, true),
  ('MAD-1021', 1021, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '5.7.6', 'Kuyuya güvenli erişim', 'Kuyu dibi derinliği ≤ 0,50 m ise merdiven muafiyetinin ve iki erişim kapısı kuralının doğru uygulandığını kontrol edin.', 'A,D', 'Görsel + Ölçüm', 'Kuyu dibi derinliği 0,50 m''yi geçmiyorsa merdiven gerekli değildir; bu durumda aynı seviyede kuyuya erişim sağlayan iki durak kapısı varsa, her ikisi de erişim kapısı sayılır.', 'ÜB.FR.63', 'R.04', '[{"id": "kuyu_dibi_derinligi_81_21", "ad": "Kuyu dibi derinliği", "birim": "m"}]'::jsonb, true),
  ('MAD-1022', 1022, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '5.8', 'Uzatılabilir kabin etek sacı', 'Sabit etek sacı yoksa, uzatılabilir etek sacının (manuel veya otomatik varyant) elektrik güvenlik kilidi, kabin kapısı kilitleme cihazı ve yöne bağlı şalter şartlarını karşıladığını kontrol edin.', 'A,C,D', 'Görsel + Test + Ölçüm', 'Sabit etek sacı mümkün değilse, her kabin eşiği uzatılabilir bir etek sacı ile donatılmalı; etek sacı çekili konumdayken (veya uzatılmamışsa) kabin kapı kilitleme cihazı ve elektrik güvenlik düzeni ile normal çalışma nötralize edilmelidir.', 'ÜB.FR.63', 'R.04', '[]'::jsonb, true),
  ('MAD-1023', 1023, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '5.9', 'Makine odası yüksekliği', 'Makine dairesi çalışma alanı açık yüksekliğinin ≥1,80 m olduğunu ölçün; <2,1 m ise uyarı işareti/şeridi bulunduğunu kontrol edin.', 'A,D', 'Görsel + Ölçüm', 'Çalışma alanlarındaki açık yükseklik 1,80 m''den az olmamalıdır; 2,1 m''den az olduğunda uyarı işareti/şeridi konulmalıdır.', 'ÜB.FR.63', 'R.04', '[{"id": "makine_odasi_yuksekligi_81_21", "ad": "Makine odası yüksekliği", "birim": "m"}]'::jsonb, true),
  ('MAD-1024', 1024, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '5.10', 'Makine odası kapı yüksekliği', 'Makine dairesi erişim kapısının ≥0,60×1,70 m olduğunu ölçün; <1,80 m''de uyarı işareti olduğunu kontrol edin.', 'A,D', 'Görsel + Ölçüm', 'Erişim kapıları en az 0,60 m genişlikte ve en az 1,70 m yükseklikte olmalıdır; 1,80 m''den az yükseklikte uyarı işareti gerekir.', 'ÜB.FR.63', 'R.04', '[{"id": "makine_odasi_kapi_yuksekligi", "ad": "Kapı yüksekliği", "birim": "m"}, {"id": "makine_odasi_kapi_genisligi", "ad": "Kapı genişliği", "birim": "m"}]'::jsonb, true),
  ('MAD-1025', 1025, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '5.11', 'Makine/makara odası giriş kapağı boyutu', 'Makine/makara odası giriş kapağının ≥0,60×0,80 m açık geçiş sağladığını ölçün; <0,80 m''de uyarı işareti olduğunu kontrol edin.', 'A,D', 'Görsel + Ölçüm', 'Kişiler için erişim/kurtarma kapıları en az 0,60×0,80 m açık geçiş sağlamalı; bir boyut 0,80 m''den az ise uyarı işareti gerekir.', 'ÜB.FR.63', 'R.04', '[{"id": "giris_kapagi_yuksekligi", "ad": "Yükseklik", "birim": "m"}, {"id": "giris_kapagi_genisligi", "ad": "Genişlik", "birim": "m"}]'::jsonb, true),
  ('MAD-1026', 1026, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '5.12', 'Kat kapı yükseklikleri', 'Kat kapısı açık yüksekliğinin ≥1,80 m olduğunu ölçün; <2,0 m ise uyarı işareti ve eğik yüzey/yumuşak kaplama bulunduğunu kontrol edin.', 'A,D', 'Görsel + Ölçüm', 'Kat kapısı girişinin açık yüksekliği bina kısıtlarına göre mümkün en yüksek değerde olmalı ancak 1,80 m''den az olmamalıdır; 2,0 m''den az olduğunda uyarı işareti ve eğik yüzey veya yumuşak kaplama gerekir.', 'ÜB.FR.63', 'R.04', '[{"id": "kat_kapi_yuksekligi_81_21", "ad": "Kat kapısı yüksekliği", "birim": "m"}]'::jsonb, true),
  ('MAD-1027', 1027, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '6.2', 'Hizmete alma öncesi dinamik deneyler', 'Üst boşluk (boş kabin+beyan hızı) ve alt boşluk (yüklü kabin+beyan hızı) için hareketli durdurucu/ön tetikleme testinin yapıldığını doğrulayın.', 'A,D', 'Test', 'Hareketli durdurucu/ön tetiklemeli sistem, boş kabin+beyan hızında (üst boşluk) ve yüklü kabin+beyan hızında (alt boşluk) dinamik olarak test edilmeli, sonrasında normal kullanımı olumsuz etkileyecek bir durum olmadığı değerlendirilmelidir.', 'ÜB.FR.63', 'R.04', '[]'::jsonb, true),
  ('MAD-1028', 1028, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '6.3', 'Teknik dosyada küçültülmüş kuyu bilgisi', 'Teknik dosyada küçültülmüş kuyu koruyucu önlemleri hakkında bilgi bulunduğunu kontrol edin.', 'A', 'Belge incelemesi', 'Küçültülmüş kuyu durumunda alınan koruyucu önlemler hakkında bilgi teknik dosyada bulunmalıdır.', 'ÜB.FR.63', 'R.04', '[]'::jsonb, true),
  ('MAD-1029', 1029, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '7.1', 'Kullanım kılavuzu - özel önlemler', 'Kullanım kılavuzunda özel önlemlerin (güvenlik sistemi, durdurucu, etek sacı) fonksiyon-kullanım-bakım açıklaması ve varsa frenleme mesafeleri bulunduğunu kontrol edin.', 'A', 'Belge incelemesi', 'Talimat el kitabı, güvenlik sistemi/durdurucu/etek sacı gibi önlemlerin fonksiyon, kullanım ve bakımına dair açıklamalar; ön tetiklemeli sistem varsa asgari/azami frenleme mesafeleri içermelidir.', 'ÜB.FR.63', 'R.04', '[]'::jsonb, true),
  ('MAD-1030', 1030, '11 - TS EN 81-21 Mevcut Binalarda Kurulum', '81-21', 'Standart / ÜB.FR.63', '7.2', 'Zorunlu uyarı işaretleri', 'Küçültülmüş boşluk, korkuluk ve etek sacı uyarı işaretlerinin doğru konumda ve okunabilir boyutta olduğunu kontrol edin.', 'A', 'Görsel', 'Küçültülmüş üst/alt boşluk, uzatılabilir korkuluk ve uzatılabilir etek sacı için gerekli uyarı işaretleri doğru karakter boyutunda yerinde olmalıdır.', 'ÜB.FR.63', 'R.04', '[]'::jsonb, true),
  ('MAD-1031', 1031, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '5.2.2.3', 'Kuyu mahfaza boyutları', 'Kuyu mahfazasının eğime göre gerekli yatay mesafe ve yükseklik şartlarını karşıladığını ölçün.', 'B,C', 'Ölçüm + Çizim/Hesap', 'Kısmi/tam kapalı kuyu mahfazası, eğime göre gerekli yatay mesafe ve yükseklik şartlarını (45°''den büyük eğimde durak kapısı tarafında ≥3,5 m, diğer kenarlarda ≥2,5 m, hareketli kısımlara ≥0,5 m; 45°''den küçük eğimde iniş tarafında araç seyir alanı yüksekliği) karşılıyor mu.', 'ÜB.FR.57', 'R.03', '[{"id": "kuyu_mahfaza_yatay_mesafe", "ad": "Yatay mesafe", "birim": "m"}, {"id": "kuyu_mahfaza_egim", "ad": "Eğim", "birim": "°"}]'::jsonb, true),
  ('MAD-1032', 1032, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '5.2.2.4.1.2', 'Muayene/acil durum kapıları boyutu', 'Muayene ve acil durum kapılarının/tuzaklarının boyut şartlarını ve deliksiz/yangın uyumlu yapısını kontrol edin.', 'B,C', 'Ölçüm + Çizim/Hesap', 'Muayene kapıları ≥1,40×0,60 m, acil durum kapıları ≥1,80×0,35 m, muayene tuzakları ≤0,50×0,50 m olmalı; deliksiz olmalı ve yangın yönetmeliğine uygun olmalıdır.', 'ÜB.FR.57', 'R.03', '[{"id": "muayene_kapi_yuksekligi", "ad": "Yükseklik", "birim": "m"}, {"id": "muayene_kapi_genisligi", "ad": "Genişlik", "birim": "m"}]'::jsonb, true),
  ('MAD-1033', 1033, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '5.2.2.4.2.1', 'Merdiven/yürüme yolu uygunluğu', 'Merdiven/yürüme yolu boyutlarının ve acil kapılar arası mesafenin (≤11 m) uygun olduğunu ölçün.', 'B,C', 'Ölçüm + Çizim/Hesap', 'EN 131-2:2010+A1:2012''ye göre en az 0,50 m genişlikte, 0,35 m basamak genişliğinde kalıcı yürüme yolu veya merdiven bulunmalı; acil kapılar arası mesafe eğime göre ölçüldüğünde 11 m''yi geçmemelidir.', 'ÜB.FR.57', 'R.03', '[{"id": "merdiven_genisligi", "ad": "Genişlik", "birim": "m"}, {"id": "merdiven_basamak_genisligi", "ad": "Basamak genişliği", "birim": "m"}]'::jsonb, true),
  ('MAD-1034', 1034, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '5.2.2.5', 'Kuyu havalandırması', 'Kuyunun uygun şekilde havalandırıldığını kontrol edin.', 'C,D', 'Çizim/Hesap + Görsel', 'Kuyu uygun şekilde havalandırılmalıdır.', 'ÜB.FR.57', 'R.03', '[]'::jsonb, true),
  ('MAD-1035', 1035, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '5.2.3.2.1', 'Kabin duvarı darbe dayanımı', 'Kabin duvarlarının darbe dayanım sertifikasını/hesabını kontrol edin.', 'C,D', 'Çizim/Hesap + Görsel', 'Kabin duvarları, 5 cm²''lik alana dağılan 300 N''luk kuvvete her iki yüzde kalıcı deformasyon olmadan, 15 mm''den büyük elastik deformasyon olmadan dayanmalıdır.', 'ÜB.FR.57', 'R.03', '[]'::jsonb, true),
  ('MAD-1036', 1036, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '5.5.3.3', 'Kapı yanmazlık sınıfı', 'Kapı malzemesinin üretici sertifikasında EN 13501-1''e göre gerekli yanmazlık sınıfını (A1 = tamamen yanmaz; Kategori 2''de A2 = çok sınırlı yanıcılık da kabul edilir) karşıladığını belgeden kontrol edin.', 'C,D', 'Belge incelemesi', 'Kapı malzemesi EN 13501-1''e göre A1 sınıfında (Kategori 2 asansörlerde A1 veya A2) olmalıdır.', 'ÜB.FR.57', 'R.03', '[]'::jsonb, true),
  ('MAD-1037', 1037, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '5.5.6.3.3 (Ek J)', 'Kapı paneli darbe dayanımı belgesi', 'Üretici/test kuruluşunun sarkaç darbe testi raporunda kategoriye göre 700/1000 mm düşme şartının karşılandığını belgeden kontrol edin; Kategori 2''de cam panel bulunmadığını görsel doğrulayın.', 'C,D', 'Belge incelemesi + Görsel', 'Yumuşak sarkaç çarpma deneyinde Kategori 1 asansörler için 700 mm''den, Kategori 2 için 1000 mm''den düşme ile test edilmelidir; Kategori 2''de kapılarda cam panel kullanılamaz.', 'ÜB.FR.57', 'R.03', '[]'::jsonb, true),
  ('MAD-1038', 1038, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '5.5.6.3.3', 'Kapı paneli tutucu darbe dayanımı belgesi', 'Kapı paneli tutucusunun 1400 mm sarkaç düşme testi raporunun mevcut olduğunu belgeden kontrol edin.', 'C,D', 'Belge incelemesi', 'Kapı panel tutucusu, yumuşak sarkaç çarpma deneyinde 1400 mm''den düşme ile test edilmelidir.', 'ÜB.FR.57', 'R.03', '[]'::jsonb, true),
  ('MAD-1039', 1039, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '5.3.3.2', 'Makine dairesi duvar/pencere/kapı mukavemeti', 'Makine dairesi duvar/pencere/kapının mukavemet hesabını/sertifikasını kontrol edin; camsa lamine olduğunu doğrulayın.', 'C', 'Çizim/Hesap', 'Makine dairesi duvarı, penceresi ve kilitli giriş kapısı, 100 cm²''lik alana uygulanan 2500 N''luk kuvvete 15 mm''den fazla esneme veya kalıcı şekil bozukluğu olmadan dayanmalıdır; cam ise lamine olmalıdır.', 'ÜB.FR.57', 'R.03', '[]'::jsonb, true),
  ('MAD-1040', 1040, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '5.3.3.6', 'Makine dairesi havalandırma', 'Havalandırma açıklığı kesitini ölçüp düz çubuğun geçmediğini kontrol edin.', 'D', 'Görsel', 'Havalandırma açıklığı kesiti 250×250 mm''den küçük olmalı, düz bir çubuk geçmemelidir.', 'ÜB.FR.57', 'R.03', '[{"id": "havalandirma_en", "ad": "En", "birim": "mm"}, {"id": "havalandirma_boy", "ad": "Boy", "birim": "mm"}]'::jsonb, true),
  ('MAD-1041', 1041, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '—', 'İzinsiz giriş alarmı (Kategori 2)', 'Kategori 2 asansörlerde izinsiz giriş alarm sisteminin (ses seviyesi, süre, yedek enerji) mevcut olduğunu kontrol edin.', 'C,D', 'Çizim/Hesap + Görsel', 'Kategori 2 asansörlerde makine dairesi giriş kapısı, muayene/imdat kapıları/kapakları ve kumanda bölmesinde, 30 sn içinde 70-85 dB(A) seviyesinde 5-15 dk çalışabilen, en az 2 saat yedek enerjili bir izinsiz giriş alarm sistemi bulunmalıdır.', 'ÜB.FR.57', 'R.03', '[{"id": "izinsiz_giris_alarm_ses_seviyesi", "ad": "Ses seviyesi", "birim": "dB(A)"}]'::jsonb, true),
  ('MAD-1042', 1042, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '—', 'Kumanda panosu erişim güvenliği', 'Kumanda panosunun kategoriye uygun şekilde (Kategori 1: özel alet gerektiren montaj; Kategori 2: gizli/görünmez bağlantı) monte edildiğini kontrol edin.', 'C,D', 'Belge + Görsel', 'Kumanda panosunun sökülmesi Kategori 1''de yalnız özel bir sökme aletiyle mümkün olmalı; Kategori 2''de bağlantılar kullanıcı tarafından görülüp fark edilemeyecek şekilde gizlenmiş olmalıdır.', 'ÜB.FR.57', 'R.03', '[]'::jsonb, true),
  ('MAD-1043', 1043, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '—', 'Kabin/kumanda malzemesi yanmazlık sınıfı', 'Kabin duvar/tavan/taban malzemesinin üretici sertifikasında EN 13501-1''e göre gerekli sınıfı karşıladığı belgelensin: A1 = tamamen yanmaz malzeme, A2 = çok sınırlı yanıcılık gösteren malzeme, A2fl = zemin kaplamaları için A2''ye denk sınırlı yanıcılık sınıfı. Kategori 1''de A1, Kategori 2''de A2/A2fl kabul edilir.', 'C,D', 'Belge incelemesi', 'Kabin duvarları A1 sınıfında olmalı; Kategori 2 asansörlerde kabin duvarları ve tavanı A2 sınıfı, kabin zemini A2fl sınıfı olmalıdır (EN 13501-1''e göre yanmazlık sınıflandırması).', 'ÜB.FR.57', 'R.03', '[]'::jsonb, true),
  ('MAD-1044', 1044, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '—', 'Kumanda tesisatı darbe/vandalizm dayanımı', 'Kumanda tesisatının darbe dayanım sertifikasının (Ek-B testine göre) mevcut olduğunu belgeden kontrol edin.', 'C,D', 'Belge incelemesi', 'Kumanda butonu, gösterge ve donatıların üretici sertifikasında darbe dayanım testinden (standardın Ek-B''sinde tanımlanan yöntemle) geçtiği belgelenmelidir.', 'ÜB.FR.57', 'R.03', '[]'::jsonb, true),
  ('MAD-1045', 1045, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '—', 'Kumanda butonları kesilmeye dayanıklılık', 'Kumanda butonlarının yaygın kesme aletlerine karşı dayanıklılık sertifikasının (Ek-E testine göre) mevcut olduğunu belgeden kontrol edin.', 'C,D', 'Belge incelemesi', 'Kumanda butonu, gösterge ve donatılar, standardın Ek-E''sinde tanımlanan araçlarla kesilerek devre dışı bırakılamayacak şekilde tasarlanmalıdır.', 'ÜB.FR.57', 'R.03', '[]'::jsonb, true),
  ('MAD-1046', 1046, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '—', 'Durak kapı güvenlik sistemi (Kategori 2)', 'Durak kapı güvenlik sisteminin kilit açılmama, erişilebilirlik, otomatik devreye girme süresi, yedek güç süresi ve 81-72/81-73 ile otomatik devre dışı kalma şartlarını sağladığını test edin.', 'C,D', 'Belge + Görsel + Test', 'Kabin durak seviyesinde değilken durak kapısı kilidi açılmamalı; tertibat asansör yakınında erişilebilir olmalı; sistem 30-60 dk içinde otomatik devreye girmeli, en az 2 saat yedek güce sahip olmalı; 81-72/81-73''e uygun asansörlerde otomatik devre dışı kalmalıdır.', 'ÜB.FR.57', 'R.03', '[]'::jsonb, true),
  ('MAD-1047', 1047, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '—', 'Alarm tertibatı testi', 'Alarm butonuna basıp 70-85 dB(A) seviyesinde ses ürettiğini ve süresini test edin.', 'B,C,D', 'Ölçüm + Çizim/Hesap + Görsel', 'Kabin katta kapıları açık değilse, alarm butonu 60 saniye veya kapılar açılana kadar 70-85 dB(A) sesle çalmalıdır.', 'ÜB.FR.57', 'R.03', '[{"id": "alarm_ses_seviyesi_81_22", "ad": "Ses seviyesi", "birim": "dB(A)"}]'::jsonb, true),
  ('MAD-1048', 1048, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '—', 'Korozyon önlemleri (Kategori 2)', 'Kategori 2 asansörlerde listelenen bileşenlerin korozyona karşı koruma önlemlerinin (kaplama, malzeme seçimi vb.) mevcut olduğunu kontrol edin.', 'C,D', 'Belge + Görsel', 'Kategori 2 asansörlerde kabin askı tertibatı (destek elemanları dahil), durak/kabin kapıları, eşikler, destek elemanları, raylar, durak kapı kilitleri, kabin duvar ve tabanı temizleme çözücüleri/vücut sıvılarının neden olduğu korozyona karşı korunmalıdır.', 'ÜB.FR.57', 'R.03', '[]'::jsonb, true),
  ('MAD-1049', 1049, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '—', 'Kamuya açık işaretler', 'İşaretlerin sökülemez şekilde sabitlendiğini ve kurulumun kategorisine göre gerekli yangın dayanım süresini (Kategori 1: 60 sn, Kategori 2: 120 sn) sertifikadan kontrol edin.', 'C,D', 'Belge incelemesi', 'İşaretler yerlerinden çıkarılamayacak şekilde tespit edilmeli, 60 saniye içinde okunamaz hale getirilememeli ve yangın dayanımı sağlamalıdır: Kategori 1 asansörlerde en az 60 saniye, Kategori 2 asansörlerde (daha uzun süre istenmesi muhtemelen dış mekân/gözetimsiz kullanım riskinin daha yüksek olmasından) en az 120 saniye yangına dayanmalıdır.', 'ÜB.FR.57', 'R.03', '[{"id": "isaret_yangin_dayanim_suresi", "ad": "Yangın dayanım süresi", "birim": "sn"}]'::jsonb, true),
  ('MAD-1050', 1050, '12 - TS EN 81-22 Eğik Düzlem Asansörler', '81-22', 'Standart / ÜB.FR.57', '7.4', 'Kullanma kılavuzu - temizlik/hasar/korozyon bilgisi', 'Kullanma kılavuzunda mal sahibi ve bakım şirketi için yukarıdaki bilgilerin eksiksiz yer aldığını kontrol edin.', 'C,D', 'Belge incelemesi', 'Kullanma kılavuzunda; mal sahibine yönelik uygun temizlik malzemeleri, hasar kontrolü/hizmet dışı bırakma talimatı, taban temizliği ve yanıcı madde arındırma bilgisi; bakım şirketine yönelik kritik elemanların (askı, paten, kilit) korozyon muayene talimatı bulunmalıdır.', 'ÜB.FR.57', 'R.03', '[]'::jsonb, true),
  ('MAD-1051', 1051, '13 - TS EN 81-28 Uzaktan Alarm', '81-28', 'Standart / ÜB.FR.62', '4.1.2', 'Alarm iletimi ve yeniden deneme', 'Alarm butonuna basarak alındı bilgisine kadar tam alarm bilgisinin kesintisiz iletildiğini test edin.', 'B', 'İşlevsel Deney', 'Alarm donanımı, alarm filtrelemesine tabi olarak, bakım sırasında dahi alındı bilgisine kadar tam alarm bilgisinin yayılmasını sağlamalı; alındı bilgisinden önce kesilirse yeniden alarm gecikmesi en aza indirilmelidir.', 'ÜB.FR.62', 'R.03', '[]'::jsonb, true),
  ('MAD-1052', 1052, '13 - TS EN 81-28 Uzaktan Alarm', '81-28', 'Standart / ÜB.FR.62', '4.1.3', 'Alarm sonu bildirimi', 'Alarm sonu bildiriminin kurtarma servisine ulaştığını ve yalnız yetkili kişilerce başlatılabildiğini kontrol edin.', 'A,B,E', 'Görsel + Deney', 'Alarmın alındığı ve kimsenin mahsur kalmadığı kurtarma servisine gösterilmeli; alarm sonu yalnız asansör sisteminden ve yetkin kişilerce erişilebilir aygıtla başlatılmalıdır.', 'ÜB.FR.62', 'R.03', '[]'::jsonb, true),
  ('MAD-1053', 1053, '13 - TS EN 81-28 Uzaktan Alarm', '81-28', 'Standart / ÜB.FR.62', '4.1.4', 'Acil durum güç kaynağı', 'Güç kesintisi simülasyonunda alarmın devam ettiğini, yedek güç kapasitesinin (≥1 saat, 15 dk sesli iletişim dahil) yeterli olduğunu ve kesinti bildiriminin çalıştığını test edin.', 'A,B,D,E', 'Görsel + Deney + Çizim/Hesap', 'Güç kesintisinde alarm engellenmemeli veya kaybolmamalı; acil durum güç kaynağı, 15 dakikalık sesli iletişim dahil en az 1 saat alarm sistemi çalışmasını sağlamalı ve kesinti kurtarma servisine bildirilmelidir.', 'ÜB.FR.62', 'R.03', '[]'::jsonb, true),
  ('MAD-1054', 1054, '13 - TS EN 81-28 Uzaktan Alarm', '81-28', 'Standart / ÜB.FR.62', '4.1.5', 'Kabin içi görsel/sesli bilgilendirme', 'Kabin panelindeki sarı/yeşil simgelerin ve sesli sinyalin (35-65 dB(A)) doğru çalıştığını test edin.', 'A,B,D,E', 'Ölçüm + Görsel + Deney + Çizim/Hesap', 'Kabin panelinde alarm doğrulandığında yanan sarı simge, sesli iletişim sırasında yanan yeşil simge ve 35-65 dB(A) arasında ayarlanabilir sesli sinyal bulunmalıdır.', 'ÜB.FR.62', 'R.03', '[{"id": "alarm_sesli_sinyal_seviyesi", "ad": "Ses seviyesi", "birim": "dB(A)"}]'::jsonb, true),
  ('MAD-1055', 1055, '13 - TS EN 81-28 Uzaktan Alarm', '81-28', 'Standart / ÜB.FR.62', '4.1.6', 'Alarm filtreleme mantığı', 'Kapı açıkken/hareket halindeyken alarmın tetiklenmediğini, kısa basışta ve manuel test modunda doğru çalıştığını test edin.', 'B,D,E', 'Deney + Çizim/Hesap + Belge', 'Kabin kilit açılma bölgesinde kapılar açıkken veya kabin hareket halindeyken alarm başlatılmamalı; alarm başlatma cihazına 3 sn''den kısa basışta alarm başlayabilmeli; sistem en fazla 30 sn sürekli basışla manuel test edilebilmeli; yetkili kişi filtrelemeyi aç/kapatabilmelidir.', 'ÜB.FR.62', 'R.03', '[]'::jsonb, true),
  ('MAD-1056', 1056, '13 - TS EN 81-28 Uzaktan Alarm', '81-28', 'Standart / ÜB.FR.62', '4.1.7', 'Asansör kimlik tanıma', 'Test alarmında kurtarma servisinin asansörü doğru tanıdığını kontrol edin.', 'B,E', 'Deney + Belge', 'Alarm donanımı, deneme alarmlarında dahi kurtarma servisinin hangi asansörden geldiğini tanıyabilmesini sağlamalıdır.', 'ÜB.FR.62', 'R.03', '[]'::jsonb, true),
  ('MAD-1057', 1057, '13 - TS EN 81-28 Uzaktan Alarm', '81-28', 'Standart / ÜB.FR.62', '4.1.8', 'İki yönlü iletişim', 'Alarm sonrası iki yönlü iletişimin otomatik kurulduğunu, kesilemediğini ve diğer ses kaynaklarının engellemediğini test edin.', 'B,D,E', 'Deney + Çizim/Hesap + Belge', 'Alarm başlatıldıktan sonra kullanıcı ek bir işlem yapmadan iletişim kurulmalı, kullanıcı iletişimi kesememeli ve varsa başka ses kaynakları (müzik vb.) sesli iletişimi engellememelidir.', 'ÜB.FR.62', 'R.03', '[]'::jsonb, true),
  ('MAD-1058', 1058, '13 - TS EN 81-28 Uzaktan Alarm', '81-28', 'Standart / ÜB.FR.62', '4.2.1', 'Otomatik öz-test ve güvenilirlik', 'Otomatik öz-test kaydının en az 3 günde bir yapıldığını ve arıza göstergesinin 1 saat içinde tetiklendiğini kontrol edin.', 'B,D,E', 'Deney + Çizim/Hesap + Belge', 'Sistem en az 3 günde bir otomatik deneme sinyali göndermeli; otomatik test arızası, bir sonraki başarılı bağlantıya kadar en geç 1 saat içinde yanıp sönen gösterge ile bildirilmelidir.', 'ÜB.FR.62', 'R.03', '[]'::jsonb, true),
  ('MAD-1059', 1059, '13 - TS EN 81-28 Uzaktan Alarm', '81-28', 'Standart / ÜB.FR.62', '4.2.2', 'Elektrik arayüzü uyumu', 'Elektrik arayüzünün EN 81-20 ilgili maddelerine uygunluğunu teknik dosyadan kontrol edin.', 'D', 'Çizim/Hesap', 'Alarm sistemi ile asansörün elektrikli güvenlik aygıtları arasındaki elektrik arayüzleri EN 81-20 Madde 5.10.3.2 ve 5.11.2.1.2''ye uygun olmalıdır.', 'ÜB.FR.62', 'R.03', '[]'::jsonb, true),
  ('MAD-1060', 1060, '13 - TS EN 81-28 Uzaktan Alarm', '81-28', 'Standart / ÜB.FR.62', '4.2.3', 'Alarm başlatma cihazı konumu', 'Alarm butonunun kabin panelindeki konumunu ve zeminden yüksekliğini (850-1200 mm) ölçün.', 'A,B,C', 'Ölçüm + Görsel + Çizim/Hesap', 'Alarm başlatma cihazı kabin kontrol paneline veya bitişiğine, kabin zemininden 850-1200 mm yükseklikte yerleştirilmelidir.', 'ÜB.FR.62', 'R.03', '[{"id": "alarm_dugmesi_yuksekligi", "ad": "Yükseklik", "birim": "mm"}]'::jsonb, true),
  ('MAD-1061', 1061, '13 - TS EN 81-28 Uzaktan Alarm', '81-28', 'Standart / ÜB.FR.62', '4.2.4', 'Alarm donanımına erişim kısıtı', 'Alarm donanımının yalnız yetkili erişime açık bir konumda olduğunu kontrol edin.', 'A', 'Görsel', 'Alarm donanımı yalnız yetkilendirilmiş kişilerin erişebileceği bir yere tesis edilmelidir.', 'ÜB.FR.62', 'R.03', '[]'::jsonb, true),
  ('MAD-1062', 1062, '13 - TS EN 81-28 Uzaktan Alarm', '81-28', 'Standart / ÜB.FR.62', '4.2.5', 'Parametre değiştirme koruması', 'Alarm sistemi ayarlarına erişimin şifre/kod ile korunduğunu kontrol edin.', 'D,E', 'Çizim/Hesap + Belge', 'Alarm sisteminin işlevsellik parametrelerine erişim, erişim kodları gibi uygun araçlarla korunmalıdır.', 'ÜB.FR.62', 'R.03', '[]'::jsonb, true),
  ('MAD-1063', 1063, '14 - TS EN 81-77 Sismik Durumlar', '81-77', 'Standart / ÜB.FR.58', '5.2', 'Kuyu yüksekliğine göre sismik koruma', 'Kuyu yüksekliğine göre (20-60m veya >60m) gerekli minimum mesafelerin veya koruma telinin sağlandığını ölçün.', 'A,C', 'Görsel + Ölçüm', 'Kuyu yüksekliği ≤20 m için ek önlem gerekmez. 20-60 m arası: sabitler ile hareketli parçalar arası gerekli mesafeler (kontrol kabloları ≥900 mm, denge halatı/zinciri/karşı ağırlık regülatör halatı ≥750 mm, kabin regülatör halatı ≥500 mm, askı halatları ≥300 mm) veya koruma teli sağlanmalıdır. >60 m''de mesafeden bağımsız tüm çıkıntı noktaları koruma teli/halatı ile korunmalıdır. (→ 2014/33/AB Ek I 2.2, 3.2)', 'ÜB.FR.58', 'R.01', '[{"id": "kuyu_yuksekligi_81_77", "ad": "Kuyu yüksekliği", "birim": "m"}]'::jsonb, true),
  ('MAD-1064', 1064, '14 - TS EN 81-77 Sismik Durumlar', '81-77', 'Standart / ÜB.FR.58', '5.3', 'Dilatasyon derzi - asansör yerleşimi', 'Asansörün tüm bileşenlerinin dilatasyon derzinin aynı tarafında yer aldığını kontrol edin.', 'D,A', 'Çizim/Hesap + Görsel', 'Bina dilatasyon derzleriyle bağımsız bloklara bölünüyorsa, asansörün tüm bölümleri (giriş holleri, kuyu, makineler dahil) dilatasyon bölümünün aynı tarafına yerleştirilmelidir. (→ 2014/33/AB Ek I 2.1, 2.2, 3.2)', 'ÜB.FR.58', 'R.01', '[]'::jsonb, true),
  ('MAD-1065', 1065, '14 - TS EN 81-77 Sismik Durumlar', '81-77', 'Standart / ÜB.FR.58', '5.4.1', 'Sismik ek yük hesabı', 'Teknik dosyadaki sismik yük hesabında kabin+beyan yükün asansör tipine göre (%40 yolcu / %80 yük) artırıldığını kontrol edin.', 'D,C', 'Çizim/Hesap + Ölçüm', 'Deprem tasarım ivmesi nedeniyle oluşacak ek kuvvet hesabına, yolcu asansörlerinde kabin kütlesi + beyan yükün %40''ı, yük asansörlerinde kabin kütlesi + beyan yükün %80''i eklenmiş olmalıdır. (→ 2014/33/AB Ek I 1.1.2, 3.1, 5.1)', 'ÜB.FR.58', 'R.01', '[]'::jsonb, true),
  ('MAD-1066', 1066, '14 - TS EN 81-77 Sismik Durumlar', '81-77', 'Standart / ÜB.FR.58', '5.4.2', 'Kabin acil durum kılavuzu (Sismik Kategori 2/3)', 'Teknik dosyada beyan edilen sismik kategori 2/3 ise, kabin acil durum kılavuzunun (üst/alt ray tutucu), açıklık ve bindirme şartlarını sağladığını kontrol edin.', 'A,B,C', 'Görsel + Deney + Ölçüm', 'Sismik Kategori 2 ve 3 asansörlerde kabin süspansiyonunda üst ve altta ek destek acil durum kılavuzu (ray tutucu) bulunmalı; tutucu-ray açıklığı (d1,d2,d3) 5 mm''yi sağlamalı, deprem esnemesinde ray palasında en az 5 mm bindirme kalmalıdır. (→ 2014/33/AB Ek I 3.2, 3.3, 4.1, 5.5, 5.6)', 'ÜB.FR.58', 'R.01', '[]'::jsonb, true),
  ('MAD-1067', 1067, '14 - TS EN 81-77 Sismik Durumlar', '81-77', 'Standart / ÜB.FR.58', '5.4.3', 'Kabin kapı kilitleme (Sismik Kategori 2/3)', 'Kabin kapı kilitleme tertibatının TS EN 81-20 5.3.9.2''ye uygun çalıştığını test edin.', 'A,B', 'Görsel + Deney', 'Sismik Kategori 2 ve 3 asansörlerde kabin kapısı kilitleme tertibatı ve çalışma şekli TS EN 81-20 Madde 5.3.9.2''ye uygun olmalıdır. (→ 2014/33/AB Ek I 3.4, 3.5, 4.3)', 'ÜB.FR.58', 'R.01', '[]'::jsonb, true),
  ('MAD-1068', 1068, '14 - TS EN 81-77 Sismik Durumlar', '81-77', 'Standart / ÜB.FR.58', '5.5', 'Karşı ağırlık acil durum kılavuzu', 'Karşı ağırlığın acil durum kılavuzunun, kabinle aynı açıklık ve esneme şartlarını sağladığını kontrol edin.', 'A,C', 'Görsel + Ölçüm', 'Karşı ağırlık veya dengeleme ağırlığı çerçevesini kılavuz raylar arasında tutan üst ve alt acil durum kılavuzuna (ray tutucu) sahip olmalı; kabindekiyle aynı açıklık (≤5 mm) ve bindirme/esneme şartlarını sağlamalıdır. (→ 2014/33/AB Ek I 3.3, 4.1, 5.5, 5.6)', 'ÜB.FR.58', 'R.01', '[]'::jsonb, true),
  ('MAD-1069', 1069, '14 - TS EN 81-77 Sismik Durumlar', '81-77', 'Standart / ÜB.FR.58', '5.6', 'Halat/zincir oluk çıkma önleyici', 'Kasnak/makara ve dişlilerdeki oluk/zincir çıkma önleyici tutucuların konumlarını (15° ve her 90°) kontrol edin.', 'A,B', 'Görsel + Deney', 'Kasnak/makara oluklarına halat giriş-çıkış noktalarının 15°''lik kısmında bir tutucu, her 90°''lik sarım kısmında en az bir ara tutucu bulunmalı; zincirli sistemlerde dişli giriş-çıkış noktalarının 15°''i içinde tutucu olmalıdır. (→ 2014/33/AB Ek I 5.6, 5.7, 5.8)', 'ÜB.FR.58', 'R.01', '[]'::jsonb, true),
  ('MAD-1070', 1070, '14 - TS EN 81-77 Sismik Durumlar', '81-77', 'Standart / ÜB.FR.58', '5.9', 'Makine/ekipman sabitleme', 'Makine ve kaldırma ekipmanlarının deprem kuvvetine karşı sabitlendiğini, hidrolik tesisatta esnek boru şartının sağlandığını kontrol edin.', 'A,D', 'Görsel + Çizim/Hesap', 'Tüm makineler, kasnaklar, tavan kirişleri, halat bağlantıları, aşırı hız düzenleyici, gergi makaraları ve dengeleme halatı gerdirme cihazları deprem ivmesine karşı devrilme/yer değiştirmeyi önleyecek şekilde tasarlanıp sabitlenmelidir; hidrolik asansörlerde tercihen esnek boru, sert boru kullanılıyorsa her sert uzunluğun ucunda esnek boru bulunmalıdır. (→ 2014/33/AB Ek I 2.2, 4.1, 5.9, 6.1)', 'ÜB.FR.58', 'R.01', '[]'::jsonb, true),
  ('MAD-1071', 1071, '14 - TS EN 81-77 Sismik Durumlar', '81-77', 'Standart / ÜB.FR.58', '5.10.1', 'Kuyu içi elektrik donanımı sabitleme', 'Kuyu içi elektrik donanımının deprem kuvvetine karşı sabitlendiğini ve salınıma karşı korunduğunu kontrol edin.', 'A,C', 'Görsel + Ölçüm', 'İniş anahtarı cihazları, son limit anahtarları, kanatlar vb. kuyu içi elektrik donanımının montajı deprem kuvvetine dayanacak şekilde tasarlanmalı ve kuyu içi salınımlara karşı korunmalıdır. (→ 2014/33/AB Ek I 3.2, 3.3, 4.5, 6.2)', 'ÜB.FR.58', 'R.01', '[]'::jsonb, true),
  ('MAD-1072', 1072, '14 - TS EN 81-77 Sismik Durumlar', '81-77', 'Standart / ÜB.FR.58', '5.10.2', 'Güç kesintisinde kurtarma (Sismik Kategori 2/3)', 'Güç kesintisi simülasyonunda kabinin bir sonraki durağa gidip kapı açtığını (veya manuel kapılarda kilidin açıldığını) test edin.', 'A,B', 'Görsel + Deney', 'Sismik Kategori 2 ve 3 asansörlerde normal güç beslemesi kesildiğinde kabin otomatik olarak bir sonraki durağa hareket edebilecek ek enerji kaynağına sahip olmalı; otomatik kapılı asansörlerde durakta kapı açılıp asansör normal çalışmadan çıkarılmalı; manuel kapılarda kabin durağa ulaştığında kapı kilidi açılmalıdır. (→ 2014/33/AB Ek I 4.1.2, 6.3, 1.4)', 'ÜB.FR.58', 'R.01', '[]'::jsonb, true),
  ('MAD-1073', 1073, '14 - TS EN 81-77 Sismik Durumlar', '81-77', 'Standart / ÜB.FR.58', '5.10.3', 'Sismik algılama sistemi (Sismik Kategori 3)', 'Teknik dosyada beyan edilen sismik kategori 3 ise, sismik algılama sisteminin tetik seviyesi, tepki süresi, öz-test periyodu, yedek güç süresi, manuel sıfırlama ve gösterge şartlarını sağladığını kontrol edin.', 'A,B,C,D', 'Görsel + Deney + Ölçüm + Çizim/Hesap', 'Sismik Kategori 3 asansörlerde üç eksenli ivme sensörüne sahip bir sismik algılama sistemi bulunmalıdır: tetik seviyesi ≤1,00 m/s² (0,5-10 Hz), sistem tepki süresi ≤3 sn, otomatik öz-test ≤24 saatte bir, yedek güç ≥24 saat, sıfırlama yalnız manuel ve yetkili erişimle, sismik mod göstergesi manuel sıfırlama cihazı yakınında görünür olmalıdır. (→ 2014/33/AB Ek I 4.1.2, 4.3, 5.10, 6.2, 2.4)', 'ÜB.FR.58', 'R.01', '[]'::jsonb, true),
  ('MAD-1074', 1074, '14 - TS EN 81-77 Sismik Durumlar', '81-77', 'Standart / ÜB.FR.58', '5.10.4', 'Sismik mod davranışı', 'Sismik mod tetiklendiğinde çağrıların iptal edildiğini, kabin davranışının (≤0,3 m/s, karşı ağırlıktan uzak durak, kapı açma) doğru olduğunu test edin.', 'A,B', 'Görsel + Deney', 'Sismik algılama tetiklendiğinde tüm kayıtlı çağrılar iptal edilmeli, yeni çağrı kabul edilmemeli; asansör hareket halindeyse en fazla 0,3 m/s hızla karşı ağırlıktan uzak bir konumda durup kapılarını açmalı ve yeni komut almamalı; iniş halindeyse otomatik kapılarda kapı açılıp hizmet dışı kalınmalı, manuel kapılarda kilitlenmeden hizmet dışı bırakılmalıdır. (→ 2014/33/AB Ek I 4.1.2, 5.5, 6.3, 3.4, 3.5)', 'ÜB.FR.58', 'R.01', '[]'::jsonb, true);

update public.kutuphane_bolum_surumleri
set surum = surum + 1, updated_at = now()
where bolum in (
  '11 - TS EN 81-21 Mevcut Binalarda Kurulum',
  '12 - TS EN 81-22 Eğik Düzlem Asansörler',
  '13 - TS EN 81-28 Uzaktan Alarm',
  '14 - TS EN 81-77 Sismik Durumlar'
);

insert into public.kutuphane_bolum_surumleri (bolum, surum, updated_at)
select b, 1, now()
from unnest(array[
  '11 - TS EN 81-21 Mevcut Binalarda Kurulum',
  '12 - TS EN 81-22 Eğik Düzlem Asansörler',
  '13 - TS EN 81-28 Uzaktan Alarm',
  '14 - TS EN 81-77 Sismik Durumlar'
]) as b
where not exists (
  select 1 from public.kutuphane_bolum_surumleri k where k.bolum = b
);

commit;

-- Salt okunur doğrulama.
select bolum, standart_grubu, count(*) as adet
from public.madde_kutuphanesi
where madde_id between 'MAD-1011' and 'MAD-1074'
group by bolum, standart_grubu
order by bolum;
